### ISSUE TITLE
a how-to is required for this repo.

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/talks#10]
For people stumbling upon this repo with an intention of proposing a talk a how-to document outlining the process would be very helpful.

**Comment by satyaakam** [comment]
@bhanuvrat are you saying there is no proper documentation on how to propose a talk here ?

**Comment by bhanuvrat** [comment]
sort of.
Lets have a line mentioning "open an issue" and encouraging every one to come forth on the website also.

**Comment by theskumar** [comment]
Agreed. Now we can also add a `issue_template.md` to help create a proper issue/talks submission. Got any suggestions what all to include there?

**Comment by shagunsodhani** [comment]
[This](https://github.com/pydatadelhi/talks/blob/master/.github/ISSUE_TEMPLATE.md) is the `issue_template.md` that PyDataDelhi uses. We could use the same.

**Comment by aktech** [comment]
> This is the issue_template.md that PyDataDelhi uses. We could use the same.

Probably too much of an overhead for the small volume of talk proposal we receive, these days.

**Comment by shagunsodhani** [comment]
I have added a trimmed down version of the template file. Do let me know if we can trim it down further :)
