### ISSUE TITLE
cyber security

### ISSUE THREAD

**Issue by Shipra2071** [pydelhi/talks#103]
- Title

- Brief description about the content to be covered

- Time required for the talk

- Link to slides / demos / any other content (if any)

- About yourself

- Any comments

**Comment by rajataaron** [comment]
@Shipra2071 did you created this issue mistakenly?

**Comment by Shipra2071** [comment]
Actually, Sir I was created it As,it is a big issue nowadays but as I am
persuing Btech and I am in 3rd year so I was busy in my college work and I
was unable to continue that .
I am very very sorry for that.
