### ISSUE TITLE
Proposal: Code clean and safe with static type checking

### ISSUE THREAD

**Issue by shubhamdhama** [pydelhi/talks#104]
# Code clean and safe with static type checking

## Abstract

One of the reasons Python is famous for is its dynamically typed behavior, but this
advantage fades away while maintaining codebase as it grows in size and when you've
to look into your code you've written months ago. This is a common problem faced by
many large organizations like dropbox, facebook, Instagram etc. which uses python at
a really large commercial scale; so they have approached to solve this problem in a
standard way and some have devised their own tools.

So let's learn how to bring the assurance of "statically typed languages to Python"!!
Isn't that cool :) Why to put the screws on your head to remember what a variable is
supposed to do months ago and why to use comments for documenting our arguments and
variables! let's do something pythonic and use python's one of the "Official" features
and make our code more safe, clean and idiomatic. We will cover everything about static
type checking from examples to basic idea how it works under the hood.

Anyone having beginner to expert knowledge of python is welcomed; even if you have
familiarity with any language you'll still find this talk interesting as python's syntax
is pretty much obvious also I'll give enough code examples with line by line analysis
which will make things easier to assimilate. And don't worry if any technical term above
doesn't make sense you currently, I'll cover every jargon in the talk.

<h2>Description</h2>

It's a 30 minutes talk which will cover everything about how python brought the safety
with clarity at the same time of statically typed languages. We will discuss
[PEP 0484](https://www.python.org/dev/peps/pep-0484/) and the standard static type checker
[mypy](http://www.mypy-lang.org/). The whole talk is a presentation based where I'll give
basic python code examples explaining the need of this tool and how we solve this with many
other examples ranging from data variable type-checking to more advanced world examples
(and really don't worry, everything would be easy for anyone to understand). To make the
talk little interesting I'll give some real-world example from a real-world production
code.

Static type checking is proved to be a one of the most helpful feature and tool to python
developers who have maintain and work on the codebase of any scale from thousand line to
million lines. The whole story becomes even more interesting when we know that the BDFL
of Python Guido van Rossum himself is one of the active core members of this mypy project.

After this talk, I bet you would have perfect foundation to move forward and apply the
knowledge in the codebase you work.

## About me

```python3
>>> name    = 'Shubham Dhama'
>>> twitter = '@geekdhama'
>>> github  = 'shubhamdhama'
>>> bio = (
...     "Open source contributor"
...     "Contributing to @zulip under 'Google Summer of Code' program this summer."
...     "I love python, js and cpp"
... )
```

**Comment by shubhamdhama** [comment]
Hey, let me know if this topic interests you. My this talk is inspired by one of the core members of the zulip project who have recently given a talk related to this in PyCon Cleveland as 
> Zulip is now the largest open source Python project that has fully adopted static types.



Also, I want to mention it would be really great if I get the opportunity to give this talk on 7th July event as I've to leave for a meetup in Kerala on 8th for a week and after that, I'd to report to college.

Feel free to contact me at https://linkedin.com/in/shubhamdhama/.

**Comment by th3b0s5** [comment]
@shubhamdhama I'm kinda new here, and probably will be attending the 7th July event, and I'd love to hear your talk!

**Comment by shubhamdhama** [comment]
Closing this since the proposal was shifted from 7th to 8th. Anyway, it's a great community, I'll try again. Thanks.
