### ISSUE TITLE
Digital Security Training

### ISSUE THREAD

**Issue by shashikanth171** [pydelhi/talks#106]
# Title

Digital Security Training - Online Threats and Protection

# Brief description about the content to be covered

Malware is software designed to do perform unintended often malicious actions without the users’ permission. Phishing attacks collect users’ sensitive information such as usernames, passwords, location, financial information usually by disguising as trustworthy communication.

People are tracked on-line. Their digital profiles being created using the records of their browsing history and on-line activity. Detailed digital profiles can reveal sensitive information such as person’s real time location & activity, personal interests, political opinions, social circles/communities. This information can be used to influence people’s in many ways. This is what happened in the case of Cambridge Analytica using users’ data from Facebook to influence their political opinions.

In this workshop, participants are informed about common on-line threats such as malware, phishing attacks and user tracking. Participants are also informed about basic digital security measures and trained in using security add-ons on Firefox browser to protect their data from the mentioned on-line threats.

# Time required for the talk

2 hours

# Link to slides / demos / any other content (if any)

For more information visit, https://digitalsecuritytraining.sflc.in/

# About yourself

Shashikanth is a Technical officer at Software Freedom Law Center, India (https://sflc.in).

SFLC.IN is a donor supported legal services organisation that brings together lawyers, policy analysts, technologists, and students to protect freedom in the digital world. SFLC.IN promotes innovation and open access to knowledge by helping developers make great Free and Open Source Software, protect privacy and civil liberties for citizens in the digital world by educating and providing free legal advice and help policy makers make informed and just decisions with the use and adoption of technology.

SFLC.IN is a society registered under the Societies Registration Act, 1860, operating all over India.

**Comment by rajataaron** [comment]
@shashikanth171 I guess you have proposed a whole training program for digital security system.

**Comment by shashikanth171** [comment]
This training will be compact to cover common online threats and how to protect against them.
