### ISSUE TITLE
Learning how to learn efficiently

### ISSUE THREAD

**Issue by juggernaut451** [pydelhi/talks#109]
## Title
Learning how to learn efficiently

## Brief description about the content to be covered
- Why is learning important for developers
- What are the different way to enhance your learning skill
- How the human body works while we learn

## Time required for the talk
30 mins

## About yourself

[http://juggernaut451.com](http://juggernaut451.com)

## Any comments
All developers are in process of learning new things. Here time plays a vital role. One could save time if learning could be done efficiently. Discussing the challenges and importance of learning one could get to the goal faster.

This would be an unconventional talk to be allowed into PyDelhi's meetups. However, one I believe the developer need.

**Comment by rajataaron** [comment]
@juggernaut451 are you available to deliver your talk on 4th August meetup?

**Comment by juggernaut451** [comment]
yes

**Comment by rajataaron** [comment]
This talk has been delivered successfully. I am closing this issue.
