### ISSUE TITLE
Proposal: Understanding Python Dataclasses

### ISSUE THREAD

**Issue by xssChauhan** [pydelhi/talks#113]
Python 3.7 introduces new `dataclass`. 

They are an important feature because they help devs save time and write cleaner code.

I shall be discussing the following:

- ### The need of dataclasses 
         
         They have been an important of Kotlin, and one of the attractions of the language. 
         So how do they benefit Python development?

- ### The working of dataclasses

         The behavior and working of dataclasses can be customized to a great extent. 
         I shall be discussing the various features and fine grained control on their 
         behaviour.

- ### Use Cases

        Many people find it difficult to grasp the use cases where dataclasses are useful. 
        I shall be discussing a few use cases I have encountered in my work. 

**Expected duration of Talk:** 1 - 1.5 hours

**Links to my blogs on Dataclasses**: [Part 1](https://medium.com/mindorks/understanding-python-dataclasses-part-1-c3ccd4355c34), [Part 2](https://medium.com/mindorks/understanding-python-dataclasses-part-2-660ecc11c9b8)

Some links about myself:

-   [LinkedIn](https://goo.gl/giuERK) 
-   [StackOverflow](https://goo.gl/bcHha8)

**Comment by Gouravchawla** [comment]
Hi. Are you available to deliver the talk on 1st September meetup?
Reply ASAP(preferably by EOD today).

Location: E2E Newtworks Limited
24, Awfis, A, 9, Mathura Rd, Mohan Cooperative Industrial Estate, · Delhi

**Comment by xssChauhan** [comment]
I'm not in Delhi from 1st - 9th. Can do it on the next meeting.

**Comment by aaqaishtyaq** [comment]
Hi. Are you available to deliver the talk on 29th September meetup?

**Comment by im-gozmit** [comment]
Hey @xssChauhan. 
Are you available to deliver your talk on 22nd December meetup?

**Comment by xssChauhan** [comment]
Yup, I'll be available.

**Comment by xssChauhan** [comment]
@im-gozmit Any updates?

**Comment by aaqaishtyaq** [comment]
Hi @xssChauhan, Your talk has been scheduled for our upcoming meetup on 22nd December.
Venue: Broctagon Solutions,
6th Floor Tower A, Green Boulevard, B – Block Sector 62, Noida, Delhi.
