### ISSUE TITLE
Proposal: 'Ensemble Learning: introduction, methods and applications'

### ISSUE THREAD

**Issue by anjalibhavan** [pydelhi/talks#114]
This talk covers ensemble learning, a paradigm of machine learning. Ensemble learning consists of combining multiple learning models for predictions, and is a popular method for predictions and analysis. I will go through the various kinds of ensemble methods and applications in various real-world problems, and also share tips and resources for building and deploying good ensembles.
I will discuss the limitations of current machine learning models and why ensemble learning is the future of data science. I will dive forth into the various types of ensembles, their applications, how to get started with building your own multiple classifier systems etc in great detail. I will also share resources, applications, tips etc. for the same.

Additional Link: Here is the link to learn more in-depth about ensembles and what I'll be discussing in my talk. https://docs.google.com/document/d/1LH50XN5qXVKfr7bY65H3yUkVjtr4dOa8huCIka7-GL0/edit?usp=sharing

Time required for the talk: 20-25 minutes

Level: Intermediate

About Me: I am a third year engineering undergrad at Delhi Technological University (DTU). I have done several projects in the field of Machine Learning, and authored a research paper as well, on the task of human activity recognition from accelerometer data. I am currently working on speaker-independent speech emotion recognition, and other projects. I am passionate about math, artificial intelligence and literature, and believe that there is much potential to be harnessed still in Machine Learning.

**Comment by aaqaishtyaq** [comment]
Hi. Are you available to deliver the talk on 29th September meetup?

**Comment by anjalibhavan** [comment]
Hi! No, unfortunately I have exams around that time so. I'll be free in October.

**Comment by aaqaishtyaq** [comment]
Okay
