### ISSUE TITLE
How to make a CRUD REST API in 20 mins

### ISSUE THREAD

**Issue by GauravJain98** [pydelhi/talks#117]
- Title: How to make a CRUD REST API in 20 mins

- Explaining what REST API is. Types of requests needed to make a CRUD application. How to work that on Django REST API using with the raw implementation of JsonResponse.The need for serializers for SQL DB. How to use DjangoRESTFramework's modelserializer and modelviewset.

- 30-40 mins

- [Slides ](https://docs.google.com/presentation/d/12li0tnQIH-tMnFKImUgs7a3m6gKql66i2G0H85xa0so/edit?usp=sharing)
Mostly explained how the library [Django Rest Framwork](http://django-rest-framework.org/) 

- About myself
  - I am a back-end developer working with the development team of W3Dev(www.w3dev.in) on Django API. I have worked on Tornado, Flask, Django and React. I am a 3rd-year student at Bharati Vidyapeeth's College of Engineering, New Delhi (IPU) and want to contribute to the community and meet as many cool people as I can. I know how to code in Python, JS, HTML, CSS, C, C++, Java, SQL. and constantly learn tech that interests me.

**Comment by Gouravchawla** [comment]
Hi. Are you available to deliver the talk on 1st September meetup?
Reply ASAP(preferably by EOD today).

Location: E2E Newtworks Limited
24, Awfis, A, 9, Mathura Rd, Mohan Cooperative Industrial Estate, · Delhi

**Comment by GauravJain98** [comment]
Yes I am

**Comment by GauravJain98** [comment]
I will link everything here

**Comment by GauravJain98** [comment]
Added the slides

**Comment by akshayaurora** [comment]
Delivered on 1st Sept 2018 @ E2ENetworks
