### ISSUE TITLE
Proposal: django on day 500

### ISSUE THREAD

**Issue by dusual** [pydelhi/talks#119]
All web developers who use python have come across django. It is both hated and loved to varying degrees. But what about day 500. What happens when you have a team of 15 people developing and 5 teams talking to the django application. What kind of baggage does django bring for day 500th. What kind of things it solves for the day 500.

Some of the points we shall talk about?

What kind questions does the day 500 bring?
Admin. Your friend and your foe.
Managing your database changes
Configuration Management
Django in a muti-skill, multi-team environment.
Django in a distributed environment.
Building visibility in your django app.

**Comment by Gouravchawla** [comment]
Hi. We are confirming your talk and updating on our schedule. Please, let us know if there are any updates from your side. And it would be helpful if you could update the talk duration, link to slides(if any) and your bio(few lines would do) ASAP.

**Comment by akshayaurora** [comment]
@dusual could you please update this issue with your slides.

**Comment by akshayaurora** [comment]
Delivered on 1st Sept 2018 @ E2ENetworks
