### ISSUE TITLE
Workshop Proposal: Symbolic Computation with Python using SymPy

### ISSUE THREAD

**Issue by aktech** [pydelhi/talks#13]
I am proposing a workshop for PyDelhi's Upcoming Meetup. Since the workshop for 16 Jan is already taken, the day of next meetup would be great for this workshop.

**Slides:**
http://iamit.in/talks/slides/sympy-tutorial-intro.pdf

**Ipython-Notebooks:**
http://iamit.in/sympy-tutorial/tutorial_exercises.zip

**Comment by aktech** [comment]
Proposed here: https://github.com/pydelhi/workshops/issues/4

**Comment by akshayaurora** [comment]
can be closed now this was conducted last time in sarai.
