### ISSUE TITLE
Session: Deploying your Python Apps using Docker

### ISSUE THREAD

**Issue by tarunlalwani** [pydelhi/talks#14]
Session: Deploying your Python Apps using Docker
Meetup: 20th Feb

**Comment by satyaakam** [comment]
@tarlabs any links to content like slides etc...

**Comment by tarlabs** [comment]
@satyaakam, no will have to prepare the content. But something like below

http://www.slideshare.net/ATASlides/atagg2015-nitin-mukhija-n-tarun-lalwani-continuous-delivery-by-building-environment-using-docker

**Comment by satyaakam** [comment]
@tarlabs you are listed for the talk http://www.meetup.com/pydelhi/events/226049193/ prepare your slides now!!

**Comment by akshayaurora** [comment]
@tarunlalwani can you deliver your talk this upcoming meet ? 22nd July

**Comment by tarunlalwani** [comment]
Where is it going to be held?

**Comment by akshayaurora** [comment]
@tarunlalwani https://www.meetup.com/pydelhi/events/238176684/
Empowerers Coworking City, Green Park

**Comment by tarunlalwani** [comment]
Okie, I can take up the session

Regards,
Tarun Lalwani

**Comment by akshayaurora** [comment]
@tarunlalwani you have been listed on the meetup page. Best of luck for your talk.

**Comment by tarunlalwani** [comment]
Can anyone share the pics taken during my session?

Regards,
Tarun Lalwani

**Comment by rajataaron** [comment]
@CuriousLearner this talk was delivered on [22 July 2017](https://www.meetup.com/pydelhi/events/238176684/) you can close this issue now.
