### ISSUE TITLE
Proposal: Face recognition and tracking with python opencv 

### ISSUE THREAD

**Issue by vishalsangwan** [pydelhi/talks#140]
**title: opencv, python and raspberry pi**

**Topics to be covered**
Basic operations with opencv and python.
object recognition and tracking.
moving pan tilt servo motors accordingly.

link to demo-https://photos.app.goo.gl/A71d6fex2SdX777j9
i have added some more fun things in the project, which are not shown in demo.

for any comments or queries- 8950888797,vishalsangwan10@gmail.com

**Comment by aaqaishtyaq** [comment]
Hi @vishalsangwan.
I'm confirming your talk/workshop for ```29th Sept 2018```.
Let me know if you have requirements from our side :)

**Comment by vishalsangwan** [comment]
Hello,

I have shared the link on both the telegram channel and in the comments of
meetup page.

Regards
Vishal sangwan

**Comment by vishalsangwan** [comment]
https://github.com/vishalsangwan/Opencv-object-recognition-and-tracking.git

**Comment by aaqaishtyaq** [comment]
Thank you for the talk.
