### ISSUE TITLE
Proposal: REST in peace with hug

### ISSUE THREAD

**Issue by ttanay** [pydelhi/talks#145]
- **Title**: REST in peace with Hug

- **Brief description about the content to be covered**:
        hug is a framework that aims to make developing Python driven APIs as simple as possible, but no 
        simpler. As a result, it drastically simplifies Python API development.

- **Time required for the talk**: 20 mins

- About yourself (Please include social media links, twitter, facebook):
       LinkedIn: https://www.linkedin.com/in/ttanay/

**Comment by aaqaishtyaq** [comment]
Hi @ttanay 
Are you available to deliver the talk on Nov 24?

**Comment by ttanay** [comment]
Yes. Also, can I host you at SocialCops HQ?

**Comment by rajataaron** [comment]
@ttanay That would be really helpful if you can help us with venue.

**Comment by rajataaron** [comment]
@ttanay please initiate the process and share your email id with me so i can send formal mail to Social Cop

**Comment by ttanay** [comment]
@rajataaron My email is tanay.t@socialcops.com.

**Comment by rajataaron** [comment]
Hi @ttanay sent you the mail please revert whenever you got time.

**Comment by ttanay** [comment]
@rajataaron Great! I talked with the team here as well. So, PyDelhi at SocialCops on 24th Nov!

**Comment by rajataaron** [comment]
Thanks, @ttanay for your help. See you soon.
