### ISSUE TITLE
Proposal: Talk-workshop : Getting started with web-scraping in python

### ISSUE THREAD

**Issue by Thedijje** [pydelhi/talks#149]
>Note : This is going to be my first talk, and i am beginner in python itself so just giving talk on what i am learning I could write a blog on it as well, but since many attendees are new and college student, this talk might help them getting into python and see its beauty at a very early stage.

# web-scraping

Web-scraping is one of commonly used utility of python and are being used in various ways and for various purpose.
Web-scraping involved getting content of web page through given URL and digging out data what we need or decided to get from. 
Unlike small stuff, web-scraping is used for huge automated collection of data, which can be stored in file/database or just view like we will be doing.

# What this talk will be consist of

- Basic python3 and pip installation
- Understanding and using pip3
- Using pip to install packages and using them in web-scraping.
- Analysing web page before scraping and understanging legal boundries of it.

# Writing script/code for web-scraping

We will go ahead after all setup and do simple scraping where we will try to extract meaningful data from given web page.
We will be using simple statements, operators and functions in Python while doing so.

Anyone new to python will definatly going to use this and going to love this.

> If title of the talk suits the meetup standard, please let me know so i can go ahead and create full planning on it.

**Comment by Aishwarey** [comment]
Will you be available on 24th november for the talk?

**Comment by Thedijje** [comment]
Yes ofcourse i will be, should I start working on it.

**Comment by Aishwarey** [comment]
Yes @thedijje

**Comment by aaqaishtyaq** [comment]
Hi @Thedijje, Thank you for your talk.
