### ISSUE TITLE
Proposal: Using Python for `Design Elements`.

### ISSUE THREAD

**Issue by aniketmaithani** [pydelhi/talks#15]
Generally we think Python as a tool to accomplish certain geeky task. But during this crisp talk I'll lay focus on how we are using Python to generate Fractal Patterns and Automating design related task.

**Comment by theskumar** [comment]
This talks is already delivered. 

@aniketmaithani please add your slides to the Readme.md and with other details and then we can close this up. Thanks.

**Comment by aniketmaithani** [comment]
https://docs.google.com/presentation/d/1Z06eZiux55FPdTbTRaCvtZPLSqh8y1sMi3ztKfcmIBY/edit?usp=sharing @theskumar

**Comment by theskumar** [comment]
Wanna send PR?
