### ISSUE TITLE
How to build  a real mobile app in kivy

### ISSUE THREAD

**Issue by AliSattarBarani** [pydelhi/talks#150]
<description>

**Comment by aaqaishtyaq** [comment]
Hi @AliSattarBarani,
Are you available to give the talk on Nov 24th [meetup](https://www.meetup.com/pydelhi/events/tcpblqyxpbgc/)

**Comment by im-gozmit** [comment]
Hi @AliSattarBarani , kindly update the description of the issue.
Whether you want to take a session or you want to learn this?
If you want to deliver the talk, please update the rest of the details.

**Comment by akshayaurora** [comment]
Closed due to lack of details.
