### ISSUE TITLE
PROPOSAL: HandsOnWorkshop - Google Protocol Buffers in Flask

### ISSUE THREAD

**Issue by shreybatra** [pydelhi/talks#151]
# Google Protocol Buffers in Flask (Handson)

## Description -
Intro to Protobuf basics and how to use them in Python (in flask).

## Pre Requisites -
Only knowledge of basic python and Flask (not necessarily)

## Time required - 
HandsOn Session, Full time track on devsprint?

## About myself
Currently a final year CSE student at JIIT. Working in full stack open source and data science. Links
LinkedIn - https://www.linkedin.com/in/shreybatra/
Github - https://github.com/shreybatra
Facebook - https://www.facebook.com/shrey.batra.1232

**Comment by akshayaurora** [comment]
@shreybatra would you be available to take this workshop on 16th June in Drupal camp for the slot given to PyDelhi?
