### ISSUE TITLE
Create serverless SMS gateway using microservice

### ISSUE THREAD

**Issue by Thedijje** [pydelhi/talks#152]
# Create serverless microservice SMS gateway using lambda + Python

We will be using AWS architecture to create serverless microservices for sending SMS from Web.
We will be covering following topics in it
- AWS basic introduction
- Basic introduction of microservices
- IAM users and permissions
- API gateway
- Lambda function
- Using AWS SDK in python using Lambda function

## Prerequisites & reading material
- Basic usage of Postman
- AWS account for everyone, no need to have server on it, we'll go serverless
- Basic HTTP protocal and REST knowledge

##  Time required for the Devsprint
Nearly 3 Hour

## Link to slides / demos
[to be created]

## About Me
Me and Shivani both are backend developer, works with PHP and AWS along with relational database, REST.
Learning python and exploring anything that i can find.

Dheeraj jha [ twitter.com/@thedijje ]
Shivani Sehdev [ twitter.com/@shivanisehdev86 ]

## Availability
8 Dec 2018

**Comment by aaqaishtyaq** [comment]
@Thedijje Thank you for your talk.
