### ISSUE TITLE
TALK PROPOSAL: Become a Pro user of PyCharm or any other Jet Brains IDEs

### ISSUE THREAD

**Issue by ckalpit** [pydelhi/talks#153]
- Become a Pro user of PyCharm or any other Jet Brains IDEs

To share with you the things that I am using to boost my productivity in PyCharm, keep in mind that most of those will work across any Jet Brains IDEs.

1. Introduction to PyCharm
2. Basic shortcuts which is helpfull in daily usage
3. Shortcuts that'll help while coding and reduce mouse usage
4. Lesser known PyCharm's functionalities
5. Advance usage of PyCharm by using Live Templates, Macros 

- Prerequisites & reading material (Distributed before the session) 
NA

- Time required for the talk
Nearly 30-40 min

- Link to blog
[Become a Pro user of PyCharm or any other Jet Brains IDEs](https://medium.com/@ckalpit/become-a-pro-user-of-pycharm-or-any-other-intellij-ides-part-1-1827c556d6fa)

- About Me
Software Alchemist(Lead Developer) @91mobiles, previously @pricebaba.com, having experience in native android, python, react, react native, opensource lover, was a member of GDG baroda and google facilitator

- Links
[linkedin.com/in/ckalpit](https://www.linkedin.com/in/ckalpit)
[twitter.com/ckalpit](https://twitter.com/ckalpit)
[github.com/ckalpit](https://github.com/ckalpit)

- Availability
8 Dec 2018

**Comment by im-gozmit** [comment]
Hey @ckalpit , Thanks for proposing your talk.
Actually, we had a DevSprint on 08 December, not a talk meetup so are you available to deliver your talk on 22nd December?
