### ISSUE TITLE
Proposal:  Securing your Django and Flask APIs with JWT

### ISSUE THREAD

**Issue by shahbaz17** [pydelhi/talks#155]
**Talk Description**
The APIs keeps changing and the frameworks like Django and Flask are shifting the paradigm of API consumption. We often dedicate a lot of time in crafting powerful APIs but overlook proper security measures. Setting up an authentication layer is, without a doubt, one of the most challenging yet necessary tasks within any web application. Not only does the application in question always needs to ensure the most basic functionality is set up by default (such as login, log out, reset password), but additionally, it’s required to develop all the libraries to handle the validation of the credentials, the connections to the database responsible for the user data, session management, and general security.

In this talk, we’ll look at proper ways to secure our Django and Flask APIs with JSON Web Tokens. We’ll go from learning what JSON Web Tokens are, why they’re the driving force in API security, and to put theory into practice we will actually build a real-world implementation using Django and Flask where we’ll show common best practices. It will not only improve the quality of the code but also help you adopt new measures of writing a secure APIs.

- Time: 30 min

- About: https://about.me/mdsbzalam

- Availability: **22 Dec 2018**

- Slide: https://slides.com/mdsbzalam/pyconid18/ ( Will make a similar slide for this talk )

I live in **Ranchi, Jharkhand** and will be in Delhi **between 21-24 Dec**. So, looking forward to presenting this topic.

Please let me know

Thank you.

**Comment by rajataaron** [comment]
Hi @shahbaz17 ,
Now when you will be available again in Delhi. Please let us know so we can schedule your talk accordingly.

Thanks,
