### ISSUE TITLE
Proposal : What Actually is Machine Learning & How to Get Started ?

### ISSUE THREAD

**Issue by ayonroy2000** [pydelhi/talks#158]
- What Actually is Machine Learning & How to get started?

- In this talk, the attendees will be made to : 

1. Understand what actually is machine learning, where machine learning is used and how it is used.
2. Understand which tools are being used for applying machine learning in a day to day life application. 
3. They will get to know the advancements that are currently undergoing in the domain of Machine Learning and the huge scope that lies under the table in this domain so that they can start boosting their skills to explore this domain in the coming future and become pioneers in Machine Learning. 
4. Introduce to some of the awesome initiatives like 100 Days Of ML etc. that they can take to keep themselves motivated while doing Machine Learning.
5. Small session on Computer Vision basics over images, so that they can get motivated to start as Images speak a thousand words.

- No Prerequisites. Bring eagerness to learn & explore new stuff!! 

- 40 to 50 Minutes 

- Slides to be crafted once the proposal is accepted.

- I am currently a second-year student of Bachelor of Technology ( Computer Science & Engineering ) at GGSIPU. I am a machine learning enthusiast, driven by data & curiosity. I have hands-on experience in solving real-life problems using statistical analysis, machine learning and data visualization. A few things that I love to do are: Helping beginners getting started with Machine Learning, Make interesting projects, Write articles and tutorials, Pursue research projects etc.
Know more about me at https://ayonroy.me/
Connect with me over LinkedIn at https://www.linkedin.com/in/ayonroy2000/

- 16th February 2019 

- Looking forward to delivering my first talk, quite excited !!

**Comment by ayonroy2000** [comment]
Updated the timings, and agenda of the talk !!

**Comment by im-gozmit** [comment]
Thanks for proposing your talk.
Are you available to deliver your talk on 16th February? 
Venue : Grofers Gurugram

**Comment by ayonroy2000** [comment]
Yes , I will be available to deliver my talk on 16th of February , 2019 at Grofers, Gurugram !! Looking forward for a worth learning experience !!

**Comment by realslimshanky** [comment]
Thanks @ayonroy2000, please share your contact detail on abc@shanky.xyz or on telegram using 'realslimshanky' username.

**Comment by aditya1501** [comment]
I am in second year pursuing btech in case and I have no idea what is machine learning.@aynoroy. is there any prebooking for talk or registration online

**Comment by ayonroy2000** [comment]
Would be very happy to have you as an attendee at the PyDelhi Meetup . For registration , RSVP at https://www.meetup.com/pydelhi/events/258753170/ .

**Comment by rajataaron** [comment]
This talk is delivered on 16th Feb meetup.
