### ISSUE TITLE
ML Under the hood

### ISSUE THREAD

**Issue by brute4s99** [pydelhi/talks#159]
- Title
  ML-Under The Hood
- Brief description about the content to be covered
  an explanation of how machine learning is implemented, focusing on the Mathematics behind.
- Prerequisites & reading material (Distributed before the session) 
  to be uploaded by today
- Time required for the talk
  50 minutes
- Link to slides / demos
  to be uploaded
- About yourself (Please include social media links, twitter, facebook)
  Piyush Aggarwal
- Availability (When would you be able to give the talk?) 
  16 Feb 2018
- Any comments

**Comment by rajataaron** [comment]
Hi @brute4s99, Thanks for creating your proposal for a talk. As per your availability, we are putting you on the schedule.

**Comment by rajataaron** [comment]
This talk was delivered on 16th Feb meetup at Grofers.
