### ISSUE TITLE
Proposal: Demystifying Python MRO 

### ISSUE THREAD

**Issue by aktech** [pydelhi/talks#16]
Hi! I am proposing a talk for PyDelhi Meetup on Demystifying Python MRO, on 2nd April 2016.

**Update:**
Slides: http://slides.com/aktech/python-mro/#/

**Comment by akshayaurora** [comment]
slides, content?

**Comment by aktech** [comment]
The slides are not ready yet. This talk proposal is for the next meetup after the meetup on 19th.

**Comment by aktech** [comment]
Status: Delivered
