### ISSUE TITLE
Proposal: Wikidata - Largest Crowd sources Knowledge Graph

### ISSUE THREAD

**Issue by karx** [pydelhi/talks#160]
### Title
Wikidata - Largest Crowd sources Knowledge Graph

### Brief description about the content to be covered
There is huge pool of clean, categorized, context-rich data on the web, any ML engineer's dream

* We will first discuss what is an Knowledge Base/Knowledge Graph
* Technology used/basic underlying components
* Introduction to Wikidata - A Data repository 
* SPARQL - A query language for the Semantic web
* Running few live queries on Wikidata

### Prerequisites & reading material (Distributed before the session) 
* Basic knowledge about diffrent data storage techniques.
* Knowlege about No-SQL databases would help.
* Any experince in query languages like SQL

### Time required for the talk
30-45 mins - Talk format

### Link to slides / demos
Github page for [Wikidata - Largest Crowd sources Knowledge Graph - by karx](https://karx.github.io/Wikidata/)

### Platforms that you may use
* Browser
* Wikidata

### Measure Success(How will you measure the Success of your talk?)
* Commits/Contributions by Attendees to Wikimedia Foundations
* Queries created by Attendees  

### About yourself
Kartik Arora, is a developer turned Entrepreneur, founder [Akriya Technologies](https://akriya.co.in)
Also,
* Developer Advocate at [Wendor](https://wendor.in)
* Resident Hacker at [India Open Data Association](https://indiaopendata.com)

Social profiles:
* [Facebook](https://www.facebook.com/karx01)
* [Twitter @karx_brb](https://twitter.com/karx_brb)
* [Linkedin](https://www.linkedin.com/in/karx01/)
* [Github karx](https://github.com/karx)

### Availability
Available in NCR in Febuary 2019

**Comment by akshayaurora** [comment]
@karx would you be available to give a talk on the community slot @Drupal Camp, in JNU Convention centre representing PyDlehi Community ? The event a open source event, does not charge anything from attendees.  PyDelhi along with other communities like ILUG-D, Blockchain Devs & Distributed systems  & others get's slots in this event. 

Date: 15th June time would be between 11 am to 5 pm.

**Comment by karx** [comment]
@akshayaurora 
That sound like an amazing opportunity to talk about Wikidata! 
Would love to be there and represent PyDelhi Community.

**Comment by akshayaurora** [comment]
@karx the date fo the slot given to PyDelhi is on 16th June hope that is ok for you.

**Comment by akshayaurora** [comment]
@karx if you can forward me the timing for the talk to be put up on the schedule that would help a lot.

**Comment by karx** [comment]
@akshayaurora 16th June works!
Timing for the talk? Do you mean which part of the day we schedule it? Let me know how I can help

**Comment by akshayaurora** [comment]
@karx would you need 40 minutes ,  more or less slots in the event for a talk are usually 40 minutes
would be great if you could adjust your talk t be delivered in that period.

**Comment by akshayaurora** [comment]
This was delivered on 16th June

**Comment by karx** [comment]
Thanks, It was amazing being part of the **Drupal Camp 2019** in **JNU**. 

Here are the link to the slides: [Slides](https://slides.com/kaaro/wikidata#/)
and the Wikidata one-pager with useful links: [One-pager](https://karx.github.io/Wikidata/)


Hoping to improve on the same and talk more about Wikidata.
