### ISSUE TITLE
Proposal : An Introduction To Computer Vision

### ISSUE THREAD

**Issue by iAyon** [pydelhi/talks#164]
-  An Introduction to Computer Vision

- In this talk, the attendees will  :

1 ) Get an introduction to Computer Vision & how it is being used in our daily lives.
2 ) Understand which tools are being currently used for applying computer vision in a day to day life applications.
3 ) Get knowledge about what actually happens while we execute our very basic codes to implement Computer Vision .
4 ) Build some simple & awesome Python scripts to get hands-on experience with Computer Vision.

- Basic Knowledge of Python & library like Numpy. Come with OpenCV library of Python already loaded in your machine.

- 1 Hour

- Slides to be crafted once the proposal is accepted.

- I am currently a second-year student of Bachelor of Technology ( Computer Science & Engineering ) at GGSIPU. I am a machine learning enthusiast, driven by data & curiosity. I have hands-on experience in solving real-life problems using statistical analysis, machine learning and data visualization. A few things that I love to do are: Helping beginners getting started with Machine Learning, Make interesting projects, Write articles and tutorials, Pursue research projects etc.
Know more about me at https://ayonroy.tech/
Connect with me over LinkedIn at https://www.linkedin.com/in/ayonroy2000/

- The Next Meetup  ( In September or October )

**Comment by ayonroy2000** [comment]
@vipulgupta2048 any updates bhaiya ?

**Comment by vipulgupta2048** [comment]
Hey @ayonroy2000, as and when the next meetup happens the talks team will get back to you ASAP. Thanks,

**Comment by ayonroy2000** [comment]
Hey @vipulgupta2048 , I would be available for a talk in September or October, though this time Mayank contacted me, but I being in Bangalore till 31/8/2019, I can't deliver the talk.
