### ISSUE TITLE
Optimising APIs for consumer with GraphQL

### ISSUE THREAD

**Issue by Thedijje** [pydelhi/talks#165]
# Optimising APIs for the consumer with GraphQL

GraphQL is a very efficient way of communication with the server with the client-first approach. Backend won't have to design and provide structure/URLs for the data they need. Now Front-end can make costume queries and keep their requirement fit as exact, none less, not more.

## Prerequisites & reading material
Basic knowledge of Rest APIs and working with APIs should be fine or reading is recommended. Since its not hands-on session excitement for the talk is fine.

## Time required for the talk
30-45 Minute

## Link to slides/demos
yet to prepare

## About Me
I am a Backend developer and loves to work on APIs, from SOAP to Rest and now graphQL is going amazing. I work with AWS, Python, Laravel, Codeigniter, and scaling of application.

## Your open source contributions
please visit @thedijje and @seekgeeks for the list of contribution

## Availability
After 14 april

**Comment by progmatic-99** [comment]
Thanks for proposing this talk.
Will you be able to give this talk on **12th September** on our upcoming meetup which includes all the local Python chapters of India coming forward to give a boost to PyCon India??
