### ISSUE TITLE
Automating Computer Vision to detect any Object

### ISSUE THREAD

**Issue by harshalofic** [pydelhi/talks#169]

**Comment by harshalofic** [comment]
Talk has been postponed :D

**Comment by realslimshanky** [comment]
@harshalofic can you please update the description with the details about what you would like to deliver?

**Comment by ShambhaviCodes** [comment]
@harshalofic, Would you like to deliver your talk in the upcoming PyDelhi meet-up scheduled on 2nd November?

**Comment by harshalofic** [comment]
Yeah I'm fine with that :)

**Comment by ShambhaviCodes** [comment]
Great! Can we discuss the agenda for the talk over e-mail?

**Comment by harshalofic** [comment]
Yes, we can.
