### ISSUE TITLE
Proposal: Getting started with PySpark

### ISSUE THREAD

**Issue by shagunsodhani** [pydelhi/talks#17]
Hi! I would like to propose a talk about how to get started with PySpark. PySpark is the Python binding for [Spark](http://spark.apache.org/). It is the same spark which claims to run 100X faster than Hadoop for in-memory computations. I will focus on what Spark is all about and the different ways it can be used with Python - scripts/shell/IPython.

**Comment by akshayaurora** [comment]
Seems like a good talk. Can you add some bio about yourself and some slides for the talk.

**Comment by shagunsodhani** [comment]
Hey @akshayaurora. I am Shagun Sodhani. I graduated in Computer Science from IIT Roorkee in 2015. Since then I have been working with Adobe Analytics. I have been using Spark for past 6 months (primarily using Scala) and recently have started using PySpark as well. 

For the slide, give me some time. I would be using an IPython notebook most probably.

**Comment by shagunsodhani** [comment]
hey @akshayaurora So can I do it in the next meetup?

**Comment by akshayaurora** [comment]
slides?

**Comment by shagunsodhani** [comment]
https://github.com/shagunsodhani/talks/blob/master/spark/PySpark.ipynb

This covers the rdd part for PySpark. Would add another part for SparkSQL and slides will only cover Spark as a system and not how to use it. I will make them available by this weekend. The talk is next saturday right?

Please let me know your feedback.

**Comment by shagunsodhani** [comment]
@akshayaurora [This](https://github.com/shagunsodhani/talks/blob/master/spark/PySpark.ipynb) is the completed IPython notebook for the talk. I will attach the placeholder slides by Sunday.

**Comment by shagunsodhani** [comment]
@akshayaurora [This](http://slides.com/shagunsodhani/deck#/) is the link to the deck.

**Comment by akshayaurora** [comment]
+1 for having this talk on 19th, please confirm that you are available and will be coming to the venue

**Comment by shagunsodhani** [comment]
@akshayaurora works for me. What is the venue?

**Comment by akshayaurora** [comment]
http://www.meetup.com/pydelhi/events/226049222/ let me know if the time is more than you need or less.

**Comment by shagunsodhani** [comment]
1 hour is sufficient :+1:

**Comment by aktech** [comment]
Status: Delivered
