### ISSUE TITLE
Proposal: [Talk] How to track your Machine Learning Experiments Effectively

### ISSUE THREAD

**Issue by init27** [pydelhi/talks#170]
<description>
The usual pipeline for working on a machine learning experiment is very different from Software Engineering. This talk will be highlights of Tracking the experiments and the iterative nature of the same effectively inside of a jupyter notebook, how to effectively apply these ideas to Kaggle competitions and make these work with data science teams. 

Pre-Requisite:

- Familiarity with Python 
- Familiarity with Jupyter notebook
- Some Experience with Building Machine Learning models.

Content URL: I'm happy to record and upload a quick screencast if that is required along with the Jupyter notebooks.

Speaker info: 
Sanyam is a Machine Learning and Computer Vision practitioner, recognized by media such as inc42 or Economic Times. Sanyam is a Kaggle Triple Expert (ranked top 1% in all categories), He is also an active blogger on Medium, which recognizes him as a "Top Writer in Artificial Intelligence".

Sanyam has done various research and industrial internships based on Deep Learning applications at the Indian Institute of Technology Madras, the Indian Institute of Technology Roorkee, ONGC, and Tech-Mahindra. He has a background in Computer Science and is an active contributor to multiple Machine Learning communities: Fastai, TWIMLAI, DS India, AISaturdays, and Kaggle-Noobs.

**Comment by realslimshanky** [comment]
Thanks @init27 for submitting your talk idea, we'll get back to you soon.

**Comment by init27** [comment]
Thanks @realslimshanky 
I'm adding a few details below, I believe these would be helpful for you to review the CFP:

Here is the rough Outline for my Talk:

10 minutes: Introduction to the problem: Why is Tracking ML Experiments difficult?
Definition, the workflow of the ML Experiment
Iterative Nature of the Problem?
Why GitHub is not good enough? ex: Tracking Datasets, 100 models, etc.

10 minutes: Ways to Track experiments:

Spreadsheets
Heavily Annotated Jupyter notebooks
Slack
Jovian (Free + Open Source), tool for Jupyter
5 minutes:

Best Practises for Kaggle
Best Practises for a collaborative Experiment
Things to avoid
5 minutes: Q&A

Drafts of Slides: [These give an overview, the gist of the talk. I'm happy to iterate further or add any changes if suggested](https://docs.google.com/presentation/d/1E6tdAoUQPMZVmC4zt-2FyJ5-Lud4eayW864_seyqiGU/edit?usp=sharing)

**Comment by akshayaurora** [comment]
@init27 would you be available on 15th September to give your talk,  Venue is Microsoft Gurgaon Premises.

**Comment by init27** [comment]
@akshayaurora Thanks, unfortunately, I'm already speaking at an event in Bangalore on the 15th. I'll be available to speak on any event after 16th Sept.

**Comment by ShambhaviCodes** [comment]
@init27 Would you like to deliver your talk in the upcoming PyDelhi meet-up scheduled on 2nd November?
