### ISSUE TITLE
Introduction to Distributed Caching, Explained with Redis!

### ISSUE THREAD

**Issue by Thedijje** [pydelhi/talks#171]
### Introduction
While scaling the system horizontally or vertically, the implementation of caching is very important, and for the system which is distributed globally, caching should be distributed for the performing at its best level. Example Youtube might have distributed audience and each geographical location required content to be cached and should be geographically be decided.  

### Prerequisites & reading material (Distributed before the session) 
Basics about system design, scaling, caching 

### Time required for the talk
30 minutes

### Link to slides / demos
Yet to be prepared

### About yourself (Please include social media links, twitter, facebook)
I am Dheeraj Jha, Sr software developer at CTE International private limited, I work on PHP based backend, work with Codeigniter, Laravel, AWS, and system architecture design.
twitter.com/thedijje
stackoverflow.com/cv/thedijje

### Your open-source contributions (if any)
seekgeeks/cssjsminify
github.com/thedijje/

### Availability (When would you be able to give the talk?) 
As per requirement

### Any comments
N/A

**Comment by realslimshanky** [comment]
@Thedijje thanks for submitting you talk idea, we'll get back to you soon.

**Comment by akshayaurora** [comment]
@Thedijje would you be available on 14th September to give this talk? Venue is Microsoft Gurgaon Premises.

**Comment by Thedijje** [comment]
Hello @akshayaurora 
I have already delivered this talk on 10th Aug meetup. If everyone is fine, i would love to deliver it again.  But i am not available this weekend as i am out of town.
Would surely try next time.
