### ISSUE TITLE
Proposal: The Zen of Python with examples.

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/talks#172]
We have all read the eloquent poem by Tim Peters.
This talks aims to understand what the poet meant by each phrase with the help of practical examples.

**Comment by realslimshanky** [comment]
Thanks @bhanuvrat for submitting the talk idea, we'll get back to you soon.

**Comment by ShambhaviCodes** [comment]
@bhanuvrat, Would you like to deliver your talk in the upcoming PyDelhi meet-up scheduled on 2nd November?
