### ISSUE TITLE
Proposal: Talk on Django 

### ISSUE THREAD

**Issue by mehul08** [pydelhi/talks#173]
Hello Everyone,  

I would like to propose a talk on developing websites with Django.

The purpose of the talk will be to give a brief introduction to writing apps in Django. From the basics to setting up databases to deployment.

 The duration of the talk can be 2 hours or whatever duration the audience and the speaker feel comfortable with.

If people are interested, a talk can be organised and it should be given by a person who is an advanced Django developer.

About me:
I am a basic front-end developer. Now I've started my server-side journey with Python. I'm interested in getting deep into Django. Hence, my proposal for a talk on the same.

Thanks and Regards,
Mehul

**Comment by realslimshanky** [comment]
Thanks @mehul08 for submitting the idea for your talk. We'll get back to you soon.

**Comment by ShambhaviCodes** [comment]
@mehul08, Would you like to deliver your talk in the upcoming PyDelhi meet-up scheduled on 2nd November?

**Comment by progmatic-99** [comment]
@mehul08 Thanks for proposing the talk. Would you like to deliver this talk in an offline meetup??
Please comment your telegram ID so that we can add you to the PyDelhi group.
