### ISSUE TITLE
Proposal: Workflow Management using Apache Airflow

### ISSUE THREAD

**Issue by imnobody0396** [pydelhi/talks#174]
In this big data era, loads of long-running data processing workflows are run my almost every tech company. These workflows are basically DAGs which consists of tasks depending on completion of one or more task. These tasks process data in batches and thus needs to be managed, monitored and scheduled properly.

Apache Airflow is a widely used solution for such a job as it is open-source and has great community support. This Workflow Management System is written in Python and was originally developed by Airbnb Team and is also used by major tech giants like Uber, Lyft, etc.

My talk can include setting up a distributed dockerized airflow cluster followed by some key airflow concepts and an example workflow run.

**Comment by realslimshanky** [comment]
Thanks @imnobody0396 for submitting the talk idea. We'll get back to you soon.

**Comment by akshayaurora** [comment]
@imnobody0396 would you be available to deliver your talk on 14th Sept. Microsoft Gurgaon Premises.

**Comment by ShambhaviCodes** [comment]
@imnobody0396, Would you like to deliver your talk in the upcoming PyDelhi meet-up scheduled on 2nd November?
