### ISSUE TITLE
Proposal: Exploring Concurrency with Asyncio

### ISSUE THREAD

**Issue by Pradhvan** [pydelhi/talks#175]
- Title: Python's tale of Concurrency 

- Brief description of the content to be covered: The talk will look into to general concept of concurrency. How it's handled with Python's with asyncio module. 

- Basic Outline: 

1. Introduction
2. Concurrency 
3. Concurrency vs Prallesim 
4. How Python handles concurrency? 
3. Threading and it's limitations.
4. Asyncio
5. Async for the web 
 
- The time required for the talk: 30 min

- Link to slides/demos: [Python's tale of Concurrency](https://docs.google.com/presentation/d/1nnVNIIEiuf9HjZlC5J2jdF2lbbID2WQgDOlG4VKezFE/edit?usp=sharing)

**Comment by ShambhaviCodes** [comment]
Would you like to deliver your talk in the upcoming PyDelhi meet-up scheduled on 2nd November?

**Comment by Pradhvan** [comment]
@ShambhaviCodes sure, count me in :smile:

**Comment by ShambhaviCodes** [comment]
Great! Can you please share your e-mail address?

**Comment by Pradhvan** [comment]
```pradhvanbisht@gmail.com```
