### ISSUE TITLE
Proposal: AI for Good 

### ISSUE THREAD

**Issue by Utkarshkulshrestha** [pydelhi/talks#176]
I want to propose a talk on developing application or using AI/ML for  betterment of society /community we are living in .

**Comment by ShambhaviCodes** [comment]
Hello, 
Would you like to present your talk on 9th November Meet-up?

**Comment by Utkarshkulshrestha** [comment]
yes I would love to

**Comment by rajataaron** [comment]
@Utkarshkulshrestha did you proposed the talk? We are looking for a speaker for upcoming meetup for AI/ML related topics.
