### ISSUE TITLE
Proposal: The Magic of Python AST

### ISSUE THREAD

**Issue by Sc0rpi0n101** [pydelhi/talks#177]
# The Magic of Python AST: Understanding your code using AST

### Brief description about the content to be covered

An abstract syntax tree (AST), or just syntax tree, is a tree representation of the abstract syntactic structure of source code written in a programming language. The ast module helps Python applications to process trees of the Python abstract syntax grammar and provides us with the capability to inspect and modify Python code.

### Prerequisites & reading material (Distributed before the session) 

Basic knowledge of syntax trees and python.
Some documentation for the python AST module:
https://docs.python.org/3/library/ast.html
https://greentreesnakes.readthedocs.io/en/latest/

### Availability (When would you be able to give the talk?) 

9th November 2019

**Comment by akshayaurora** [comment]
@Sc0rpi0n101 would you be interested in giving this talk on the upcoming meetup on 25th Jan @ Gojek gurgaon?

**Comment by Sc0rpi0n101** [comment]
Sorry, that won't be possible. I have classes on 25th.

**Comment by progmatic-99** [comment]
Thank for proposing this talk. Would you like to take this talk in the upcoming virtual meetup?

**Comment by Sc0rpi0n101** [comment]
When is the meetup?
