### ISSUE TITLE
Talk proposal - SOLID design principles

### ISSUE THREAD

**Issue by Ankush-Chander** [pydelhi/talks#178]
- Title
SOLID design principles
 
- Brief description about the content to be covered
S.O.L.I.D is an acronym for the first five object-oriented design(OOD)** principles** by Robert C. Martin, popularly known as Uncle Bob.
These principles, when combined together, make it easy for a programmer to develop software that is easy to maintain and extend. They also make it easy for developers to avoid code smells, easily refactor code, and are also a part of the agile or adaptive software development.

- Prerequisites & reading material (Distributed before the session) 
Basic acquaintance with python, Object-Oriented Principles.

- The time required for the talk
1 hr
- Link to slides/demos
https://github.com/Ankush-Chander/Tech-Talks/blob/master/SOLID.ipynb

- About yourself (Please include social media links, twitter, facebook)
Books, basketball, code, life. 
https://twitter.com/AnkushChander
https://www.linkedin.com/in/ankush-chander-8248a876/

- Availability (When would you be able to give the talk?) 
Next meetup.

- Any comments

**Comment by progmatic-99** [comment]
Thanks for proposing this talk.
Are you interested in delivering this talk in a virtual meetup.
If yes, then please ping in PyDelhi telegram group(recommended) or reply here.
My telegram username is @exit07

**Comment by Ankush-Chander** [comment]
I will update the jupyter-notebook by Thursday for review.

**Comment by progmatic-99** [comment]
Have you updated the jupyter notebook ?

**Comment by Ankush-Chander** [comment]
I will update by 12:00 am tomorrow if that's fine.

**Comment by progmatic-99** [comment]
Sure, that's fine.

**Comment by Ankush-Chander** [comment]
> I will update the jupyter-notebook by Thursday for review.

HI,
I just added  the link for jupyter-notebook. 
Please review and let me know of feedback.

**Comment by progmatic-99** [comment]
There is a mistake in ```# Liskov substitution Principle(Voilation)```
`     @property`
`     def height(self):`
`         return self._width`

should be changed to:
`     @property`
`      def height(self):`
>`         return self._height`

**Comment by Ankush-Chander** [comment]
> There is a mistake in `# Liskov substitution Principle(Voilation)`
> ` @property`
> ` def height(self):`
> ` return self._width`
> 
> should be changed to:
> ` @property`
> ` def height(self):`
> 
> > `         return self._height`

Thanks for the heads up. Modified slides accordingly. along with other information.

**Comment by shadowdevcode** [comment]
Can somebody share telegram link for chat group? I wanted to be a part of it. Just watched PyDelhi video. @Ankush-Chander

**Comment by realslimshanky** [comment]
Telegram group is private and is made so to prevent bot attacks. Please share your Telegram username to me I’ll add you in. Thanks.

> On 09-May-2020, at 7:59 PM, Vijay Sehgal <notifications@github.com> wrote:
> 
> 
> Can somebody share telegram link for chat group? I wanted to be a part of it. Just watched PyDelhi video. @Ankush-Chander
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Shashank
https://shanky.dev

**Comment by shadowdevcode** [comment]
> Telegram group is private and is made so to prevent bot attacks. Please share your Telegram username to me I’ll add you in. Thanks.
> On 09-May-2020, at 7:59 PM, Vijay Sehgal ***@***.***> wrote: Can somebody share telegram link for chat group? I wanted to be a part of it. Just watched PyDelhi video. @Ankush-Chander — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> Shashank [shanky.dev](https://shanky.dev)

Hi, 

Okay, Sharing my telegram username below - 
**username:** vijaybsehgal

**Comment by shadowdevcode** [comment]
Please let me know once you add me to the group @realslimshanky
