### ISSUE TITLE
Talk Proposal: Give Python a face lift with Electron

### ISSUE THREAD

**Issue by AakashMallik** [pydelhi/talks#179]
- Title
Give Python a face lift with Electron

- Brief description about the content to be covered
My talk will cover an experimental architecture that has been used to gel Electron shell and python scripts together to work in harmony. This architecture can be used to create desktop native applications that can help the python community benefit from the mature UI ecosystems of web community.

- Prerequisites & reading material (Distributed before the session) 
**ElectronJS basics**, **Threading in python**, **JSON**.

- Time required for the talk
**35mins** tops

- Link to slides / demos
https://docs.google.com/presentation/d/1WfmGk998_vg2IknntScclJSdFZomZrs3KNJd32CpWug/edit?usp=drivesdk

- About yourself (Please include social media links, twitter, facebook)
https://www.facebook.com/humble.discipulus
https://medium.com/heuristics (https://medium.com/@aakashmallik)

- Availability (When would you be able to give the talk?) 
In any of the upcoming meetups.

- Any comments
N/A

**Comment by progmatic-99** [comment]
Thanks for proposing this talk. Are you interested in giving this talk in a virtual meetup??
Please ping in the pydelhi telegram group, if you are a member.
