### ISSUE TITLE
Talk Proposal: Audio signal feature extraction and clustering

### ISSUE THREAD

**Issue by AakashMallik** [pydelhi/talks#180]
- Title
**Audio signal feature extraction and clustering**

- Brief description about the content to be covered
The talk will cover some basic theory about audio feature extraction and making use of tensor flow to perform a clustering operation on the same. The talk will touch up deeper concepts of tensor flow graphs and how it is supposed to be visualized while writing code.

- Prerequisites & reading material (Distributed before the session)
A brief idea of machine learning and tensor flow

- Time required for the talk
**30mins**

- Link to slides / demos
I have written a heavily documented article on it, so it the talk gets approved, I'll prepare the slides in no time.
https://medium.com/heuristics/audio-signal-feature-extraction-and-clustering-935319d2225

- About yourself (Please include social media links, twitter, facebook)
A s/w engineer at Samsung.
https://medium.com/@aakashmallik
https://www.linkedin.com/in/aakash-mallik-5b8198132/

- Availability (When would you be able to give the talk?) 
upcoming meetup

- Any comments

**Comment by AakashMallik** [comment]
@rajataaron What all details would you need from my end?

**Comment by realslimshanky** [comment]
@AakashMallik Please ping on PyDelhi group on Telegram. It would be quicker to communicate with you there. @rajataaron Aakash is present on the group as @humble_D

**Comment by AakashMallik** [comment]
Name: Aakash Mallik
Working as: S/W Engineer
At: Samsung R&D, Delhi
Area of interest: IOT and ML
