### ISSUE TITLE
Concurrency 101

### ISSUE THREAD

**Issue by shashankaryan** [pydelhi/talks#181]
- Title

Concurrency 101

- Brief description of the content to be covered

The fundamental principles of implementing concurrency using Python programming.

1. Introduction to concurrency and parallelism - Concurrency vs Parallelism (5 mins)
2. When Is Concurrency Useful?
     - Use case: I/O Bound Program (Includes demo, 10 mins) 
     - Use Case: CPU Bound Process (Includes demo, 10 mins)
3. Conclusion - When to use Concurrency (5 mins)

- Prerequisites & reading material (Distributed before the session) 
      - Understanding of Python Programming.
      - Basic understanding of how GIL works.
      - Basic understanding of AsyncIO

- The time required for the talk:   40 minutes

- Link to slides / demos:   https://slides.com/shashankaryan/concurrency-101

- About yourself (Please include social media links, twitter, Facebook)
   Shashank is a Software Dev at Nykaa, working in Nykaa Display Network. 
   https://shashankaryan.tech/
   https://twitter.com/shashankaryan
   https://www.linkedin.com/in/shashankaryan

- Availability (When would you be able to give the talk?) 
  15th Feb 2020

- Any comments
References:
1. https://stackoverflow.com/questions/49005651/how-does-asyncio-actually-work/51116910#51116910
2. https://wiki.python.org/moin/GlobalInterpreterLock
3. https://docs.python.org/3/library/asyncio.html
4. https://docs.python.org/3.7/library/multiprocessing.html
5. https://docs.python.org/3.7/library/concurrency.html

**Comment by progmatic-99** [comment]
Which date would you be comfortable with, in delivering this talk?

Also, can you share your telegram username?

**Comment by progmatic-99** [comment]
Thanks for proposing this talk.

Would you like to give this talk in our upcoming virtual meetup??

**Comment by shashankaryan** [comment]
Hi @progmatic-99 

I already delivered this talk in one of the PyDelhi meetups.

https://youtu.be/-YGF7tRQhiM
