### ISSUE TITLE
Workshop Proposal: Dissecting sound - Playing with python and TensorFlow

### ISSUE THREAD

**Issue by AakashMallik** [pydelhi/talks#182]
- Title
Dissecting sound - Playing with python and TensorFlow

- Brief description about the content to be covered
We will conduct the workshop keep a dialog piece as our subject. 
1. Try to understand how a sound wave can be visualized and processed will be our first agenda.
2. We will the bring our focus into understanding some key feature extraction methods and their use cases. ( Won't be diving too deep to avoid making the workshop boring )
3. Using a few well known clustering methods to segment the audio clip at hand.

- Prerequisites & reading material (Distributed before the session) 
- Python basics
- A little understanding of what clustering is
- A brief understanding of how k-means works
- A brief understanding of tensor flow graphs 
- https://medium.com/heuristics/audio-signal-feature-extraction-and-clustering-935319d2225

- Time required for the talk
2 hrs (We'll take a few **breaks** to keep the attendees engaged as much as possible)

- Link to slides / demos
TBD

- About yourself
Aakash Mallik 
S/W engineer at Samsung

- Availability (When would you be able to give the talk?) 
**15th Dec**

- Any comments
**Participation demands the possession of laptops, so try to bring your laptops along and signup for a Kaggle account as most of the stuff will be doing will be on an online cloud kernel**

**Comment by progmatic-99** [comment]
Thanks for proposing this talk. Will you be able to deliver this talk in our upcoming virtual meetup?

**Comment by AakashMallik** [comment]
> Thanks for proposing this talk. Will you be able to deliver this talk in our upcoming virtual meetup?

I have already given the talk at pyDelhi
