### ISSUE TITLE
The Era of an Edge Device

### ISSUE THREAD

**Issue by TDBTECHNO** [pydelhi/talks#183]
- Title
Era of an Edge Device
- Brief description about the content to be covered
Technology is getting ubiquitous day by day. Now people or users want to experience technology in a low-cost device. 2 years ago, this kind of technology required a huge amount of computation like a huge GPU Memory, RAM as well as the high-resolution camera. Even most of the deep learning models couldn’t run on a low computational device. So instead of buying a huge computation system, people or users get an instance on cloud platforms like AWS, GCP, Microsoft Azure, etc. where it would cost around $150 per month approximately. But using the cloud, data breaching problem has occurred where the security of data has been compromised. Unfortunately, most of the people couldn’t afford to buy a huge computation system as well as buying a cloud instance. These problems degrade the use of A.I tools as security in normal stores, public places, schools, etc. So to enhance the use of A.I tools, there has been launched various devices such as Nvidia Jetson TX1, Nano, TX2, Xavier, Raspberry pi, etc with having a programming language binding support like python, c++, etc. by which we can deploy the deep learning model on this devices.
These devices have a decent CPU memory, GPU memory with a good resolution camera at an affordable price. These devices can be used in public places(railway stations, malls), roads, cars, stores and it doesn’t require a huge system. It is nothing but a small device or says a small CPU. The user just has to connect it with Keyboard, Mouse and an HDMI monitor.
- Prerequisites & reading material (Distributed before the session) 
Python, Deep learning, and some knowledge of embedded systems
- Time required for the talk
45-60 minutes
- Link to slides/demos
http://tdbtechno.com/projects/
- About yourself (Please include social media links, twitter, facebook)
Experienced Chief Executive Officer with a demonstrated history of working in the information technology and services industry. Skilled in Probability, Data Science, Presentation Skills, Web Design, and Data Analytics. Strong business development professional with a Bachelor of Engineering - BE focused in Computer Engineering from Savitribai Phule Pune University.

Deep knowledge and vast experience in software development, architecture and management. My company, TDB Technologies, has been at the forefront of innovative software development. We have completed hundreds of software development projects for many companies, from small start-ups to large corporations. We handle ambiguity and come-up with the right intuitive and easy-to-use solutions, taking on projects that require high skill levels and strong technical expertise.

Specialties: Computer Vision Software Applications for: Cloud computing, Mobile, Web, Desktop. Technology expertise including: Computer Vision, Video & Image Processing, Machine Learning, Object Recognition, Image Recognition, Graphics & 3D Software. 

Deepanshu Bhinda
CEO, Managing Director
TDB Technologies
Email:- ceo@tdbtechno.com
linkedIn:- https://www.linkedin.com/in/deepanshu-bhinda-09043916a/
- Availability (When would you be able to give the talk?) 
After 10th Feb 2020
- Any comments

**Comment by progmatic-99** [comment]
Would you be available in the coming days to deliver this talk in a virtual meetup?

**Comment by TDBTECHNO** [comment]
Sure, I have texted you on telegram

**Comment by satyaakam** [comment]
@progmatic-99 consider collaborating this talk with https://www.linuxdelhi.org/ and there is a hardware hackers club which predominantly works on Open hardware
