### ISSUE TITLE
Talk on concurrency in Python

### ISSUE THREAD

**Issue by Ankush-Chander** [pydelhi/talks#185]
- Title
Concurrency in Python

- Brief description about the content to be covered
Difference between concurrency and parallelism
I/O bound applications vs CPU bound applications
Global Interpreter Lock(GIL)
Process vs threads in python
Concurrency with Futures
Concurrency with Asyncio

- Prerequisites & reading material (Distributed before the session) 
Basic Python programming

- Time required for the talk
1 hour

- Link to slides / demos
Will share Jupyter notebook once confirmed.

- About yourself (Please include social media links, twitter, facebook)
books, basketball, code, life
twitter: https://twitter.com/AnkushChander
linkedIn: https://www.linkedin.com/in/ankush-chander-8248a876
building at: https://raxter.io

- Availability (When would you be able to give the talk?) 
On or after 24th May
 
- Any comments

**Comment by progmatic-99** [comment]
Thanks for proposing this talk. Would you like to take this talk in the upcoming virtual meetup?

**Comment by Ankush-Chander** [comment]
Yes, I am open to deliver this talk for 30/31st May weekend.

**Comment by Ankush-Chander** [comment]
Code of the talk can be found here: 
https://github.com/Ankush-Chander/Tech-Talks/blob/master/concurrency_python.ipynb
