### ISSUE TITLE
Talk Proposal: Cracking Text Classification SOTAs

### ISSUE THREAD

**Issue by vasudev13** [pydelhi/talks#186]
- Title: Cracking Text Classification SOTAs

- Brief description about the content to be covered

1. Starter induction to the Text Classification process. 
2. Introducing State of the Arts models such as BERT, RoBERTa.
3. Introducing and Installing huggingface transformers.
4. Demo on Google Colab with TPUs.
5. USP of talk: Getting SOTA performance on Text Classification in less than 50 lines of code with Tensorflow. (Excluding boilerplate)
7. Sharing Jupyter and link to slides.
 8. Discussing further applications, such as Multilingual Text Analysis, Textual Similarity.
9. Ending Notes.

- Prerequisites & reading material (Distributed before the session) 
I  propose to deliver a short and practical based talk without discussing many theoretical concepts and more focus on implementation. Therefore, prerequisites would be familiarity with fundamental machine learning pipeline such as feature engineering, initiating model for training, followed by prediction.

- Time required for the talk
35 mins approx.

- Link to slides / demos
Will Share soon.

- About yourself (Please include social media links, twitter, facebook) 
CSE Undergrad who loves Deep Learning. I recently got placings at ML competitions, one of which was about NLP.
github: vasudev13. 

- Availability (When would you be able to give the talk?) 
Any meetup after 31 May 2020 talk. (Preferably Virtual)

- Any comments

**Comment by progmatic-99** [comment]
Thanks for proposing this talk. When will you be available to deliver this talk?

**Comment by vasudev13** [comment]
I guess any meetup in the coming month?

**Comment by progmatic-99** [comment]
Do you have any date in mind ? If you are on the PyDelhi telegram group, please ping there.
Otherwise provide your telegram username, I will add you on the group.

Thanks

**Comment by vasudev13** [comment]
Hi, my username is vasudev13. I tried earlier to ping in Telegram but I guess I contact the wrong person.
