### ISSUE TITLE
Azure PyDay Proposal: Azure + Python = Data Analytics ♥

### ISSUE THREAD

**Issue by snehithallamraju** [pydelhi/talks#187]
**- Title**
_Azure + Python = Data Analytics ♥_

**- Brief description about the content to be covered**

_Learn how Azure and python are tightly integrated in Data engineering & Data Science scenarios. We probably cannot cover a length and depth of use cases in 30 mins but I can demo specific high level use cases on how to use Azure with python in an IoT use case, covering functionality that Azure provides with native support on Python_

_Part of the Demo will include_

_-	Data orchestration (Azure Data Factory)
o	Support for Scripting
o	Python dataricks use case
o	ETL pipelines_

_-	Spark based analytics (Data bricks)
o	Notebooks
o	Blob storage_

_-	Big Data Analytics
o	Azure Data Lake Analytics_

_-	Machine learning with Python on Azure
o	Using Python with ML Studio__

**- Time required for the talk**

30 mins

**- Link to slides / demos**

TBD

**- About yourself (Please include social media links, twitter, facebook)**

_Snehith Allamraju is a Data and Analytics Architect & Manager with 13 years of experience in Business Intelligence, Data Analytics, Data Engineering and Data Science domain. He dwells at the confluence of data, technology, strategy and community. He is a Azure certified data scientist and is an active volunteer at Tech communities in Hyderabad Python and Tableau User groups. He is Ambassador for the ODSC Hyderabad and Kaggle Days Hyderabad Chapter_

_Snehith has an Bachelors in Technology from JNTU and is an Alumni of the Indian School of Business's Management Program in Business Analytics_ 

_He can be reached out on Linked in at https://www.linkedin.com/in/snehithallamraju/ and can be followed on Twitter @watrutalkin and @HydTechEvents_

**Comment by progmatic-99** [comment]
Hi, thanks for proposing this talk. Do you have a Microsoft 365 account, as we will be using Microsoft Teams ??

**Comment by snehithallamraju** [comment]
> Hi, thanks for proposing this talk. Do you have a Microsoft 365 account, as we will be using Microsoft Teams ??

Yes I do have one.
