### ISSUE TITLE
Talk Proposal: How drastically will NLP (as computer software) change our lives in the near future?

### ISSUE THREAD

**Issue by jsxs0** [pydelhi/talks#188]
- Title
How drastically will NLP (as computer software) change our lives in the near future?

- Brief description about the content to be covered
In today's Information Age large volumes of information are available in English – whether it be information for competitive exams or general reading. However, many people whose primary language is Hindi or any other Indian language are unable to access information in English. Anusaaraka (we) aims to bridge this language barrier by allowing a user to enter an English text into Anusaaraka and read it in an Indian language of their choice.

What the audience can bring back: Machine translation convert one language to another language, learn more about it! The audience will learn more about why Anusaaraka aims to bridge a language barrier by allowing a user to enter an English text into Anusaaraka and read it in an Indian language of their choice. When any machine does that work they need big parallel corpus that can help for making some rules and disambiguate many senses, let's look into that!

- Prerequisites & reading material (Distributed before the session) 
Target audience: Intermediate (finished Python tutorial and worked on third-party libraries for web app development, data analysis, automation, etc.)

Prerequisite knowledge: Having an Operating system of POSIX compatible is a plus. Nothing too specific is a prerequisite. Interest in Python (MT- Machine translation) is obviously important. 50% (Audience has half the expertise of the presenter)

(https://code.google.com/archive/p/anusaaraka/)
(https://sourceforge.net/projects/anusaaraka/)
(https://event.ospn.jp/osc2020-online-do/session/127508)
- Time required for the talk
45 minutes to an hour

- Link to slides / demos
(I’m still working my slides)
(http://cdn.iiit.ac.in/cdn/ltrc.iiit.ac.in/downloads/nlpbook/nlp-panini.pdf)

- About yourself (Please include social media links, twitter, facebook)
Currently an Undergraduate Researcher at Anusaaraka lab - Language Translation, and NLP for Indian languages, LTRC, IIIT-Hyderabad under the supervision of Professor Vineet Chaitanya. Also the Conference (Journal) Reviewer at PyCon (Python Conferences) JP (Japan) [PyCon JP (2020) Volunteer Staff].
I've worked on (in connection with this topic):
– Implemented Word Analyzer, Local Word Grouper as a part of Standard components of MT system along with mapping using Bilingual Dictionaries.
– Successfully implemented the Word analyzer algorithm. It was designed using Sandhi, Wrong breaking of words, and grammar for Written Language. Spelling variation also occurs because Telugu does not make.
– Worked on generating the converters algorithm
[Linkedin](https://www.linkedin.com/in/jasveens/)

- Availability (When would you be able to give the talk?) 
Anytime from now

- Any comments
Anusaaraka Lab: it's one of the labs of the Language Technologies Research Centre (LTRC). LTRC is the largest academic centre of speech and language technology in South Asia, and LTRC carries out its work through four labs, which work in synergy with each other.

**Comment by progmatic-99** [comment]
Thanks for proposing this talk. When will you be available to propose this talk in our virtual meetup?

**Comment by jsxs0** [comment]
Thanks for following up. How about a week, from now?

**Comment by progmatic-99** [comment]
How about 15th August??

**Comment by jsxs0** [comment]
Sounds good. Let's finalise that (?)

**Comment by progmatic-99** [comment]
Cool. Are you in the PyDelhi telegram group?
If yes, Ping in the group once.
If you are not in the group, just provide your telegram username and i will add you.

**Comment by jsxs0** [comment]
> Are you in the PyDelhi telegram group?
No, I'm not.
Thanks @progmatic-99. Due to security concerns, I cannot share my telegram username here, so I've dropped you an email at shubh_am22@outlook.com with the same. Thanks!

**Comment by progmatic-99** [comment]
Sure. I will add you to the group and further discussions will take place there.

**Comment by progmatic-99** [comment]
@jsxs0 I haven't received your mail yet. Did you send it to the right address?
