### ISSUE TITLE
Azure PyDay talk proposal : Introduction to Azure Kubernetes Service  

### ISSUE THREAD

**Issue by ronakbanka** [pydelhi/talks#189]
- **Title**

Introduction to Azure Kubernetes Service(AKS)

- **Brief description about the content to be covered**

In this talk, the audience will walk away with Introduction to Kubernetes on Azure & how to deploy a sample Python application on AKS

- **Prerequisites & reading material (Distributed before the session)** 

This talk doesn't require any knowledge of Kubernetes, all you need is an Azure subscription, which is free to sign-up.

- **Time required for the talk**

50 minutes including Q&A

- **Link to slides/demos**

Link for slides: https://speakerdeck.com/rbanka/introduction-to-azure-kubernetes-service-aks
Link for getting started blog: https://devstack.in/2020/06/06/getting-started-with-azure-kubernetes-service-aks

- **About yourself (Please include social media links, twitter, Facebook)**

Ronak is a Sr. Solutions Architect with VMware, based out of Singapore, and has been helping organizations on their Cloud journey and DevOps practices for the last 8 yrs. He likes sharing knowledge with the community at conferences, meetups & webinars.

You can follow me on: 
Twitter: https://twitter.com/ronakbanka
Linkedin: https://www.linkedin.com/in/ronakbanka/

- **Availability (When would you be able to give the talk?)** 

I am available for any slot on 28th June.

- **Any comments**

Feel free to contact me if you have any queries on Linkedin.

**Comment by progmatic-99** [comment]
Hi, thanks for proposing this talk. Do you have a Microsoft 365 account, as we will be using Microsoft Teams ??

**Comment by progmatic-99** [comment]
Also, would 5:50 pm - 6:40pm be okay for your talk? Or, do you need another slot??

**Comment by ronakbanka** [comment]
@progmatic-99 time slots work for me.
