### ISSUE TITLE
Workshop: Apply machine learning models in Azure Functions with Python and TensorFlow

### ISSUE THREAD

**Issue by AnbuMani27** [pydelhi/talks#190]
- Title
Apply machine learning models in Azure Functions with Python and TensorFlow

- Brief description about the content to be covered

In this Workshop, you will learn how to use Python, TensorFlow, and Azure Functions with a machine learning model to classify an image based on its contents. Because you do all work locally and create no Azure resources in the cloud, there is no cost to complete this tutorial.

1. Initialize a local environment for developing Azure Functions in Python.
2. Import a custom TensorFlow machine learning model into a function app.
3. Build a serverless HTTP API for classifying an image as containing a dog or a cat.
4. Consume the API from a web app.

- Prerequisites & reading material (Distributed before the session) 

1. An Azure account with an active subscription. [Create an account for free.](https://azure.microsoft.com/en-in/free/?ref=microsoft.com&utm_source=microsoft.com&utm_medium=docs&utm_campaign=visualstudio)
2.  [Python 3.7.4.](https://www.python.org/downloads/release/python-374/) (Python 3.7.4 and Python 3.6.x are verified with Azure Functions; Python 3.8 and later versions are not yet supported.)
3. The [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#install-the-azure-functions-core-tools)
4. A code editor such as [Visual Studio Code](https://code.visualstudio.com/)

- Time required for the talk
1.30 Hours

- Link to slides / demos

- About yourself (Please include social media links, twitter, facebook)

Speaker 1: Karthikeyan VK - Microsoft MVP
Linkedin: https://www.linkedin.com/in/karthikeyanvk/

Speaker 2: Anbu Mani - Microsoft MVP
Linkedin: https://www.linkedin.com/in/anbumani27/

- Availability (When would you be able to give the talk?) 

- Any comments

**Comment by progmatic-99** [comment]
Hi, thanks for proposing this talk. Do you have a Microsoft 365 account, as we will be using Microsoft Teams for Azure PyDay ??

**Comment by AnbuMani27** [comment]
Hi Shubham,

Our M365 Mail Ids:

anbu@anbumani.dev
foxpr@hotmail.com

Thank you

________________________________

**Comment by progmatic-99** [comment]
Thanks, see you on 28th
