### ISSUE TITLE
Documenting your next Python project: Right the Docs

### ISSUE THREAD

**Issue by vipulgupta2048** [pydelhi/talks#191]
## Brief description of the content to be covered
Documenting your next Python project is a deep dive into options available as far as internal tools are considered to document your Python code. There is almost a certain confusion every time people think about what tools to use for documenting their project. In the end, it doesn't come down to how good the tool is but its more focused on what's the actual use-case is. 

In the talk, we will be going over several mechanisms for methodologies you can work with. Deployment strategies for your docs. Ways to lint and catch insensitive and inconsiderate phrasing for providing a more inclusive docs experience for all your users. We will be doing this all through well documented real-life examples that I have been working with several open-source projects and clients through Mixster. 

In the end, we will conclude and take up questions. 

## Prerequisites & reading material (Distributed before the session) 
- In this talk I talk a lot about how to document, rather the burning question has always been what to document and how to do it right and for that, I am lucky to have some great talks already such as this one by Daniele in PyCon 2017 - https://www.youtube.com/watch?v=azf6yzuJt54

## Time required for the talk
40 minutes (30 minutes + 10 for the questions) or flexible

## Link to slides/demos
https://slides.com/vipulgupta2048/writing-open-source-documentation-at-scale-that-isn-t-terrible-879091

## About yourself

Vipul Gupta is a software developer by title and documentarian by heart. He started [Mixster](https://bit.ly/whatmixster) as an initiative to help create and improve OSS docs for early-stage startups and organizations. He advocates for open-source and the cult of party parrots. Apart from his full-time commitment, he collects Calvin & Hobbes snippets, reads about human psychology, and checks his Amazon wishlist constantly to get his remote setup together. 

To know him more intimately, one can read [Man behind Mixster](https://mixstersite.wordpress.com/aboutvipulgupta2048/) or find him on [Twitter](https://twitter.com/vipulgupta2048) or [Instagram](https://www.instagram.com/vipulgupta2048_/) as [@vipulgupta2048](https://vipulgupta2048.me/)

- Availability (When would you be able to give the talk?) 
Saturday the 19th of September in the year 2020

- Any comments
Hope this goes well.

**Comment by inovizz** [comment]
@vipulgupta2048 - Is it possible to shorten it down to 30 mins?

**Comment by vipulgupta2048** [comment]
@inovizz yes, I will keep it more examples oriented. Less theory.

**Comment by inovizz** [comment]
Awesome! Thanks.

**Comment by surajwate** [comment]
Best of luck.

**Comment by vipulgupta2048** [comment]
Slides have been updated
Talk delivered here https://www.meetup.com/pydelhi/events/273073755/
Closing the issue.
