### ISSUE TITLE
Visualize your Python Code using Tkinter : Code ->App

### ISSUE THREAD

**Issue by reachudaanorg** [pydelhi/talks#192]
- Visualize your Python Code using Tkinter : Code ->App

- In this session, we will be developing a checklist desktop application using Python Tkinter, all from scratch, and hands-on. The basic functionality of the application would be - user can add and delete items as a part of the checklist, clear the checklist, and save the checklist in a txt document so that the checklist isn't lost when the app is closed and re-opened.

- There are absolutely no prerequisites to the workshop.

- 3 hours, as it will be an interactive session.

- Demo Code : https://drive.google.com/file/d/1pvlw0CFCbdkchn6w2iSQqU4QIQ95UgTZ/view?usp=sharing

- I am a final year undergrad studying IT at Ramrao Adik Institute of Technology. I have been teacking and conducting workshops for 3 years now. I can be contacted at 9326699667 (call/whatsapp) and reachudaanorg@gmail.com via mail.

- Any time is fine for me.

**Comment by progmatic-99** [comment]
Thanks for proposing the talk. 
Would you be able to deliver this on 27th March (next Saturday) in a virtual meetup??
