### ISSUE TITLE
Ethical Considerations While Building AI Systems

### ISSUE THREAD

**Issue by anjalibhavan** [pydelhi/talks#193]
- Title
Ethical Considerations While Building AI Systems
- Brief description about the content to be covered
I would like to discuss the importance of ethical data collection, analysis and development of AI systems. Especially now - amidst a pandemic, climate change and numerous other problems across the world which are leading to a great spread in misinformation on social media and otherwise. I wish to present the current issues facing the AI research community with respect to accountability and accessibility, and hope to provide a roadmap for building more democratic and ethical systems which are not biased towards the privileged.

- Prerequisites & reading material (Distributed before the session) 
A couple of news articles: 
https://www.cnbc.com/2020/12/03/ai-researcher-timnit-guru-says-shes-been-fired-from-google.html
https://thenextweb.com/news/someone-let-a-gpt-3-bot-loose-on-reddit-it-didnt-end-well

- Time required for the talk
20-25 minutes

- Link to slides / demos
Not made yet

- About yourself (Please include social media links, twitter, facebook)
I am a part-time graduate student at the University of Washington, and a software engineer at Paytm. My interests include computational linguistics, regional considerations of fairness and ethics in NLP, and how best we can build a safer and more democratic internet. My website is anjalibhavan.github.io/.

- Availability (When would you be able to give the talk?) 
The upcoming mega meetup? Any time after this week actually.

**Comment by Sc0rpi0n101** [comment]
Hey @anjalibhavan,

The event has been postponed to May 8th. Will you be available on that day for the talk?

**Comment by anjalibhavan** [comment]
Yeah sure, I will be!

**Comment by progmatic-99** [comment]
@anjalibhavan Is this talk delivered in PyDelhi's previous meetups?

If not, would you like to deliver it in an offline meetup on 23 July??

**Comment by yednapg** [comment]
Hey @anjalibhavan, Would you like to deliver this talk in an offline meetup on 23 July? If yes, please let me know as soon as possible, and are you in the telegram group of PyDelhi?
