### ISSUE TITLE
Finding high-impact performance bottlenecks in a Django application

### ISSUE THREAD

**Issue by shuttlesworthNEO** [pydelhi/talks#195]
### Title

- Finding high-impact performance bottlenecks in a Django application

### Brief description about the content to be covered

- We'll explore the drawbacks of abstraction in Django ORM, how to optimize queries and tools that can be used to identify bottlenecks and profile your Django application.
- The talk will be divided into 3 parts:
    - Preparing the data for benchmarking
    - Running the benchmarks
    - Analysis of results

### **Prerequisites & reading material (Distributed before the session)**

- Basic working knowledge of Django, esp. ORM: [https://docs.djangoproject.com/en/4.0/topics/db/queries/](https://docs.djangoproject.com/en/4.0/topics/db/queries/)
- Knowledge of joins in SQL: [https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-joins/](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-joins/)

### **Time required for the talk**

- 25 mins talk + 5 mins questions

### **Link to slides / demos**

- [Deck](https://docs.google.com/presentation/d/1Elhcf6SbrsF_3ZoIHr66RoFvCsOt-5t8oXYO6Bpb084/edit)

### **Hands on code repo**

- https://github.com/shuttlesworthNEO/pydelhi-django-optimisation

### **About yourself (Please include social media links, twitter, facebook)**

- I am a Senior Backend Engineer at Certa who has helped build many world-class engineering products, taking key architectural and design decisions. I am highly skilled in designing and developing scalable, data-driven software and have a thorough understanding of data structures, algorithms, back-end development, databases, operating systems, and machine learning.
- [LinkedIn](https://www.linkedin.com/in/shuttlesworthneo/)

### Availability (When would you be able to give the talk?)

- 21st May

### Any comments

**Comment by progmatic-99** [comment]
@shuttlesworthNEO Thanks for proposing this talk. Are you in the PyDelhi telegram group?
If not, can you comment your telegram ID so that communication becomes easier??

Thanks

**Comment by shuttlesworthNEO** [comment]
@progmatic-99 I'm not a part of the telegram group. You can find me with the handle `shuttlesworthNEO`

**Comment by Sanyambansal76** [comment]
@shuttlesworthNEO Looks interesting topic, looking forward to it.
