### ISSUE TITLE
Workshop: Getting started with the Twitter API v2 in Python

### ISSUE THREAD

**Issue by sparack** [pydelhi/talks#197]
- **Title**: Getting started with the Twitter API v2 in Python

- **Description**: The Twitter API v2 is the newest version of the Twitter API that includes new functionality such as bookmarks, conversation threading, Tweet annotations etc. It also includes dedicated access for academic researchers giving them the ability to search the full-archive of public Tweets for free. In this workshop, we will learn about the new features in the Twitter API v2 and learn how to work with it in Python using the Tweepy package. We will look at sample apps built with the Twitter API v2 in Python and coding a flask app together.

- **Prerequisites & reading material (Distributed before the session)** : https://developer.twitter.com/

- **Time required for the talk:** 90 Minutes

- **Link to slides / demos:** https://dev.to/twitterdev/a-comprehensive-guide-for-using-the-twitter-api-v2-using-tweepy-in-python-15d9

- **About yourself (Please include social media links, twitter, facebook)**: Suhem Parack is Staff Developer Advocate at Twitter. He helps developers and researchers in their journey of using the Twitter API. His work can be found on [Twitter](https://twitter.com/suhemparack) and [dev.to](https://dev.to/suhemparack)

- **Availability (When would you be able to give the talk?):** 20th July 2022

- Any comments

**Comment by progmatic-99** [comment]
Hey @sparack, thanks for proposing the talk. 
Are you part of PyDelhi telegram group??

**Comment by sparack** [comment]
No. Where do I sign up for it?

**Comment by progmatic-99** [comment]
@sparack Are you on telegram?? Just tell me your telegram username
If you are not on telegram, then you can download it from play store or ios store

**Comment by sparack** [comment]
Can you please [DM me on Twitter](https://twitter.com/suhemparack)

**Comment by yednapg** [comment]
Hey @sparack, We're going to have a physical meetup on 23, July 2022. We're very excited to have you as a Speaker. I hope you are ready for that. Just reply to this comment in order to confirm your spot latest by 17, July 2022!

If we didn't hear a response from you until 17, July 2022. It is very hard for us to schedule your Talk for the 23, July 2022 Meetup. Also Could you please add your e-mail in the comment for further instruction and communication?

Best,
Gaurav!

**Comment by sparack** [comment]
Yes, looking forward!
