### ISSUE TITLE
Having fun with text in Python or 🐍❤🔠

### ISSUE THREAD

**Issue by pulsar17** [pydelhi/talks#200]
- Title
Having fun with text in Python or 🐍❤🔠
- Brief description about the content to be covered
In this talk I will cover:
  - What is text? (an abstract and philosophical question)
  - What is Unicode? Why Unicode is required?
    - A brief tutorial on hexadecimal and a hexadecimal to binary conversion HOWTO (useful to understand Unicode codepoints and encodings)
    - Some terminology related to Unicode
  - A brief intro to encodings: `ascii`, `utf-8` [a short passing mention of `utf-16`, and `utf-32`]
    - What is an encoding and why should you even care about the encoding
    - Python's support for `utf-8` and encodings like it
    - Pythonic practices to read and write files when dealing with different OSs
  - Making an emoji search tool from scratch using just Python [Live Coding]
    - [Bonus: might skip if no time left] Ideas for further expanding this tool using Unicode Normalization Forms 

- Prerequisites & reading material (Distributed before the session) 
None. This will be a beginner talk. I'll explain everything needed to get started with Unicode in Python.
- Time required for the talk
~ 30 - 45 mins
- Link to slides - [pulsar17/talks](https://github.com/pulsar17/talks/tree/main/pydelhi)

- About yourself (Please include social media links, twitter, facebook)
  - I am currently a Backend Engineer at Aakash BYJU's
  - Generally excited about Python - the language and the surrounding community. I have some experience with Django. Also, my first open source code contributions were in Python, so Python has a special place in my heart (interestingly, the contributions were encoding related).
  - [Personal Blog](https://pulsar17.me)
  - git{[Hub](https://github.com/pulsar17), [Lab](https://gitlab.com/pulsar17)}
  - pulsar17 on Telegram
  
- Availability (When would you be able to give the talk?) 
Next planned meetup (16 Mar 2024)
- Any comments

**Comment by progmatic-99** [comment]
Hey @pulsar17, thanks for proposing this talk. Are you in the PyDelhi telegram group?

**Comment by pulsar17** [comment]
> Hey @pulsar17, thanks for proposing this talk. Are you in the PyDelhi telegram group?

Yes, I have the same @pulsar17 as my handle in the group.

**Comment by yednapg** [comment]
Hey @pulsar17, We're going to have a physical meetup on 23, July 2022. We're very excited to have you as a Speaker. I hope you are ready for that. Just reply to this comment in order to confirm your spot latest by 16, July 2022!

If we didn't hear a response from you until 16, July 2022. We'll ask you in on our Telegram Group and if we still didn't hear any response from you. It is very hard for us to schedule your Talk for the 23, July 2022 Meetup. Also Could you please add your e-mail in the comment for further instruction and communication?

Best,
Gaurav!

**Comment by pulsar17** [comment]
Hey @yednapg 
I acknowledge your comment and confirm that I'll be giving the talk as proposed.
My email ID is: ishaanarora1000 at gmail.com

**Comment by yednapg** [comment]
Thank You, So Much!

**Comment by pulsar17** [comment]
@Animesh-Ghosh should I prepare this talk for the upcoming meetup on 16th? I promise I'll make it interesting 😉

**Comment by Animesh-Ghosh** [comment]
Yes @pulsar17, please go ahead.
