### ISSUE TITLE
Proposal: Collaborative talk about Python opportunities in the UK with a work visa

### ISSUE THREAD

**Issue by RohancheH** [pydelhi/talks#201]
Love what you're doing at Pydelhi. It's an impressive set up you've put together. 

I'm actually writing to you from the UK and we are a data driven company connecting tech professionals with UK companies that can provide a work visa.

I'm not here to sell you anything and I'm not a recruiter. I'm contacting you to explore the potential of a collaboration. 

Do you think career opportunities within tech (Specifically Python) in the UK would be of interest to your community? If so, it could be great to collaborate and help inform them of the potential tech opportunities here. 

I think it could fit in well with what you do and could attract more members to your community by offering more diverse international career options.

We recently worked with a number of tech meetup communities in India and helped them grow their community by 30% from a number of collaborative talks and online events on this topic. 

The UK government is seeking top tech talent from India in particular and have launched a number of working visas to attract them since Brexit. Our government contacts tell us it's a top priority.

Would you be interested in arranging a brief chat to see how we could collaborate?

I look  forward to your reply.

**Comment by progmatic-99** [comment]
Hey @RohancheH, thank you for proposing this. Are you on telegram? 
If yes, please provide your telegram username, so I can add you to the PyDelhi group and we can talk about this with the community.

**Comment by RohancheH** [comment]
Hi Shubham

Thanks for your reply.

Yes I do have a telegram account. My username is RohanChe.

In addition my contact number is +44 7957 272 010

I look forward to discussing this with you further.

Many Thanks

Rohan Harris
Company Director
Email: ***@***.***
https://jobs.inter-cv.com/
http://www.inter-cv.com/


ᐧ
