### ISSUE TITLE
talks website is not responsive on the desktop screen when we add more than 4 talks videos

### ISSUE THREAD

**Issue by yednapg** [pydelhi/talks#203]
The talks website (https://pydelhi.org/talks/) is not responsive on the desktop screen when we add more than 4 talks videos, please see the attached image below.

<img width="1680" alt="Screenshot 2022-07-07 at 6 51 47 PM" src="https://user-images.githubusercontent.com/103869798/177784255-11aeab70-1dc7-4878-ae33-e370900ba0b8.png">

**Comment by progmatic-99** [comment]
You are working on this, right??

**Comment by yednapg** [comment]
yes!
