### ISSUE TITLE
What's new in Python 3.11?

### ISSUE THREAD

**Issue by yednapg** [pydelhi/talks#205]
### Title
What's new in Python 3.11?

### Brief description about the content to be covered
Every year a new Python Version is released, with new features, improvements, and many other things. In this talk, I will discuss “What’s new in Python 3.11 with a hands-on demo.”

What if you know, What’s the exact error in your code without debugging it or spending hours in identifying the issue? Python 3.11 makes it possible to some extent. It’s will detect, Where actually the error is? Not only better “Error Messages”, but also Python 3.11 is 10% - 60% faster than Python 3.10 version. 

In this talk, I will talk about these 2 major improvements in Python 3.11:
1. Better Error Messages (enhanced error locations in tracebacks)
2. Faster Python (CPython)

I think they are too much for 15 minutes of a lightning talk.

### Prerequisites
1. Basic Python knowledge should be required.

### Time required
15-20 Minutes

### Link to slides / demos
Live Coding

### About yourself (Please include social media links, twitter, facebook)
Twitter: @yednapg 

### Availability (When would you be able to give the talk?) 
Next Meetup

**Comment by Animesh-Ghosh** [comment]
@yednapg are you available to give this talk on the 17th of December?

**Comment by pulsar17** [comment]
Closing this since it has been open for a long time. @yednapg feel free to create a clone once you're available.
