### ISSUE TITLE
A Learning Curve - Scuba Diving Pro to Python 

### ISSUE THREAD

**Issue by zora89** [pydelhi/talks#206]
- Title 

A Journey of Transition - (Scuba Diving Pro to Python )

- Brief description about the content to be covered

1. I'd like to share my non-dev background very briefly. 
2. How living on a remote island with no internet motivated me to find a door into technology. 
3. Perspective on my technology beliefs, in a formative stage as they are. 
4. Show some code samples from my learning phase to projects that I am pursuing now. 
5. Present the challenges and nudges that have kept me going. 
6. Need for open source collaboration for enthusiasts & professionals.

- Prerequisites & reading material (Distributed before the session) 
 
Null

- Time required for the talk

30 Mins

- Link to slides / demos

https://github.com/zora89

https://youtu.be/9M3Smej2pDI

I'll combine a few more things locally on my machine to make it worth everyones time. 

- About yourself (Please include social media links, twitter, facebook)

https://www.instagram.com/zinstagran/

https://www.linkedin.com/in/zorawarpurohit/

- Availability (When would you be able to give the talk?) 

23rd July meet up, or anytime pydelhi deems fit. 

- Any comments

Null

**Comment by yednapg** [comment]
Hey @zora89, Thank You So, Much for proposing your talk. Unfortunately, we're not able to schedule your talk for July Meetup. It is ok if we reserve your talk for August Meetup.

Thank You!

**Comment by zora89** [comment]
Absolutely, I'd be happy to present & share anytime.

Look forward to seeing you on the 23rd, irrespective.


-
*Zorawar Purohit*
Virtual Meet: calendly.com/zpmeet
More Info: linktr.ee <https://linktr.ee/zorawarpurohit>
