### ISSUE TITLE
Continuous Integration With Python

### ISSUE THREAD

**Issue by patilswapnilv** [pydelhi/talks#210]
Core concepts behind Continuous Integration (CI) and why they are essential for modern software engineering teams.

Discussion around how to set up Continuous Integration for your Python project to automatically create environments, install dependencies, and run tests. How to work with GitHub, CircleCI, and PyTest, etc

**Comment by yednapg** [comment]
Hey @patilswapnilv, Thank You so much for proposing the talk. I would recommend you please use our Issue Template, it would be easier for us to review your talk.

Best!

**Comment by yednapg** [comment]
Hey, @patilswapnilv **Last Call**, Are you available for the PyDelhi August Meetup? or for September Meetup. Also please tell me how much is required for the talk.

Best,
Gaurav!

**Comment by yednapg** [comment]
Hey, @patilswapnilv I've did not get a response yet so I am closing this. If you want to talk in PyDelhi future meetup. Please feel free to create a new issue.
