### ISSUE TITLE
How to build a successful career in AI by Sameer Nigam

### ISSUE THREAD

**Issue by aisociety-in** [pydelhi/talks#211]
- How to build a successful career in AI. 

-  I will be giving about how to build a successful career in AI. We will have an in-depth discussion on right way to start a career in AI regardless of experience and background. I will also discuss ways to apply for AI-related internships or jobs and explain what is the right way to learn everything about AI without getting scared by mathematics.

- Not as such. This talk is for everyone.

- 2 hours or more. I can manage accordingly.

- Link to Demo- https://www.instagram.com/tv/CLrK0Bfg70b/?utm_source=ig_web_copy_link
(I can give both in English and Hindi)

- Sameer Nigam is the founder of AI SOCIETY and has successfully worked as an Artificial Intelligence instructor since 2018. He has helped tutor over 300+ people all over the globe who are now finding good jobs in AI. He teaches and spreads knowledge about the latest advancements in AI on various social media platforms. He has a mission to spread the awareness of AI to every corner of the world through educational courses and workshops and by placing students in well-paying jobs. He sincerely believes that the success of an online educator in Artificial Intelligence is measured by his ability to help students develop technical and analytical skills with an understanding of the importance of leadership, business, and mathematics. 
- He is also a public speaker who gave seminars on building a successful career in AI at institutions like Manipal University, Indus University, National Railway Institute of Technology, Delhi University, and many more.
- He writes blogs that are even praised by the course director of Artificial Intelligence at Oxford University.

**Social Media Links**
**Instagram**- https://www.instagram.com/aiwithsameer/
**LinkedIn**- https://www.linkedin.com/in/aiwithsameer/
**Youtube**- https://www.youtube.com/aisociety
**Twitter**- https://twitter.com/AIwithSameer

You can directly connect me on LinkedIn or 8299856425(Non-WhatsApp) 

- 20th August

- Any comments- You guys are doing great work. I just wanted to know the Audience Type and Size.

**Comment by yednapg** [comment]
Hey Sameer, Thank You so much for proposing the talk. Our Program team loves the Talk but before fitting it into the schedule we need additional information about your talk. 

1. As you said you require 2 hours for your talk, which is not fitting into our schedule. We can provide a maximum of 60-70 minutes.
2. As we're a community of Python Users, your talk should somehow be related to Python or have technical concepts with code examples if possible. 
3. We would prefer the English Language for the talk although you can mix it up with Hindi.

Please reply as soon as possible, Thank You for proposing the talk.

Best,
Gaurav! @PyDelhi

**Comment by aisociety-in** [comment]
Thank you for your email Gaurav. Since the posting asked about my talk, so
I mentioned it.

1. 60-70 minutes can also work for me.
2. We can create an AI project using python to create interest for AI after
the presentation(in total, it will not take more than 70 minutes).
3. Most of my talks are in English, so no problem with that too.

Regards,
Sameer Nigam.

**Comment by yednapg** [comment]
Hey Sameer, Thank You so much for the reply. I would love to see you on the meetup day which is scheduled on 20th August 2022. I will send you more information 2-3 days before the event.

Best,
Gaurav! @PyDelhi

**Comment by aisociety-in** [comment]
Happy to hear from you. I will be waiting for more information. I’ll book
the tickets right away.

**Comment by aisociety-in** [comment]
Hi Gaurav, can I get a confirmation of the offline event on 20th August?

**Comment by aisociety-in** [comment]
Please call on this number for the confirmation of the event. I need to ask
some urgent things

8299856425

**Comment by aisociety-in** [comment]
Now only two days are left for the event. Still no information. Please
don’t procrastinate on this email and reply asap.

**Comment by yednapg** [comment]
Hey, @aisociety-in Thank You for being patient, as I am still a school student I can't reply to you every time, please allow me a bit more time to collect details from Operations Team to get details about the venue. I will positively confirm by today. 😊

**Comment by yednapg** [comment]
Hey, Sameer. Thank You for being patient. I've contacted the Team, the venue details are here.

Venue: Prismberry, C-79, C Block, Sector 2, Noida, Uttar Pradesh 201301
Venue Location: https://goo.gl/maps/B17fxL92gV7EC32K8

We're excepting 30-40 people for our meetup.

Best,
Gaurav!

**Comment by aisociety-in** [comment]
Thanks you for the info Gaurav. I will be there
