### ISSUE TITLE
Python Decorators Walkthrough

### ISSUE THREAD

**Issue by vj18** [pydelhi/talks#214]
### Title

Hands-on python decorators

### Describe your Talk

The talk is mostly intended for students who are looking to learn more about python. 

It will begin by explaining how functions behave in python and then move towards:
- Decorator syntax and flow of control
- Decorators without parameters
- Decorators with parameter
- using *args and **kwargs

### Pre-requisites & reading material

Basic python syntax. Completely beginner friendly.

### Time required for the talk

Est. 30 min

### Link to slides/demos

Live coding. Code will be later uploaded to GitHub.

### About you

[Veebhor Jain](https://www.linkedin.com/in/veebhor-jain/)

### Availability

Next Meetup

**Comment by yednapg** [comment]
Hey, @vj18 Thank You for proposing a talk, Is it possible for you to give a talk at our September Meetup?

Best,
Gaurav! @PyDelhi

**Comment by vj18** [comment]
Sure.

**Comment by yednapg** [comment]
Hey Veebhor, Thank You. Please allow us 3-4 Days to schedule your talk. I will let you the final decision latest by 13 August. 

Best,
Gaurav! @PyDelhi

**Comment by yednapg** [comment]
Hey Veebhor, Your talk is accepted and scheduled for September Meetup! 

Best,
Gaurav! @pydelhi

**Comment by yednapg** [comment]
Hey Veebhor, As your talk is scheduled for September Meetup, I would like to send you more info about the Meetup.

**Expected Audience Size**: 50-70
**Skill Level**: Mixed
**Language**: Both Hindi and English
**Venue**: WeWork Blue One Square, Udyog Vihar, https://goo.gl/maps/WapZNgD4pFWKN39R8. 
**Timings**: 11:00 AM - 4:00 PM

If you need more information or have any questions please don't hesitate to ask.

Best,
Gaurav! @pydelhi

**Comment by yednapg** [comment]
Hey Need confirmation from your side, are you ready for the meetup? please reply.

**Comment by vj18** [comment]
Yes, I'll be there on 17th.

**Comment by yednapg** [comment]
Great See you there! 👋

**Comment by Animesh-Ghosh** [comment]
@vj18 are you available to give this talk again on 19th November?

**Comment by vj18** [comment]
Yes. Sure.
