### ISSUE TITLE
Python packaging: from stone age to the future

### ISSUE THREAD

**Issue by Saransh-cpp** [pydelhi/talks#215]
### Title

Python packaging: from stone age to the future

### Describe your Talk

A brief plan -
1. What is packaging and why would you need it in `Python`?
2. `distutils`, `setuptools`, and `PEPs`
3. A very simple `Python` package.
4. Enter `setup.py`
5. Enter `setup.cfg` and related `PEPs`
6. Enter `pyproject.toml` and related `PEPs`
7. `Python` packages are powered by wheels?
8. Generate `wheel` files and install the package
9. `cibuildwheel` and `twine`  (introduce and leave it up to the users to explore)
10. Enter `pip` and why you should always use `pip`
11. Enter `pipx`, or `pip` on steroids (introduce and leave it up to the users to explore)
12. A modern build backend - [hatch](https://github.com/pypa/hatch)
13. What about projects mixing Python with C++?
14. Future for the projects using Python and C++

### Pre-requisites & reading material

Have a basic knowledge of Python and a will to learn.

### Time required for the talk

30-40 minutes (maybe 45-50)

### About you

I am an engineering junior at [Cluster Innovation Center](http://cic.du.ac.in/), [University of Delhi](http://du.ac.in/), pursuing a major in Information Technology and Mathematics. In daylight, I work towards my academic skills and professional commitments, and by night, I develop and maintain open-source research software, which I believe are the key to collaborative and reproducible research.

Currently, I am a [fellow](https://iris-hep.org/fellows/Saransh-cpp.html) at the [Analysis Systems](https://iris-hep.org/as.html) group of [Institute for Research and Innovation in Software for High Energy Physics (IRIS-HEP)](https://iris-hep.org/), where I am working on the first-ever major release of [Vector](https://github.com/scikit-hep/vector) under [Dr. Henry Schreiner](https://iscinumpy.gitlab.io/page/about/) and [Dr. Jim Pivarski](https://github.com/jpivarski). I am also working as a technical writer for [FluxML](https://fluxml.ai/) under [Julia Season of Contributions](https://julialang.org/jsoc/). I am interested in everything a [Research Software Engineer](https://us-rse.org/about/what-is-an-rse/) and a Machine Learning Engineer do! I am passionate about Scientific Machine Learning, Computer Vision, developing packages, code optimization, technical writing, building infrastructures and CI/CD pipelines, developing and advocating open-source research software, JuliaLang, and Python. Psst, I was previously interested in Android and backend development, and though I still remember most of them, I have moved on.

### Availability

Most possibly the upcoming session.

**Comment by yednapg** [comment]
Hey, @Saransh-cpp  Thank You for proposing a talk, Is it possible for you to give a talk at our September Meetup?

Best,
Gaurav! @PyDelhi

**Comment by Saransh-cpp** [comment]
Yes, no worries!

**Comment by yednapg** [comment]
Hey Saransh, Thank You. Please allow us 3-4 Days to schedule your talk. I will let you the final decision latest by 13 August.

Best,
Gaurav! @PyDelhi

**Comment by yednapg** [comment]
Hey Saransh, Your talk is accepted and scheduled for September Meetup! 

Best,
Gaurav! @pydelhi

**Comment by yednapg** [comment]
Hey Saransh, As your talk is scheduled for September Meetup, I would like to send you more info about the Meetup.

**Expected Audience Size**: 50-70
**Skill Level**: Mixed
**Language**: Both Hindi and English
**Venue**: WeWork Blue One Square, Udyog Vihar, https://goo.gl/maps/WapZNgD4pFWKN39R8. 
**Timings**: 11:00 AM - 4:00 PM

If you need more information or have any questions please don't hesitate to ask.

Best,
Gaurav! @pydelhi

**Comment by Saransh-cpp** [comment]
Thanks, @yednapg! Is there a tentative date for the September meet-up?

**Comment by Saransh-cpp** [comment]
Thanks! Works for me!

**Comment by yednapg** [comment]
Great, are you on PyDelhi Telegram Group, if not please send me your Username so that I can add you.

**Comment by yednapg** [comment]
Hey Need confirmation from your side, are you ready for the meetup? please reply.

**Comment by Saransh-cpp** [comment]
Hi, @yednapg! Sorry for the delay, but I just went through the venue and it is around a 2 hour ride from my home. It would be very difficult for me to travel there the upcoming weekend (given that PyHEP is also next week, and I am presenting my summer research work remotely). Would it be possible to reschedule my talk for the next PyDelhi meetup? Apologies for the inconvenience.

**Comment by yednapg** [comment]
Hey, @Saransh-cpp I am very sorry to hear that. As we already schedule your talk I can move to the very beginning at the meetup you'll be free by 11:30 - 12:00. Please let me know as soon as possible I have a meeting with the Operations team tomorrow for finalizing the schedule.

Best, Gaurav!

**Comment by Saransh-cpp** [comment]
That sounds good, @yednapg! My telegram username is `@SaranshChopra`. I can deliver my talk early in the morning!

**Comment by pulsar17** [comment]
@Saransh-cpp are you available to give this talk again on 19th November?

**Comment by Saransh-cpp** [comment]
Hi, @pulsar17

I really want to. But, unfortunately, it won't be possible for me to give this talk again on 19th November because of my upcoming endsems.

**Comment by pulsar17** [comment]
No problem @Saransh-cpp
