### ISSUE TITLE
Where do the 🐍🐍🐍 go? [hint: venvs]

### ISSUE THREAD

**Issue by pulsar17** [pydelhi/talks#216]
### Title

Where do the 🐍🐍🐍 go? [hint: venvs]

### Describe your Talk

As a beginner, using virtual environments felt like using incantations of dark magic 🧙. 

I will attempt to demystify them.

So, In this talk I will cover:
  - Virtual Environments (referred to as `venvs` hereafter)
  - Why were venvs introduced. What problem(s) do they solve.
  - How and why do venvs work
    - What happens when I `source venv/bin/activate`
    -  How being "in" a venv affects:
        - `pip install stuff`
        - `import stuff`
  - A brief intro to Python's import machinery (in context of venvs)

### Pre-requisites & reading material

None.

This will be an intermediate level talk (though I encourage everyone irrespective of their level to attend, this stuff will become important 6 months later in your journey if not now, maybe you'll revisit this talk then 😉).

It'll also help if people are familiar with basic UNIX concepts (like PATH, symlinks, etc) [I will explain those as well for completeness]

### Time required for the talk

~ 30-45 mins

### Link to slides/demos

WIP (will update here once finalized)

### About you

- Generally excited about Python - the language and the surrounding community. I have some experience with Django but I love to use Python for everything :). Sometimes I also write Lua for a change. 
- [Personal Blog](https://pulsar17.me)
- git{[Hub](https://github.com/pulsar17), [Lab](https://gitlab.com/pulsar17)}
- pulsar17 on Telegram
- [@realpulsar17](https://twitter.com/realpulsar17) on Twitter

### Availability

Any future meetup

### Any comments

The title is meant to be read as "Where do the snakes go? [hint:virtual environments]" 😉

**Comment by progmatic-99** [comment]
Is this delivered?? @yednapg 

If not, can you squeeze it down to 30 mins, @pulsar17 ??

**Comment by yednapg** [comment]
yes delivered!
