### ISSUE TITLE
'Cloud Firestore' -  The startup world's nitro

### ISSUE THREAD

**Issue by BabneetRehal** [pydelhi/talks#217]
### Title

'Cloud Firestore' -  The startup world's nitro

### Describe your Talk

The latest trending technologies look brighter at the start but slowly take us towards a horizon that scatters the focus of Business. This talk is a quick overview of Why to use Firestore for your startup / next project and How efficiently will the family of Firebase helps you to launch a scalable solution, faster. More importantly, you can understand the limitations and make them work in your favor.

We would want to cover sub-topics around Firestore 

- Introduction
- Firebase Family
- Usual Interaction Layers
- Architecture
- How it works?

### Pre-requisites & reading material

- Meeting over Google Meets
- Q&A using our internal product Dory

### Time required for the talk

60 minutes (40 minutes of talk followed by Q&A)

### About you

Fluxon is a global product development company founded by ex-Googlers and startup founders. We work with fast-growing startups and tech leaders like Google, Stripe and Zapier to deliver the world’s most innovative products. Bringing together strong expertise across disciplines and industries, Fluxon offers full-cycle software development: from ideation and design to build and go-to-market.
[Intro to Fluxon (New).pdf](https://github.com/pydelhi/talks/files/9450785/Intro.to.Fluxon.New.pdf)

- Our Website - https://www.fluxon.com/ 
- Our LinkedIn Page - https://www.linkedin.com/company/fluxon/
- Deck - Enclosed

### Availability

22/09/2022

### Any comments

Speaker mostly be few of them :

- Arvind Kumar Chinniah | https://www.linkedin.com/in/arvindkumarchinniah/
- Edgard Lindner | https://www.linkedin.com/in/edgardlindner/
- AJ Ross | https://www.linkedin.com/in/lasersox/

We prefer to have two speakers, one from India & one from Ex-India.

**Slides are under preparation and will be shared soon.**

**Comment by yednapg** [comment]
Hey, Thanks for the proposal, I have a couple of questions.

1. How your talk is related to Python? or Open Source
2. All of our events are Offline, maybe hybrid in the future. Our latest meetup is on 17th September 2022.

We have more questions, it is possible to have a quick chat on google meet.

Best,
Gaurav!

**Comment by BabneetRehal** [comment]
Hey Gaurav,

Thank you for your email. Sure, let me know your time preference and I can
set up the calendar invite accordingly.
I am also available on handphone +91-9999079569.

Thanks!

**Comment by yednapg** [comment]
Great, Please set up meeting today, after 7 PM IST.

Best,
Gaurav!

**Comment by BabneetRehal** [comment]
Great Gaurav!

I am available at 07 or 07:30 pm IST at *meet.google.com/pbz-hkdg-tij
<http://meet.google.com/pbz-hkdg-tij>*.
Let me know the relevant email address to shoot the calendar invite.


Thanks!

**Comment by yednapg** [comment]
I'll prefer 7 PM IST, and the email address are:-

1. yednapg@gmail.com
2. shubham.upreti@gmail.com 

Best,
Gaurav!

**Comment by BabneetRehal** [comment]
Sure, Gaurav!

However, one thing to notify is that Fluxon works in the remote and
distributed setup and thus we are looking to collaborate only with the
groups that are open for online Meetups.
I hope it works for the pydelhi group.

Thanks!

**Comment by yednapg** [comment]
Hey, Sorry for the late reply. I talked to my team and we discussed that this is not related to Python and Open-Souce. So, in that case, you have to provide sponsorship to PyDelhi. For E.g, Swags, Books, Tech products (Mouse Keyboard, SSD), Python merchandise, etc. Please note that we do not accept sponsorship in Cash or bank transfer. 

About Online, yes we have decided to have an Online Meetup or Workshop with other speakers if you are ready to provide sponsorship we'll decide a day and other things.

Best,
Gaurav & PyDelhi
