### ISSUE TITLE
An Entrepreneurial Ride -  Scuba Pro to Python Programmer   

### ISSUE THREAD

**Issue by zora89** [pydelhi/talks#218]
### Title

An Entrepreneurial Ride -  Scuba Pro to Python Programmer   

### Describe your Talk

- Share my pre-dev adventures in the ocean and on an island.
- Living on an island with no internet to finding doors in technology.
- Perspective on gig economy and `India` as a software export hub.
- Code samples from my learning phase to projects that I am pursuing now.
- Challenges and nudges that have kept programmers going.
- Need for open source collaboration for enthusiasts & professionals.
- Live coding [ 'list comprehension', ' flask "Hello World" ', 'API Integration Quick Walk Through']

### Time required for the talk

90 minutes

### Link to slides/demos

https://slides.com/zorawarpurohit/code

### About you

[About Me](https://zorawar.bio.link/)

### Availability

17/09/2022

**Comment by yednapg** [comment]
Hey Need confirmation from your side? please reply.

**Comment by zora89** [comment]
Yes , flying in on 15th for the same.


-
*Zorawar Purohit*
Virtual Meet: calendly.com/zpmeet
More Info: Bio <https://zorawar.bio.link/>
