### ISSUE TITLE
Scraping from beautiful soup to selenium

### ISSUE THREAD

**Issue by gamer496** [pydelhi/talks#22]
In this talk I will start from the bottom as to how people study a website and scrape starting from beautiful soup and how selenium may be the last resort in certain situations.

**Comment by aktech** [comment]
Hi @gamer496 do you have a content outline/slides/code?

**Comment by gamer496** [comment]
Yeah @aktech here is my bit link https://bitbucket.org/gamer496/
Also will prepare the slides.
The outline consists of:
1.)Starting from the easiest like some startups.
2.)Checking on which security the website has implemented.
3.)How you may never want to do scrapping without proxies.
4.)How to easily integrate proxies in different scripts.
5.)BeautifulSoup and requests vs scrapy.
6.)And how selenium beats them all but on account of speed.

**Comment by aktech** [comment]
Great! are you available on this meetup on Saturday (28 May) for the talk?

**Comment by gamer496** [comment]
I have end-sem  tests from 30th.
I was hoping I could give this talk on next meetup.

**Comment by aktech** [comment]
Alright no, problem.

**Comment by theskumar** [comment]
@gamer496 I'm closing this up as it's been open for quite a while. Please feel free to reopen if you still want to present the topic in any of our meetups.
