### ISSUE TITLE
Building on Solana with Python

### ISSUE THREAD

**Issue by akshatcoder-hash** [pydelhi/talks#222]
### Title

BUIDL on Solana with Python 🐍

### Describe your Talk

Solana was released in March 2020. It is considered to be the fastest blockchain with scalability of 65k Transactions Per Second.
Initially, C was required to build on solana and now it has completely shifted itself on Rust. There is a framework named [Seahorse](https://seahorse-lang.org) which allows developers to build on this powerful blockchain with Python.

I will be starting with the very basics of Blockchain, some core concepts of Ethereum and then finally moving on to Solana, its advantages, consensus mechanism i.e. Proof of History and diving deep into it.
Then we'll be moving to a Hands On Demo with Seahorse and till the end, we'll have minimum 2 programs built with Seahorse (as the time allows).

### Time required for the talk

45 mins

### About you

I am the Co-Founder of FOSS Community and we have successfully established a local chapter of the community at KIET Group of Institutions, Ghaziabad.
Ex-Intern @ [Solana Spaces](https://solanaspaces.com/)
Currently, I am working on [Shastra OS](https://shastraos.co/) - An Open Source Operating System built on the top of Arch Linux kernel and crafted specifically for Web3 users.
I have been an Evita DAO Fellow for the Batch-5 for blockchain development.

### Availability

26/11/2022 or any upcoming dates

### Any comments

Twitter - [akshatwts](https://twitter.com/akshatwts)

**Comment by progmatic-99** [comment]
Hey @akshatcoder-hash , thanks for proposing this talk.

Would you like to deliver this talk at our 17th December meetup ??
Can you reduce your talk's time to 30 mins ??

**Comment by akshatcoder-hash** [comment]
Hey @progmatic-99! 
Yeah, I can surely reduce the talk's time.
Sorry, but I would not be available for that 17th December week. Can it be covered in before or after that week?

**Comment by progmatic-99** [comment]
Yes, you can deliver the talk at one of our upcoming meetups

**Comment by Animesh-Ghosh** [comment]
Hey @akshatcoder-hash, would you be available on the 21st January?

**Comment by akshatcoder-hash** [comment]
Hey @Animesh-Ghosh 

I am extremely sorry, but I am not available for this whole week.
Let's see if we can make it to Feb.
Best,
Akshat

**Comment by pulsar17** [comment]
Hey, our upcoming meet-up will be on the 18th February. Would you be available then @akshatcoder-hash ?

**Comment by akshatcoder-hash** [comment]
Hey! @pulsar17 
Sorry for this time, but I have my exams from 20th Feb. Also, I'll be occupied with academics in March as well.
April will be good for the talk.
