### ISSUE TITLE
How to create an Open source chatbot using Python & Machine Learning framework

### ISSUE THREAD

**Issue by aparna2071** [pydelhi/talks#224]
### Title

How to create an Open source chatbot using Python & Machine Learning framework

### Describe your Talk

- It is a chatbot for career related queries created using Python & Rasa machine learning framework
- The installation of RasaX will be discussed, why to prefer RasaX over Rasa will also be discussed
- Then a chatbot will be created & also integrated with a social media platform
- After the project is built, it will be made open source for everyone to use & collaborate
- This will be a live coding session 

### Pre-requisites & reading material

- Basics of Python, Machine learning
- Python, Anaconda & Microsoft Build tools with visual c++ 14.0 should be installed on the system

### Time required for the talk

30 mins

### About you

I am a Full stack developer at Accenture & an Open source advocate. I help people in their Open source journey through blogs, twitter threads, YouTube videos, meetups etc.
I am a maintainer & active contributor of several communities on GitHub.
Moreover, I have been invited to Google cloud community day 2022, FOSS United & several twitter spaces as well as meetups to address folks about Open source.

- Twitter: https://twitter.com/AparnaSoneja
- GitHub: https://github.com/aparna2071
- LinkedIn: https://www.linkedin.com/in/aparna-35066b191/

### Availability

17/12/2022

**Comment by progmatic-99** [comment]
@aparna2071 thanks for proposing this talk. Are you in the PyDelhi telegram group??
If not, please share your telegram username. I will add you to the group.

**Comment by aparna2071** [comment]
Hi @progmatic-99 thanks for your reply.
My telegram username is @aparna2071.

**Comment by aparna2071** [comment]
Hi @progmatic-99 I have tried to add my introduction in the telegram group but it is not getting sent to the group, can you please look into this.

Also, would like to confirm that I too should join the connect that is scheduled for 7 pm ist today ? 

Your reply will be highly appreciated.
Thanks

**Comment by Animesh-Ghosh** [comment]
Hey @aparna2071, links to the slides and code samples would be much appreciated. Thanks!

**Comment by aparna2071** [comment]
> Hey @aparna2071, links to the slides and code samples would be much appreciated. Thanks!

sure, will add
