### ISSUE TITLE
[TFUG] A gentle introduction to LSTM

### ISSUE THREAD

**Issue by vj18** [pydelhi/talks#225]
### Title

A gentle introduction to LSTM and demo code

### Describe your Talk

- What is Long Short Term Memory?
- What happens behind model.fit function
- Applications and demo python code for predicting stock market trends

### Pre-requisites & reading material

Basic Python

### Time required for the talk

Est. 30 min

### Link to slides/demos

[Slides](https://docs.google.com/presentation/d/1pJoNay7ntkrQYSwtOAG38Q3odf-9uuy4/edit?usp=sharing&ouid=103984180317609436755&rtpof=true&sd=true)

### About you

I am a Data Scientist with 4 years of experience working in startups with computer vision based products. I am also the co-organiser for TFUG Delhi. In my free time I am either coding or reading books.
[Veebhor Jain](https://www.linkedin.com/in/veebhor-jain/)

### Availability

17/12/2022

**Comment by Animesh-Ghosh** [comment]
Hey @vj18, thank you for proposing this talk. Looking forward to it in the upcoming meetup!

**Comment by Animesh-Ghosh** [comment]
Hey @vj18 could you also share the link to the slides here? Thanks!
