### ISSUE TITLE
Automated life with .py

### ISSUE THREAD

**Issue by ashishdevo28** [pydelhi/talks#226]
I want to talk about **"Automated life with .py"**
- Why automate
- Why python can easily used to automate
- Examples of Automation with Python
- Which libraries can be used
- Scope of automation
- How Industries are automating
- Example code for automation

You can get to know more about me here [Linktr.ee](https://www.linktr.ee/ashishdevo28/)

**Comment by Animesh-Ghosh** [comment]
Hey, could you please add a bit more details to your proposal? Try following [this](https://github.com/pydelhi/talks/issues/new?assignees=yednapg&labels=proposal&template=talk-proposal.yaml). Thanks!

**Comment by Animesh-Ghosh** [comment]
> Hey, could you please add a bit more details to your proposal? Try following [this](https://github.com/pydelhi/talks/issues/new?assignees=yednapg&labels=proposal&template=talk-proposal.yaml). Thanks!

@ashishdevo28. Forgot to ping on the last comment.

**Comment by pulsar17** [comment]
Hey, our upcoming meet-up will be on the 18th February. Would you be available then @ashishdevo28 ?

**Comment by progmatic-99** [comment]
@ashishdevo28 ??

**Comment by ashishdevo28** [comment]
> Hey, our upcoming meet-up will be on the 18th February. Would you be available then @ashishdevo28 ?

Hey @Animesh-Ghosh, Can you share me the timings?

**Comment by Animesh-Ghosh** [comment]
@ashishdevo28 tentative timings are 12 PM to 5 PM on Saturday 18th February, 2023.

**Comment by ashishdevo28** [comment]
@Animesh-Ghosh Give me some time to reschedule my 18th February, and get back to you!

**Comment by ashishdevo28** [comment]
@Animesh-Ghosh What's the location for the talk?

**Comment by ashishdevo28** [comment]
Hey, @Animesh-Ghosh, @pulsar17 @progmatic-99,
I'm available for the talk for 18th February. Let'm known the further steps.

**Comment by Animesh-Ghosh** [comment]
@ashishdevo28 are you available for giving the talk on 15th March?

**Comment by ashishdevo28** [comment]
Hey @Animesh-Ghosh, I'm available on 15th March and very interested in giving the talk. Do let me know the next steps!

**Comment by ashishdevo28** [comment]
@Animesh-Ghosh Can I also change the title for the talk?

**Comment by ashishdevo28** [comment]
@Animesh-Ghosh  Can I also change the title for the talk?

**Comment by Animesh-Ghosh** [comment]
@ashishdevo28 sure, go ahead.

**Comment by ashishdevo28** [comment]
Thanks @Animesh-Ghosh, but you have mentioned 15th March are you trying to say May or April?

**Comment by Animesh-Ghosh** [comment]
My bad, I meant 15th April @ashishdevo28.

**Comment by ashishdevo28** [comment]
Oh, I thought 15th of Next month. I'm not available on 15th April as I'll be in a Hackathon. I hope to connect with you soon for the next session. And Thanks a Lot @Animesh-Ghosh. I was really excited for the talk this time!

**Comment by ditsuke** [comment]
@ashishdevo28 are you available to give this talk in-person on the 17th of June?

**Comment by pulsar17** [comment]
Closing this, feel free to reopen again
