### ISSUE TITLE
[TFUG] Creating ETL pipelines for Geospatial Data

### ISSUE THREAD

**Issue by chaitanya1-coder** [pydelhi/talks#227]
### Title

Creating ETL pipelines for Geospatial Data 

### Describe your Talk

A lightning talk on working with Geospatial Data  :
This talk Includes :
What is Geospatial Data ?
Extracting Data using Google APIs and Google Cloud Platform
Loading Data on Web Apps

### Pre-requisites & reading material

Basic Knowledge of any programming language

### Time required for the talk

15 min

### About you

I am Chaitanya, final year student of Computer Science Engineering of GGSIPU, New Delhi. 
I am working as Developer Relations Engineer at STYAVA.DEV. 
My interests are Web Development, Cloud Computing and Data Science. 
[Let's Connect on LinkedIn](https://www.linkedin.com/in/chawla-chaitanya/)

### Availability

17/12/2022

**Comment by Animesh-Ghosh** [comment]
@chaitanya1-coder would you be available to give this talk on the 21st January?

**Comment by chaitanya1-coder** [comment]
> @chaitanya1-coder would you be available to give this talk on the 21st January?

@Animesh-Ghosh Thankyou for your response. Sorry, I am not available on 21st January.

**Comment by pulsar17** [comment]
Hey, our upcoming meet-up will be on the 18th February. Would you be available then @chaitanya1-coder?

**Comment by ditsuke** [comment]
@pulsar17 
I suggest we consider closing this issue due to the author's lack of availability to respond.
