### ISSUE TITLE
Proposal: Building Brain-Computer Interfaces with Timeflux

### ISSUE THREAD

**Issue by mesca** [pydelhi/talks#228]
Hi!

I will be in Delhi during the second half of January, and if you are interested, I can give a talk about how to build brain-computer interfaces in Python.

> Brain-Computer Interfaces (BCIs) enable people to interact with physical devices by using their mind only. Until recently, building such systems was the prerogative of the academic world. It is now time to get BCIs out of the lab and into the hands of programmers. During this talk, we will introduce Timeflux (https://timeflux.io), a free and open-source Python framework for real-time biosignal processing, and will demonstrate how to build a virtual keyboard that you can control with your mind.

**Comment by Animesh-Ghosh** [comment]
Hey @mesca, we'll most likely be having our meetup on the 21st January. Would you be available on that date to give the talk?

**Comment by mesca** [comment]
Hi @Animesh-Ghosh 
Yes, I am available on the 21st. Would a 45 min talk + 15 min Q&A work for you? Do you have a Whatsapp or equivalent where we can arrange the details?

**Comment by Animesh-Ghosh** [comment]
Yup @mesca, that sounds good. We do have a Telegram channel which we could invite you to. If you're on Telegram, could you share your Telegram username so that we could add you there?

**Comment by mesca** [comment]
Hey @Animesh-Ghosh, I am @m3sc4‬ on Telegram.
