### ISSUE TITLE
A tutorial on introduction to mathematical optimization using Python

### ISSUE THREAD

**Issue by indrag49** [pydelhi/talks#229]
### Title

Introduction to mathematical optimization using Python

### Describe your Talk

The tutorial will start with important prerequisites that need to be developed before starting with serious numerical optimization algorithms. Concepts like *a solution*, *minimization/maximization*, *scaling*, *objective function*, *gradient* and *Hessian* will be introduced. This first section will take around 15 mins

Next, we will explore unconstrained optimization techniques and discuss a few elementary mathematical backgrounds before diving into discussing how to solve one-dimensional optimization problems using algorithms called *Fibonacci search method*, *Newton’s method*, *secant method*, and **bisection method*, accompanied by their Python implementation. This section will consume around 30 mins.

In the next section of around 30 minutes we will cover *line search descent methods* for solving unconstrained optimization problems. Methods like *first-order line search*, *conjugate gradient*, *second-order line search* and *quasi-Newton*   will be discussed in detail along with Python implementation. 

Finally we will delve deeper into *conjugate gradient methods* covering the basics of *linear conjugate gradient* and *nonlinear conjugate graduate methods*, before ending the presentation with *rank 1 update* and *rank 2 update algorithms* in *quasi-Newton method*. The final section will be of around 15 minutes again.

While learning these optimization techniques, the Python packages that will be used are : 
* numpy,
* scipy (especially the module scipy.optimize),
* autograd, and
* matplotlib

### Pre-requisites & reading material

I believe this talk will help upper-level undergraduate and graduate students in Computer Science, Applied Mathematics, and other related fields, start exploring the field of numerical optimization hands-on. The audience is expected to have an undergraduate-level understanding of linear algebra, besides having an introductory working knowledge of Python/similar scripting languages and usage/implementation of Python packages.

### Time required for the talk

90 mins

### About you

 I am a Ph.D. candidate in applied mathematics from the School of Mathematical and Computational Sciences, Massey University, New Zealand. I work on dynamical systems and chaos. Besides my research topic, I am also interested in computational physics, optimization, data analysis, open-source software development, etc. I write codes in Python and R, and sometimes Fortran.

### Availability

01-02-2023

### Any comments

I came across the PyDehli meetup seminars through Twitter and was intrigued my the model that it portrays. I would love to present at the meetup if an online option is available. I am free during the first week of February, given that the time works out for everyone. Looking forward to hearing from the organizers.

**Comment by Animesh-Ghosh** [comment]
Hey @indrag49, would you be available to give your talk on the 21st?

**Comment by indrag49** [comment]
Hi @Animesh-Ghosh, do you mean 21st January? I have a tight schedule in January. Does anytime in February work? Thank you.

**Comment by Animesh-Ghosh** [comment]
Hey, our upcoming meet-up will be on the 18th February. Would you be available then @indrag49?

**Comment by indrag49** [comment]
Yes, February 18th works perfectly for me. Thank you.

**Comment by indrag49** [comment]
Hello @pulsar17 , Actually 1 p.m. IST will be 8:30 p.m. my time (New Zealand time). Can I start at 1 p.m IST? Then I will take a break at 1:45 IST for 15 mins before resuming at 2 p.m IST. Does this work for you?

Also, it would be fantastic if the audience could download the following notebooks  from Github: https://github.com/indrag49/Numerical-optimization-PyDelhi-meetup

Cheers,
Indra

**Comment by pulsar17** [comment]
@indrag49 we can schedule your talk at 12:30 pm IST. Is that fine with you?
Also please let me know if you're part of our telegram group (If not please share your username) as it's much easier there to have synchronous communication on the meetup day.

**Comment by indrag49** [comment]
Hi @pulsar17 , 12:30 p.m IST is even better for me. Thank you. My Telegram username is @indraghosh314.

**Comment by indrag49** [comment]
Hi @pulsar17, will there be a zoom link shared? I think I am not yet a member of the telegraph group of PyDelhi, could you please add me there? My username is @indraghosh314. Hope to see you soon! Thank you.

**Comment by pulsar17** [comment]
Hi @indrag49 , we'll be starting a bit late. I'll get you added in the group.
