### ISSUE TITLE
JayporeCI.in : a zero setup, offline first CI system

### ISSUE THREAD

**Issue by theSage21** [pydelhi/talks#230]
### Title

JayporeCI.in : a zero setup, offline first CI system

### Describe your Talk

I wanted to talk about the advantages a small CI system like JayporeCI can bring to solo dev projects where we have time to work on them but not set up a full CI system for all of them.

A few things that make this system different:

1. Zero setup. No need to set up a gitlab/drone/jenkins server.
2. Configure the pipeline in python instead of yaml.
3. Running locally and offline by default, instead of a remote runner.

### Time required for the talk

30 minutes

### Link to slides/demos

https://www.jayporeci.in

### About you

I'm Arjoonn and I live in Jaipur. I like to build small, powerful systems.
The only social media I'm on is https://github.com/thesage21/

### Availability

01/03/2023

### Any comments

I'm flexible with the dates. It can be any weekend.

**Comment by Animesh-Ghosh** [comment]
Hey @theSage21 would you be in Delhi in March? Or were you planning to have an online session?

**Comment by theSage21** [comment]
I can do a physical talk in March, no worries but I'll need to book tickets
so will needs dates beforehand.

**Comment by Animesh-Ghosh** [comment]
So the meet-ups happen on the 3rd Saturday. For March, that would be on the 18th.
If you're coming from Jaipur I think the Jaipur Double Decker might have seats available @theSage21.

**Comment by theSage21** [comment]
That sounds good to me. I can present it on 18th March.
