### ISSUE TITLE
Shruti Arora - DevRel For Developers

### ISSUE THREAD

**Issue by shrutiiaroraaa** [pydelhi/talks#232]
### Title

DevRel For Developers

### Describe your Talk

Through this talk I am gonna let the audience explore the  world of Developer Relations, also known as DevRel, and everything you need to know to get started in this exciting and emerging field.

### Pre-requisites & reading material

In order to get the most out of my talk on "DevRel for Developers", there are a few prerequisites that may be helpful.

1) Firstly, it would be useful to have a basic understanding of software development, programming languages.

2) Secondly, having some familiarity with the broader technology landscape and industry trends can help you to contextualize the role of Developer Relations within the wider ecosystem. This can include knowledge of emerging technologies, software development methodologies, and popular tools and platforms.

3) An open mind and a willingness to learn and engage with others will be crucial for getting the most out of this talk. Developer Relations is a constantly evolving field, and there will always be new ideas and approaches to explore.

### Time required for the talk

40 mins

### Link to slides/demos

https://www.canva.com/design/DAFWaZ_xkX4/b_lwm2YLAxIVN4NzFUA-jA/view?utm_content=DAFWaZ_xkX4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### About you

Hi there, my name is Shruti Arora and I am an aspiring computer science graduate in my final year of studies. I currently work as a Developer Relations professional at Permissionless, where I build relationships with developers and help them to be successful with our technology. I am also the founder of DevRelo, a platform that connects developer relations professionals around the world.

In addition to my work in Developer Relations, I am very active in the tech communities and enjoy participating in hackathons and open-source programs. I believe in the power of community and open-source technology to drive innovation and create positive change.

Thank you for taking the time to learn a little more about me. I am excited to continue on this journey and contribute to the Pydelhi.

My Socials - https://www.linkedin.com/in/shrutiiaroraaa/

### Availability

19/03/2023

**Comment by Animesh-Ghosh** [comment]
Hey @shrutiiaroraaa, would you be available to give this talk on the coming Saturday, on the 18th of March?

**Comment by ditsuke** [comment]
@shrutiiaroraaa are you available to give this talk in-person on the 17th of June?

**Comment by pulsar17** [comment]
Closing this, feel free create a new issue again.
