### ISSUE TITLE
Demystifying Python AsyncIO: A Real-World Approach

### ISSUE THREAD

**Issue by Mr-Sunglasses** [pydelhi/talks#233]
### Title

Demystifying Python AsyncIO: A Real-World Approach

### Describe your Talk

# Abstract
 Maybe it's just me, but I hate stupid examples. I hate reading about OOP with animal examples as much as I hate reading about async with the client using bare asyncio.sleep statements. Mostly because (considering you won't work for a zoo 🤷‍♂️) these examples will never get any close to real life. I don't want to start talking about the solution (i.e. async), I want you to feel the problem first, I want you to run things locally from your own computer. So, in this talk, I want then to explore async by using examples that you can run yourself and understand. So, the plan is to learn:
- What are sync and async processes with a real word example
- Where to use Sync and Async 
- Why and why not use Sync and Async
- Basic syntax and Usage of async in Python
- Explore async with slow HTTP queries
- Explore async with slow Database queries
- Share a real project running in production that uses async

# Description 

I noticed some people using the async syntax without knowing what they were doing. First, they think async is parallel which is not true. Then they write code that doesn't take any advantage of Python async. In other words, they write sync code with async syntax. The goal of this talk is to point out these performance issues and help you benefit the most from async code.

# 🤔 When to use Python Async
Async only makes sense if you're doing IO. There's ZERO benefit in using async to stuff like this that is CPU-bound. Your code might even get slower by doing that due to the Event Loop. That's because Python async only optimizes IDLE time!. IO-bound operations are related to reading/writing operations.
A good example would be:
- Requesting some data from HTTP
- Reading/Writing some json/txt file
- Reading data from a database

👆 All these operations consist of waiting for the data to be available.
While the data is UNAVAILABLE the EVENT LOOP does something else.
This is Concurrency.
NOT Parallelism.

So In this talk, we will dive into the world of synchronous and asynchronous processes with real-world examples that you can run on your own computer. We'll start by understanding the difference between synchronous and asynchronous processes and where to use each one. We'll explore the benefits and drawbacks of both sync and async processes to help you make informed decisions in your own projects.

We will then move on to explore the basic syntax and usage of async in Python, including how to create and run async functions. We will also discuss common pitfalls and best practices for using async in your code.

Next, we will take a deep dive into async with slow HTTP queries and slow database queries, showing you how async can help optimize your code and improve performance in these scenarios. We will provide real-world examples that you can run yourself, so you can see the benefits of async firsthand.

Finally, we will share a real project running in production that uses async, giving you a glimpse into how async can be used in a real-world scenario. By the end of this talk, you'll have a solid understanding of async and how it can be used to optimize your code and improve performance in a variety of scenarios.

### Time required for the talk

45

### About you

I am Kanishk Pachauri, a Second Year Computer Science Engineering Student at Kiet College Ghaziabad, From high school, I was passionate about Open-Source and Free Software. I love to Contribute to Open-Source Software I was also the Google Summer of Code Intern for 2022 under the Python Software Foundation and MLH Fellow for Fall 2021. I am also a Monthly Student Associate Member of the Free Software Foundation. Also, I am the Co-Founder of an Open-Source Community in my Local Area FOSSCU(Free and OpenSource Community United) fosscu.org which focuses on the promotion of FreeSoftware and OpenSource and Promote Contributing to them. I am an Upcoming Summer Engineering Intern at Google UK. Also, I am the Community Manager of Namaste Dev a Community with 21K members on Discord, where we all learn and share our technical learning and growth together. I love to share my knowledge of Open-Source and Free Software. Previously I delivered a talk at Pydelhi, Pycon France, FOSS United Delhi, and FOSSCU conference, and also I host many sessions to promote the Knowledge of Open-Source Contributions and Community Work.

<hr>

Links to my previous talks and Sessions -

Speaker in Panel Discussion at FOSS United Delhi -:
[Post](https://twitter.com/FOSSUnitedDelhi/status/1583080295569719301/photo/1)

[Video](https://www.youtube.com/watch?v=m0KkkvBWDts&t=2s)(https://www.youtube.com/watch?v=x5h1jjJTnAk)

Talk on Introduction to Python and make your own Git in Python -:
Post - [ https://www.instagram.com/p/ClRAl94y59C/ , https://www.instagram.com/p/ClgiPHsScmU/ ]
Video - [ https://youtu.be/PN0sqr_2dtg ]

Speaker of the Event on Decoding OpenSource - Getting Started with Open-Source and Contributions contributions -:
Post - [ https://www.instagram.com/p/CcH7tsereQP/ , https://www.linkedin.com/feed/update/urn:li:activity:6920808643261063169/ ]

Head of Organizing team of a 2-week-long Event on Contributing to Open-Source projects on Github :
Post - [ https://www.linkedin.com/posts/dsckiet_opensource-github-msoc-activity-6972203027164217344-O3jx?utm_source=share&utm_medium=member_desktop ]

Member of Organizing team of Tech-In-Tech in association with Pydelhi:-
Post - [ https://www.linkedin.com/posts/dsckiet_pydelhi-activity-6977962652526362624-7Ju1?utm_source=share&utm_medium=member_desktop , https://www.instagram.com/p/CjF44o5Lmjm/ ]

Links to the Slides from my Previous Talks:-

Decoding OpenSource:-
[slide](https://docs.google.com/presentation/d/1OvXC4FYQx3V9g8EYz3UKZAey4UueLcjGR9PYDvQKvr0/edit?usp=sharing)

Introduction to Git and Github:-
Slide - [ https://docs.google.com/presentation/d/1QkX1TXHpzqukt5e0rc-UqI5lLiSiIjdgvrdNOhxJUfE/edit?usp=sharing ]

Introduction to Free Software and Open-Source:-
Slide - [ https://slides.com/akshatsharma0023/deck#/12 ]

From Python Script to an Open-Source Project at FOSS Delhi:
Video - [ https://youtu.be/9A6MoVIxt_s ]

Talk at PyconFrance: 
Website - [ Links to my previous talks and Sessions -

Speaker in Panel Discussion at FOSS United Delhi -:
Post - [ https://twitter.com/FOSSUnitedDelhi/status/1583080295569719301/photo/1 ]
Video - [ https://www.youtube.com/watch?v=m0KkkvBWDts&t=2s , https://www.youtube.com/watch?v=x5h1jjJTnAk ]

Talk on Introduction to Python and make your own Git in Python -:
Post - [ https://www.instagram.com/p/ClRAl94y59C/ , https://www.instagram.com/p/ClgiPHsScmU/ ]
Video - [ https://youtu.be/PN0sqr_2dtg ]

Speaker of the Event on Decoding OpenSource - Getting Started with Open-Source and Contributions contributions -:
Post - [ https://www.instagram.com/p/CcH7tsereQP/ , https://www.linkedin.com/feed/update/urn:li:activity:6920808643261063169/ ]

Head of Organizing team of a 2-week-long Event on Contributing to Open-Source projects on Github :
Post - [ https://www.linkedin.com/posts/dsckiet_opensource-github-msoc-activity-6972203027164217344-O3jx?utm_source=share&utm_medium=member_desktop ]

Member of Organizing team of Tech-In-Tech in association with Pydelhi:-
Post - [ https://www.linkedin.com/posts/dsckiet_pydelhi-activity-6977962652526362624-7Ju1?utm_source=share&utm_medium=member_desktop , https://www.instagram.com/p/CjF44o5Lmjm/ ]

Links to the Slides from my Previous Talks:-

Decoding OpenSource:-
Slide - [ https://docs.google.com/presentation/d/1OvXC4FYQx3V9g8EYz3UKZAey4UueLcjGR9PYDvQKvr0/edit?usp=sharing ]

Introduction to Git and Github:-
Slide - [ https://docs.google.com/presentation/d/1QkX1TXHpzqukt5e0rc-UqI5lLiSiIjdgvrdNOhxJUfE/edit?usp=sharing ]

Introduction to Free Software and Open-Source:-
Slide - [ https://slides.com/akshatsharma0023/deck#/12 ]

From Python Script to an Open-Source Project at FOSS Delhi:
Video - [ https://youtu.be/9A6MoVIxt_s ]

### Availability

18/04/2023

### Any comments

I would love to volunteer for the meetup and I want to help the organizing community as much as I can. 
As part of the conference, I could help with the staff tasks including(but not limited to):
 - helping at the registration desk
- being a talk manager for a few hours 
- helping for managing the people during the breaks and lunches
- intervene to enforce the observation of the Code of Conduct in every situation related to the event. 

 Also, Please do tell me in what way I can help the team. and feel free to reach out to me for any volunteer work.

**Comment by akshayaurora** [comment]
Available to give the talk on 15/04/23 ?

**Comment by Animesh-Ghosh** [comment]
Tagging @Mr-Sunglasses for visibility, @akshayaurora.

**Comment by Animesh-Ghosh** [comment]
@Mr-Sunglasses we meant 15th April 2023.

**Comment by Animesh-Ghosh** [comment]
@Mr-Sunglasses would you be available to give the talk on the 20th of May, 2023?

**Comment by Mr-Sunglasses** [comment]
Yes @Animesh-Ghosh  I'll be available on 20th May 2023
