### ISSUE TITLE
Dapr Overview

### ISSUE THREAD

**Issue by DeepanshuA** [pydelhi/talks#235]
### Title

Dapr Overview

### Describe your Talk

Dapr is Ditributed Application Runtime, which helps in quickly creating microservices and solves many problems, like Observability, resiliency etc. without microservices to re-invent the wheel.
It uses sidecar architecture and has many building blocks to write standardized, language, component and platform agnostic code.

### Pre-requisites & reading material

Some basic knowledge about microservices.

Dapr Docs: https://docs.dapr.io/

### Time required for the talk

30 minutes

### Link to slides/demos

https://www.canva.com/design/DAFeklKPtns/EkqeEWoXCs3Rl-ZQ_aePKw/view?utm_content=DAFeklKPtns&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### About you

I have around 15 years of experience in Software Engineering filed. Currently, I am working with Microsoft in Dapr project.

### Availability

16/04/2023

**Comment by Animesh-Ghosh** [comment]
@DeepanshuA could you elaborate on how your talk is related to Python?

**Comment by DeepanshuA** [comment]
@Animesh-Ghosh I would be using https://github.com/dapr/python-sdk to setup microservices and though Dapr is not dependent on any language in particular, but let's say someone is developing microservices in Python, Dapr would let developer focus only on business logic and all other needs like service discovery, mtls, database, event management are taken care of.

Does that address your concern?

**Comment by akshayaurora** [comment]
@DeepanshuA available to give your talk on this 15.05.23?

**Comment by Animesh-Ghosh** [comment]
@DeepanshuA the date is 15th April 2023. The earlier comment had a typo.

**Comment by Animesh-Ghosh** [comment]
@DeepanshuA available to give your talk on 20th May, 2023?

**Comment by DeepanshuA** [comment]
Sorry, I am not available over weekends for a while.
Can I plan for 1st of July?

**Comment by Animesh-Ghosh** [comment]
@DeepanshuA would 17th June work for you?

**Comment by DeepanshuA** [comment]
Yeah, so far I am in town for this weekend.
Let's do it on 17th June.
@Animesh-Ghosh Could you please share the venue details etc. with me?

**Comment by Animesh-Ghosh** [comment]
> Yeah, so far I am in town for this weekend.
> Let's do it on 17th June.
> @Animesh-Ghosh Could you please share the venue details etc. with me?

@DeepanshuA we'll be having the meetup at CSDS, Civil Lines and we'll have it from 1-5 PM.
