### ISSUE TITLE
Proposal — Developing & Testing Python Serverless applications using LocalStack!

### ISSUE THREAD

**Issue by HarshCasper** [pydelhi/talks#236]
### Title

Developing & Testing Python Serverless applications using LocalStack!

### Describe your Talk

LocalStack is a fully functional local AWS cloud stack that enables cloud applications & infrastructure to be developed entirely on your local machine. The session covers interactive live coding to showcase common scenarios and use cases to develop & test Python serverless applications, different settings for local debugging of Lambdas and containerized apps, and some advanced new features that can radically improve productivity and team collaboration patterns.

Agenda:

- Introduction to Serverless
- State of AWS Serverless Ecosystem
- Getting started with LocalStack
- Technical Demonstrations
- Collaboration patterns for Serverless
- Q&A

### Pre-requisites & reading material

Reading material:

- LocalStack: https://github.com/localstack/localstack
- Lambda: https://docs.localstack.cloud/user-guide/aws/lambda/
- Introduction to Serverless on AWS: https://aws.amazon.com/serverless/

Technical pre-requisites:

- Docker & `pip`
- [AWS CLI](https://pypi.org/project/awscli/)
- `curl` & `jq`

Intended audience: Beginners with an interest in AWS Cloud & Serverless 

### Time required for the talk

45 minutes

### Link to slides/demos

In progress

### About you

Hi — I am Harsh, an engineer working at LocalStack. Previously, I was a Google Summer of Code student developer at MetaCall, and a Google Season of Docs technical writer at moja global. I have worked at HackerRank, Quansight, and Red Hat, to name a few, and I am passionate about Web Engineering, Python, DevOps, and Cloud in general. I have spoken at EuroPython '21, PyCon India '21, and GitKon '22.

### Availability

30/06/2023 — 05/07/2023

### Any comments

I would be available for an offline talk in the above time frame because of a vacation visit. I would be happy to know the proposed dates, but I'm afraid that I might not be able to accommodate that :(

**Comment by HarshCasper** [comment]
@Animesh-Ghosh @akshayaurora Any updates on this?

**Comment by Animesh-Ghosh** [comment]
@HarshCasper we usually try to have meet-ups on the 3rd Saturday of the month. Would you be available in that timeframe the next month?

**Comment by HarshCasper** [comment]
@Animesh-Ghosh Unfortunately, no — I can do an online talk if that's an option. Please let me know about this. Thanks!

**Comment by pulsar17** [comment]
@HarshCasper closing this now. Feel free to create an issue again if you're available. This month's meetup will be on 15th of July.
As @Animesh-Ghosh mentioned, we have a meetup on every 3rd Saturday. So, you can open an issue for a future meetup.
