### ISSUE TITLE
Sanic's event loop: Under the hood

### ISSUE THREAD

**Issue by akshitadixit** [pydelhi/talks#237]
### Title

Sanic's event loop: Under the hood

### Describe your Talk

Sanic is a popular Python web framework that uses asynchronous programming to achieve high performance. Underneath the hood, Sanic relies on an event loop to manage asynchronous tasks efficiently. Understanding how Sanic's event loop works is critical for developers who want to build high-performance web applications using Sanic.

In this presentation, we will explore the inner workings of Sanic's event loop. We will begin by discussing the basics of asynchronous programming and how it differs from traditional synchronous programming. We will then delve into the details of Sanic's event loop, examining its architecture and how it manages tasks.

We will also cover how Sanic's event loop handles common scenarios, such as long-running tasks, blocking I/O, and CPU-bound tasks. We will discuss how to optimize performance by tuning the event loop's parameters and other strategies for improving performance.

By the end of this presentation, attendees will have a thorough understanding of how Sanic's event loop works and how to optimize their web applications for maximum performance.

### Pre-requisites & reading material

- Basic knowledge of Python programming language
- Familiarity with asynchronous programming concepts such as coroutines, event loops, and callbacks
- Understanding of web application development using Python

- Sanic documentation: https://sanic.readthedocs.io/en/latest/
- Asynchronous programming in Python: https://docs.python.org/3/library/asyncio.html

### Time required for the talk

40 mins

### About you

I'm working with Tata 1mg as a Backend Developer and we extensively use Sanic to power our microservices architecture that receives massive traffic each day. I am also working with Major League Hacking (MLH) as a Technical Program Associate in their Fellowship team where I facilitate the program for MLH Fellows. I am in my final year of engineering from IIIT Kalyani and have previously spoken at various places, list of which you'd find here: https://akshitadixit.github.io/#sessions

### Availability

20/05/2023 - 20/08/2023

### Any comments

This duration would be the most probable duration of me being in and around Delhi NCR

**Comment by Animesh-Ghosh** [comment]
Hey @akshitadixit, would you be available in Delhi on the 20th May, 2023?

**Comment by akshitadixit** [comment]
Hey @Animesh-Ghosh yes I will be.

**Comment by akshitadixit** [comment]
Hi @Animesh-Ghosh can we have more communication on the event so I can book my tickets accordingly?

**Comment by Animesh-Ghosh** [comment]
@akshitadixit just to be clear, this will be for a local meetup in Delhi. Also, you can share your Telegram username so that we could add you to the Telegram group. We can have the conversation there since it's closer to real time.

**Comment by akshitadixit** [comment]
@Animesh-Ghosh Here is my telegram: `@plastic96`
