### ISSUE TITLE
Proposal: Writing a Python Interpreter from scratch, in half an hour.

### ISSUE THREAD

**Issue by tusharsadhwani** [pydelhi/talks#239]
### Title

Writing a Python interpreter from scratch, in half an hour.

## Abstract

You use the Python interpreter every single day. It does a lot of things for you: checks that your code has valid syntax and is properly indented, imports modules from various locations, and runs your code instruction-by-instruction.

But if you've ever wondered how exactly it happens, this talk will teach you the entire process, by building a working python interpreter from scratch.

## Details

The plan is to write a really simple, but working Python interpreter that can run Python code, from scratch.

The concepts we'll be going through to build this interpreter:

- Parsing an indentation based language
- Why `Indent` and `Dedent` need to be tokens
- Writing a Recursive Descent parser
- Parsing literals: `int`s, strings, lists, dictionaries
- Parsing expressions
- Parsing function calls - `print("Hello world!")`
- Semantic analysis: removing invalid code
- A tree-walk interpreter
- Interpreting `print()` statements
- Running `import` statements
- File I/O: implementing `open()` calls
- Running `json.loads()` and `json.dumps()` on our hand-written interpreter

### Pre-requisites & reading material

The only pre-requisite is very basic knowledge of Python. Everything explained in the talk will be from the ground up, and it won't be using any fancy libraries.

### Time required for the talk

40 mins (30 for the talk, 10 for question/answers) 

### About you

I'm a Python programmer, author, technical reviewer and speaker.

Currently I'm employed as a Language Engineer at DeepSource, where I maintain their Python code analysis and Autofix stack. I've been working with Python's syntax trees, writing linters, building tools that parse code, etc. for over 2 years. I've also contributed a fair bit to popular Python linters, code formatters, type checkers, etc.

Twitter: [@sadhlife](https://twitter.com/sadhlife)

### Availability

July/August, 2023

**Comment by tusharsadhwani** [comment]
@Animesh-Ghosh I'll have to take a flight to delhi, I'm currently in bangalore. So most probably not.

**Comment by akshitadixit** [comment]
@tusharsadhwani love the topic tho <3

**Comment by pulsar17** [comment]
Hi @tusharsadhwani , would you be available on 17th June?

**Comment by tusharsadhwani** [comment]
@pulsar17 I'll have to take a flight to delhi, I'm currently in bangalore. So most probably not.

**Comment by tusharsadhwani** [comment]
I hope to give this talk in the August 5 conference though!

**Comment by ditsuke** [comment]
@pulsar17 since the PyDelhiConf is up on PaperCall, should we close this issue?

**Comment by pulsar17** [comment]
> @pulsar17 since the PyDelhiConf is up on PaperCall, should we close this issue?

The idea was that the speaker would present their talk to a smaller audience first. It would help them prepare their talk and allow us to worry about one less talk to arrange.
@ditsuke you can close this issue as the speaker is available only on conference dates

**Comment by ditsuke** [comment]
> > @pulsar17 since the PyDelhiConf is up on PaperCall, should we close this issue?
> 
> The idea was that the speaker would present their talk to a smaller audience first. It would help them prepare their talk and allow us to worry about one less talk to arrange.
> @ditsuke you can close this issue as the speaker is available only on conference dates

Ah, that makes sense. I don't have triage rights on this repository at the moment, maybe @Animesh-Ghosh can?
