### ISSUE TITLE
Write your own personal blog using Python 📝🐍

### ISSUE THREAD

**Issue by pulsar17** [pydelhi/talks#243]
### Title

Write your own personal blog using Python 📝🐍

### Describe your Talk

The talk will be about:
- Why a personal blog?
- Why Python? (Isn't it slow?)
- My own mods to the default setup
- My workflow on adding new articles
- Hosting considerations
- DNS, it's always DNS!

### Pre-requisites & reading material

None. This is a beginner friendly talk.

### Time required for the talk

30 mins

### About you

#pythonis❤️

- Generally excited about Python - the language and the surrounding community. I have some experience with Django but I love to use Python for everything :). Sometimes I also write Lua for a change.
- [Personal Blog](https://pulsar17.me/)
- git{[Hub](https://github.com/pulsar17), [Lab](https://gitlab.com/pulsar17)}
- pulsar17 on Telegram
- [@pulsar17@mastodon.social](https://mastodon.social/@pulsar17) on Mastodon
- [@realpulsar17](https://twitter.com/realpulsar17) on Twitter

### Availability

17/06/2023

**Comment by pulsar17** [comment]
@Animesh-Ghosh is this one of the 2 talks selected for 17 Jun?

**Comment by Animesh-Ghosh** [comment]
Yes, @pulsar17.
