### ISSUE TITLE
Talk: KerasNLP

### ISSUE THREAD

**Issue by shivance** [pydelhi/talks#244]
### Title

KerasNLP: Modular Design philosophy for LLMs

### Describe your Talk

KerasNLP, a natural language processing library by Tensorflow. This library is an extension of the core Keras API. workflows are built from modular components that have state-of-the-art preset weights and architectures when used out-of-the-box and are easily customizable when more control is needed.

The emphasis of this talk will be on 
1. API and keras-nlp offering for NLP workflows.
2. We'll dive into the basics of LLMs and learn how to design one with ease!

### Pre-requisites & reading material

1. Keras and Tensorflow
2. https://keras.io/guides/keras_nlp/getting_started/

### Time required for the talk

30 mins

### About you

Anshuman is a recent graduate from National Institute of Technology Warangal. He is a Google Summer of Code mentee at TensorFlow and is contributing to KerasNLP. He is 2xKaggle Master and has interned at Amazon and Bank of New York in past.

### Availability

15/07/2023

**Comment by Animesh-Ghosh** [comment]
@shivance are you available to deliver the talk on 15th July 2023 in Delhi?

**Comment by shivance** [comment]
@Animesh-Ghosh please keep it under consideration, I'm from Kanpur originally in process of making travel arrangements but I'll mostly be available! What's the location for talk anyway?

**Comment by Animesh-Ghosh** [comment]
@shivance it'll be in DU North campus, Conference Centre.

**Comment by pulsar17** [comment]
> @Animesh-Ghosh please keep it under consideration, I'm from Kanpur originally in process of making travel arrangements but I'll mostly be available! What's the location for talk anyway?

@shivance could you confirm by tomorrow noon whether you will be available or not. We are planning to announce the meetup tomorrow so we need the no. of speakers beforehand.

Also, please share your Telegram username so that I can send you the group link.(If you're not already part of the group, also please share your username)

**Comment by shivance** [comment]
Sorry I won't be able to make it this time!

**Comment by Animesh-Ghosh** [comment]
@shivance the meetup got rescheduled to the 22nd. Would you be available then?

**Comment by shivance** [comment]
I'm flying for a talk at TFUG Kolkata on 22
