### ISSUE TITLE
Introduction to computer vision

### ISSUE THREAD

**Issue by MurluKrishna4352** [pydelhi/talks#245]
### Title

Introduction to Computer Vision

### Describe your Talk

We would be going through the domain of computer vision in the session. The following things would be covered: 

- Introduction to Computer Vision
- Basics of Image Processing
- Image Filtering and Edge Detection
- Resources and Tools

### Time required for the talk

45 minutes to an hour

### About you

I'm Krishna Nagpal and I'm an AI enthusiast. 
You can find more about me here: https://www.linkedin.com/in/krishnanagpal

### Availability

15/7/23

**Comment by Animesh-Ghosh** [comment]
@MurluKrishna4352 are you available to give your talk on the 15th of July 2023 in Delhi?

**Comment by MurluKrishna4352** [comment]
Yes

**Comment by Animesh-Ghosh** [comment]
> Yes
> 

Great, @MurluKrishna4352! Could you also let me know about the following:

1. Are you part of the PyDelhi Telegram group? If yes, please share your username.
2. Do you have a preferred time slot? (The meetup timings are 1-5 pm, generally)

**Comment by MurluKrishna4352** [comment]
1. Yes, @helloworld001122
2. 1-5 is fine
