### ISSUE TITLE
Introduction to probabilistic programming with PyMC

### ISSUE THREAD

**Issue by 5hv5hvnk** [pydelhi/talks#246]
### Title

Introduction to probabilistic programming with PyMC

### Describe your Talk

We would go through basic understanding of use of probability for making predictions on data. Things that I will cover:

- Bayes Rule
- What is Dirichle's Prior?
- What is PyMC?
- Use PyMC to build a small probabilistic model.

### Time required for the talk

45 minutes - 1 hour (talk would be around 25-30 minutes assuming there will be questions regarding understanding conditional probability)

### About you

I am Shashank Kirtania, upcoming RA @ speech lab IITM. Previous works include working at PyMC last summer as GSoC mentee, ML intern at Wadhwani AI.

### Availability

15/07/2023

**Comment by Animesh-Ghosh** [comment]
@5hv5hvnk are you available to deliver your talk on 15th July 2023 in Delhi?

**Comment by 5hv5hvnk** [comment]
Yes I will be in Delhi.

**Comment by pulsar17** [comment]
> Yes I will be in Delhi.

Cool, a few questions.

1. Are you part of the PyDelhi Telegram group? If yes, please share your username.
2. Do you have a preferred time slot? (The meetup timings are 1-5 pm, generally)

**Comment by 5hv5hvnk** [comment]
@pulsar17 No I am not in the group my username is `shvshvnk`

**Comment by pulsar17** [comment]
Sent you the group link in DM

**Comment by 5hv5hvnk** [comment]
I won't be available to deliver the talk on 22nd for the talk.
