### ISSUE TITLE
To build a production-ready distributed task queue system with celery. 

### ISSUE THREAD

**Issue by vishrutkohli** [pydelhi/talks#247]
### Title

To build a production-ready distributed task queue system with celery. 

## Description

We hear a lot about queuing technologies like **Redis**, **RabbitMQ**, **Amazon Sqs**, etc but when it comes to building and maintaining a **consuming** and **publishing** mechanism for those queues it becomes a difficult and time-consuming task.
Whenever you are working with python and you hear distributed task queue management system first thing which comes to mind is **Celery** but making a production-ready which means Highly **efficient**, **Resilient**, **transparent**, and **scalable** setup with celery is a tricky business. In this talk, we will see how we can take advantage of Celery to build and manage our task queue distribution system with ease along with tips and tricks to find the perfect configuration for your celery at scale.

## Content of talks(Outline):

- **Introduction** to talk and speaker? - 2 min
    1. About myself
    2. What do i do at Grofers?
    3. Introduction to the Talk.

---

- What are **task queues** and why we need them? - 4 min
    1. A real Life problem we face.
    2. Its Solution using task queues.
    3. Explaining task queues.

---

- What is **Celery** and why we need it? - 2 min
    1. Why celery is useful.
    2. Talking about the keywords we are going to use in the talk.
    3. Explaining task queues.

---

- **Building** a distributed task queueing system. -5 min
    1. Starting off with a real-life problem.
    2. Talking about the approach to start building our system.
    3. Talking about pipelines and how pipelines are better.
    4. Which broker to choose?
    5. Code samples.

---

- **Tuning** a distributed task queueing system for better efficiency. -5 min
    1. Does the batching of tasks help our use case?
    2. Why benchmarking after each optimization is important.
    3. What are IO-bound and CPU-Bound tasks and why we need to split them?
    4. When to use -Ofair optimization to maximize performance.
    5. When to use prefetch multiplier to maximize performance.
    6. Store task results in the celery backend only if you need them.

---

- Adding **resiliency** to the system -3 min
    1. Talking about the basic auto-retry feature of celery.
    2. Talking about exponential backoff and when do we need them.
    3. Adding max retries for circuit breaking.
    4. using acks_late= true to handle worker failures.
    5. Using retry jitter to add randomness to retries.
    6. Using a DLQ to record circuit breaker failures.

---

- What to do in times of **SOS**? - 2 min
    1. Starting with checking CPU and memory usages and see what is causing the failure and seeing horizontally scaling or vertically scaling can help or not.
    2. using max tasks per child and max memory per child when you suspect a memory leak.

---

- **Monitoring** the system we built. - 2 min
    1. Talking about how flower helps in monitoring our celery setup and how easy it is to set up.
    2. Using RabbitMQ admin panel for monitoring queues.

---

- Questions - 5 min

---

- Bad Jokes - All the time

---

### Pre-requisites & reading material

Prerequisites:

- Basic knowledge of python.
- Basic knowledge of web development.
- know about or used a little celery before.
- Good sense of Humour and love for Gifs.

### Time required for the talk

30 min

### About you

I am Vishrut, a 26-year-old Senior Software Engineer at MilkBasket (India's largest and most sustainable grocery delivery service), leading consumer applications and platform. Prior to this I led the last mile team at Blinkit(India's largest quick commerce service) . Python has been my primary tech stack since i started coding and this journey started from building a data server hosted on my raspberry pi to building a high performant delivery partner allocation system for our 10 min delivery service which handles more than 100k orders/ min flawlessly. Apart from this, I was also a METI Japan internship scholar and have won various hackathons such as SBI National Hackathon , Shadowfax Leap Hackathon, and was the world finalist for United by HCL Hackathon held in Manchester.

### Availability

22/07/23 (or any other day)

**Comment by pulsar17** [comment]
Hi @vishrutkohli , a few questions:

1. Are you part of the Telegram group? (If no, please share your username. If yes, please share your username)
2. Is there a particular time slot you have in your mind? (The meetup timings are 1-5 pm generally)

**Comment by Animesh-Ghosh** [comment]
@vishrutkohli hey, just pinging since we wanted to finalize the talks.

**Comment by vishrutkohli** [comment]
Hi  sorry for the late reply. 
No i am not part of the telegram group . here is my username can you please add me -- lazycoder7

i am okay with any timing but i prefer something which is after 2.

**Comment by Animesh-Ghosh** [comment]
Hi @vishrutkohli, yup this is for the 22nd July meetup that'll happen tomorrow.
Sure we can schedule your talk after 2 PM.
Can we schedule this for tomorrow then @vishrutkohli?

**Comment by vishrutkohli** [comment]
Hi yes anytime after 2 works . I am still not able to find myself in the group . Can you ping me
Once
