### ISSUE TITLE
Proposal: Journey to LFX mentorship

### ISSUE THREAD

**Issue by AkankshaAI** [pydelhi/talks#250]
### Title
Journey to LFX Mentorship

**Describe your Talk**
In the talk I unveil the secrets to becoming a successful LFX Mentee under [The Linux Foundation](https://www.linkedin.com/company/the-linux-foundation/) . Discover how to land high-paying part-time internships while still in initial or after years of college through the power of Open Source. Plus, get an inside look at my enriching 6-month internship journey at [Hyperledger Foundation](https://www.linkedin.com/company/hyperledger-project/) as an LFX Mentee '23.

The following topics will be covered-

- Introduction to Open Source and Open source programs
- LFX Mentorship Portal - Application Process
- Project Hunt , Finding Organisation
- Prerequisites and requirements
- Tips for Resume and Cover letter
- Secrets to the best application
- Resources 

**Pre-requisites** & reading material

**Time required for the talk**
35 minutes

**Link to slides/demos**
No response

**About you**
LFX mentee'23 @Hyperledger | Co-founder HEALTHub | GHC Scholar'23  | Mentor GSSoC'23 & GDSC | Vice Chairperson IEEE IGDTUW | Winner Cisco thingQbator Cohort 5 | Awarded as Outstanding Mentor by Delhi Goverment | AI ML enthusiast | 

**Availability**
21/10/2023

**Any comments**
No response

**Comment by deedee3** [comment]
Wow, looking forward to it.

**Comment by AkankshaAI** [comment]
> Wow, looking forward to it.

Will you we contacting for further details?

**Comment by deedee3** [comment]
Yes, please.

Feel free to contact me. If there is a slack community for pydelhi please
add me to it. We can chat there

**Comment by deedee3** [comment]
Hello, can I get your email or any contact service. I can't wait until the issue gets addressed, I want to proactively get into LFX programs, your guidance would be invaluable.

**Comment by Animesh-Ghosh** [comment]
Hey @AkankshaAI, are you available to deliver your talk on 21st October, 2023?

**Comment by AkankshaAI** [comment]
> Hey @AkankshaAI, are you available to deliver your talk on 21st October, 2023?

Yes , I am available. Please let me know more details

**Comment by AkankshaAI** [comment]
> Hello, can I get your email or any contact service. I can't wait until the issue gets addressed, I want to proactively get into LFX programs, your guidance would be invaluable.
> 
> Or you can ping me to initiate the conversation @ [kushal.bhandari.3114@gmail.com](mailto:kushal.bhandari.3114@gmail.com)
> 
> Thanks!

You can ping me on linkedin 
https://www.linkedin.com/in/akanksha-rani-775355202

**Comment by AkankshaAI** [comment]
@Animesh-Ghosh Also, if details regarding presentation slides and session agenda are required , please let me know . I'll share everything in format.

**Comment by Animesh-Ghosh** [comment]
@AkankshaAI the venue is CSDS, Civil Lines and timings will be 1-5 PM for the whole meetup. You'll get 30-45 minutes for your talk.

**Comment by AkankshaAI** [comment]
> @AkankshaAI the venue is CSDS, Civil Lines and timings will be 1-5 PM for the whole meetup. You'll get 30-45 minutes for your talk.

Alright, I confirm for taking the session, I'll be there. Some doubts I had : What will be the target audience and by when will be my exact slot timings confirmed . And lastly, should I share presentation here itself in a day or two for review. Please clear these doubts and let me know what all details are required from my side.

Regards,
Akanksha Rani

**Comment by Animesh-Ghosh** [comment]
@AkankshaAI [this](https://github.com/pydelhi/talks/issues/251#issuecomment-1763423560) should answer your question about the demographics.
If you had created the issue following the template we had for you, we had asked for the slides there. But it's fine, since we ask those for reference for anyone who might be a potential future speaker, or just for our reference. Feel free to add the link to the slides in the original comment.
Thanks!

**Comment by AkankshaAI** [comment]
@Animesh-Ghosh Thankyou so much , all my doubts are cleared. I'll share the slides and details in issue format by Pydelhi which will make work easier for you maximum by 18th October,23. For any further information, let me know.

Regards,
Akanksha Rani

**Comment by Animesh-Ghosh** [comment]
Just to be clear, please just update this issue's original comment @AkankshaAI.

**Comment by AkankshaAI** [comment]
@Animesh-Ghosh Alright, I'll have to update
https://github.com/pydelhi/talks/issues/250#issue-1838058842
This comment right

**Comment by pulsar17** [comment]
@AkankshaAI please also drop your telegram username here so that one of us can contact you on the meetup day

**Comment by AkankshaAI** [comment]
> @AkankshaAI please also drop your telegram username here so that one of us can contact you on the meetup day

Hey,
You can ping me on Telegram at +91 8800959923 . Username : Akanksha 
I am already there in Pydelhi telegram too.

**Comment by pulsar17** [comment]
@AkankshaAI it's probably better to remove your contact details from the comment above since this is a public repo -  https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#redacting-sensitive-information

**Comment by AkankshaAI** [comment]
> @AkankshaAI it's probably better to remove your contact details from the comment above since this is a public repo - https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#redacting-sensitive-information

Sure sure , Thankyou for letting me know
