### ISSUE TITLE
Introduction to the World of Research and Research Papers

### ISSUE THREAD

**Issue by 072arushi** [pydelhi/talks#251]
### Title

Introduction to the World of Research and Research Papers

### Describe your Talk

Researching topics and fields is very important and helpful in education. I have worked extensively in the field of Machine Learning and Deep learning and wrote 4 Conference papers and one journal paper and I am excited to share my journey, motivate the students and help them to start their journey.

The following topics will be covered-
1. To understand any domain and dive deep into it, research is an indispensable part. It helps us understand topics more clearly and get to know the work done by previous authors and researchers, and how architecture can be molded in a certain way. 
2. Need to write a research paper.
3. How to start with your first research paper.
4. Things to keep in mind while drafting a paper.
5. Know more about conferences and journals.
6. How to present a paper at a conference.
7. Preventing plagiarism

### Pre-requisites & reading material

https://drive.google.com/file/d/1Eub_JnSAlikDk3kHXK-oUQvye3nE8ZIi/view?usp=sharing

I presented this talk at PyDelhi Conference'23

### Time required for the talk

30

### About you

Product Intern @Adobe | AWS CLoud Club Captain | Mentor @GSSoC'23 | Management Head @tnp | Research Intern @ IGDTUW | Technical Head - Senior executive team @IEEE

### Availability

20/10/2023

**Comment by Animesh-Ghosh** [comment]
Hi @072arushi, are you available to give your talk on 21st October, 2023?

**Comment by 072arushi** [comment]
Hi
Thank you for your response
Will it be an online event or offline?
Also could you tell more about the audience. And in case an online event,
could you please share the location as well.

Regards

**Comment by Animesh-Ghosh** [comment]
@072arushi it'll be an offline event.
The audience will consist of students and professionals. Maybe some people from academia.

Hope that answers your questions!

**Comment by 072arushi** [comment]
HiiCould you please mention the venue as well? RegardsArushi From: MaDDogxSent: Sunday, October 15, 2023 8:55 PMTo: pydelhi/talksCc: arushi_garg; MentionSubject: Re: [pydelhi/talks] Introduction to the World of Research and Research Papers (Issue ***@***.*** it'll be an offline event.The audience will consist of students and professionals. Maybe some people from academia.Hope that answers your questions!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Animesh-Ghosh** [comment]
@072arushi should I take it as a yes?

**Comment by 072arushi** [comment]
Yes
I’ll be there. Thanks for considering my talk. Please do let me know in
case any changes need to be made in the presentation.

Regards
Arushi

**Comment by 072arushi** [comment]
@Animesh-Ghosh It'd be great if you could confirm the timings and along with that please do mention if PyDelhi needs the presentation in some specific format.

**Comment by 072arushi** [comment]
And also please mention, how much time will be given to me for presentation and then the QnA, if any @Animesh-Ghosh

**Comment by Animesh-Ghosh** [comment]
@072arushi [this](https://github.com/pydelhi/talks/issues/250#issuecomment-1764227302) should answer both your questions.

**Comment by 072arushi** [comment]
Thanks @Animesh-Ghosh
