### ISSUE TITLE
Introduction to AWS Lambda & AWS API Gateway 

### ISSUE THREAD

**Issue by kybrdbnd** [pydelhi/talks#253]
### Title

Introduction to AWS Lambda & AWS API Gateway 

### Describe your Talk

In this talk we will walkthrough about AWS Lambda, i.e What is AWS Lambda? How to write lambda functions and cover its deployment strategy. We will also cover how to manage 3rd party dependencies in AWS Lambda using Lambda Layer. We will close the talk with a sample application (Basic CRUD) made using AWS Lambda + AWS DynamoDB + AWS API Gateway

### Pre-requisites & reading material

Basic understanding of VPC (Virtual Private Cloud) and python language.

### Time required for the talk

90 mins

### About you

Myself Pranav Puri with 6 years of working IT experience. Currently working as a Consultant in Big 4. Having expertise in devOps tools like GitHub Actions, Jenkins and cloud providers like AWS, Azure. 

### Availability

21/10/2023

### Any comments

Kinda flexible with the days, only not available from 18th Nov - 26th Nov

**Comment by Animesh-Ghosh** [comment]
Hi @kybrdbnd, are you available to give your talk on 21st October, 2023?

**Comment by kybrdbnd** [comment]
> Hi @kybrdbnd, are you available to give your talk on 21st October, 2023?

Yeah sure! Happy to give

**Comment by pulsar17** [comment]
90 mins is long :), @kybrdbnd any chance you could squeeze the talk in a 30 min time slot?

Or I might be misinterpreting this as a talk, do you intend to give it as a workshop?

(Please also drop your telegram username so that one of us can contact you on the meetup day)

**Comment by pulsar17** [comment]
Just saw @Animesh-Ghosh replied to you on Telegram, we can schedule this for the next meetup. Apologies @kybrdbnd

**Comment by Animesh-Ghosh** [comment]
@kybrdbnd is 18th November 2023 doable for you?

**Comment by kybrdbnd** [comment]
hi @Animesh-Ghosh , works for me, It will be a 1 hour talk

**Comment by pulsar17** [comment]
Closing this as this talk has been delivered. Thanks @kybrdbnd !
