### ISSUE TITLE
Microservices to behave like Monolithic - A use case

### ISSUE THREAD

**Issue by akhilgarg** [pydelhi/talks#254]
### Title

Microservices to behave like Monolithic - A use case

### Describe your Talk

This is about a use case where, a software design having multiple microservices having their separate databases, requires a search over all the data spread across multiple such databases. And as we couldn't apply join to form one such query.
We ended up with aggregating all real time data into one index in elastic search.
And this wasn't easy and straight forward.
While we were quite lucky to have elasticsearchdsl library to sync data from each microservices to an individual separate indexes however, forming a Global index and updating it in real time from from these individual index involved multiple technology and concepts like Django Signals, Message Queue, relational database to store a MetaData to be used to identify which needs to be changed and a listener code to update this Global index.

In this talk, we will see this use case and a solution architecture of such a problem. And we'll discuss each component role to solve this problem.

### Pre-requisites & reading material

Django
Python
Django Signals
Message queue (any)
AWS lambda (optional)
A little patience to understand the use case.
A little more patience to understand the solution.

### Time required for the talk

30-45 min.

### About you

I'm(Akhil Garg) currently working as a Lead Software Engineer in EPAM Systems, Delhi NCR.
In Epam System, I've provided 2 talks so far and a blog. Talks were related to GPg keys for encryption and Data comparison using Pandas.
In industry, I've spent around a decade working on Python mainly but other tech as well like database, message queue, cloud practice etc. 
I've been part of organisations like Greyorange robotics, Xebia, Nagarro, Innovaccer and MTree in the past.
I'm also associated with NITI Ayog in its Atal Innovation Mission as a Mentor of Change since last couple of many years. 

### Availability

28/10/2023

### Any comments

If date given by me does not suit to community then please confirm with me for another date as well.

**Comment by kybrdbnd** [comment]
interested for this one, we are using opensearch in our project. Wanna have a discussion with you if got a chance

**Comment by Animesh-Ghosh** [comment]
Hi @akhilgarg, are you available to give your talk on 21st October 2023?

**Comment by akhilgarg** [comment]
> Hi @akhilgarg, are you available to give your talk on 21st October 2023?

Hi @Animesh-Ghosh ,on 21st I'm not available.

**Comment by Animesh-Ghosh** [comment]
@akhilgarg is 18th November 2023 doable for you?

**Comment by akhilgarg** [comment]
Hi,
Yes, I can make it. What would be the venue??

**Comment by akhilgarg** [comment]
Hi @Animesh-Ghosh , I'm available to present this topic.

**Comment by Animesh-Ghosh** [comment]
Yup @akhilgarg, I saw your message.

> Hi, Yes, I can make it. What would be the venue??

Venue is TBD.

**Comment by pulsar17** [comment]
@akhilgarg confirming your talk. Any particular time slot you have in mind? (meetup timings will probably be 1pm-5pm)
Also please drop your Telegram username so that we can contact you on the meetup day.

**Comment by akhilgarg** [comment]
Hi Ishan,
Thanks for the confirmation and for shortlisting my talk topic.
Please find my telegram username - akhil_garg
No specific timing on mind but I'll appreciate whenever timing is decided
for my talk please convey to me so I can plan the day accordingly.

Thanks,
Akhil Garg
