### ISSUE TITLE
Hands On Django for Web Dev

### ISSUE THREAD

**Issue by engagepy** [pydelhi/talks#255]
### Title

Building Web Apps With Django

### Describe your Talk

Hands-On:

- `pyenv` 
- `venv`
- `django`
- `django-allauth`
- `bootstrap template integration`
- `SMTP mail setup`

Discussion:

- `tenants`
- `cache`
- `django-restframework`

### Pre-requisites & reading material

        Perusing through these can certain help ! 
        
        - https://docs.djangoproject.com/en/4.2/intro/tutorial01/
        - https://www.django-rest-framework.org/

### Time required for the talk

60 minutes

#### Technologies that I work with:

	- Python
	- JavaScript
	- Django
	- React
	- PostgreSQL
	- AWS
	- FastAPI
	
	
#### Projects Deployed As A Team

	- Training ML Models
	- AI Enabled BI Tools
	- OpenAI APIs
	- OpenSource

### Availability

Available < 25/10/23

**Comment by Animesh-Ghosh** [comment]
Hi @engagepy, are you available to deliver your talk on 21st October, 2023?

**Comment by engagepy** [comment]
Yes

**Comment by pulsar17** [comment]
60 mins is long, @engagepy  can you squeeze this in a 30 min time slot?

**Comment by pulsar17** [comment]
Seems like we have time, instead of the whole 60 mins, you could do 25 mins + 5 mins break + 30 mins. _Just a suggestion_
