### ISSUE TITLE
The Hitchhiker's Guide to Sustainability with Free Software

### ISSUE THREAD

**Issue by 0xquark** [pydelhi/talks#256]
### Title

The Hitchhiker's Guide to Sustainability with Free Software

### Describe your Talk

In this talk I will provide an overview of the environmental harm driven by software and how to design a sustainable software. I will link the inherent values that come with a Free & Open Source Software to sustainable software design. Finally, I will provide an overview of the work of the KDE Eco project and the sustainability goals of KDE.
P.S - I'll also share a sneak peak of a python tool i wrote in order to streamline the energy measurement process

### Pre-requisites & reading material

None

### Time required for the talk

25-30 Mins

### About you

Karanjot Singh is a Core Contributor of the KDE Eco Project. He's been involved in different open source programs, including Google Summer of Code and Linux Foundation Mentorship. He's passionate about the KDE Eco Project because it aims to make Free Software more sustainable during its development and use.

### Availability

07/11/2023

### Any comments

I can't speak at the October meetup because I have a hectic schedule this month, but I'd be happy to present at the next PyDelhi Meetup instead.

**Comment by Animesh-Ghosh** [comment]
@0xquark are you available on 18th November 2023 to deliver your talk?

**Comment by 0xquark** [comment]
Yes!

> @0xquark are you available on 18th November 2023 to deliver your talk?

**Comment by pulsar17** [comment]
@0xquark confirming your talk. Any particular time slot you have in mind? (meetup timings will probably be 1pm-5pm)
Also please drop your Telegram username so that we can contact you on the meetup day.

**Comment by 0xquark** [comment]
3:00 PM sounds good to me.
Telegram username - @DrQuark
Is the venue for the meetup final?
