### ISSUE TITLE
Python Type Annotations

### ISSUE THREAD

**Issue by kybrdbnd** [pydelhi/talks#257]
### Title

Python Type Annotations

### Describe your Talk

In this talk we talk about the python type annotations which are introduced in python3.7+. Run a case study why adding typing annotations to functions/methods are good thing.

### Pre-requisites & reading material

Basic Python understanding

### Time required for the talk

30 mins

### About you

Myself Pranav Puri with 6 years of working IT experience. Currently working as a Consultant at Big 4. Having expertise in devOps tools like GitHub Actions, Jenkins and cloud providers like AWS, Azure.

### Availability

All weekends mainly

**Comment by pulsar17** [comment]
Hi @kybrdbnd  will you be available to give the talk on January 20, 2024 (3rd Saturday)?

**Comment by pulsar17** [comment]
Also, you have 2 proposals open, if you do plan to give a talk, please let me know which one here as well.

**Comment by kybrdbnd** [comment]
hi @pulsar17, unfortunately I won't be available on 20th January.

**Comment by Animesh-Ghosh** [comment]
Thanks @kybrdbnd for the talk!
