### ISSUE TITLE
Create your own Python Library

### ISSUE THREAD

**Issue by kybrdbnd** [pydelhi/talks#258]
### Title

Create your own Python Library

### Describe your Talk

In this talk, we will walk through how to create your own python library and what are its pros and cons. We will also talk about version control of the library.

### Pre-requisites & reading material

Basic Python understanding, hands on with functions / classes.

### Time required for the talk

30 mins

### About you

Myself Pranav Puri with 6 years of working IT experience. Currently working as a Consultant at Big 4. Having expertise in devOps tools like GitHub Actions, Jenkins and cloud providers like AWS, Azure.

### Availability

Most weekends

### Any comments

Having knowledge of __init__.py is a plus.

**Comment by Animesh-Ghosh** [comment]
Hey @kybrdbnd would you be available to deliver your talk on the 20th of January, 2024?

**Comment by Animesh-Ghosh** [comment]
@kybrdbnd available to deliver this talk on the 16th of March?

**Comment by kybrdbnd** [comment]
@Animesh-Ghosh Yes i am

**Comment by pulsar17** [comment]
Hey @kybrdbnd I know you've provided some of this above but could you please mention the following things:

- Designation and Company
- Talk topic and description
- Brief bio and headshot

You can add the details here or send them to me on Telegram whichever is convenient.

**Comment by kybrdbnd** [comment]
hi @pulsar17 , please find the details as follows:
**Designation and Company:** Consultant at KPMG
**Talk topic and description:** Create your own Python Library. In this talk, we will walk through how to create your own python library and what are its pros and cons. We will also talk about version control of the library.
**Brief bio and headshot**: Having 6 years of working IT experience with expertise in devOps tools like GitHub Actions, Jenkins and cloud providers like AWS, Azure. 8+ years of working in Python Techstack. Hands-On experience with frameworks like Flask, ReactJS with end to end deployment.

For the headshots you are take pic from my GitHub/linkedin profile

**Comment by pulsar17** [comment]
@kybrdbnd are you available to give this talk on 20/04/2024 (3rd Saturday)?

**Comment by kybrdbnd** [comment]
@pulsar17 yeah sure

**Comment by pulsar17** [comment]
Thanks for giving the talk @kybrdbnd !
