### ISSUE TITLE
Future of devops and cloud

### ISSUE THREAD

**Issue by sambhavsaxena** [pydelhi/talks#261]
### Title

Future of devops and cloud

### Describe your Talk

I will be speaking about how things scale on industry level, and what makes devops come into play when it comes to terms like scalability and availability. What all things do engineers need to keep in mind, and what makes product widely available, tradeoffs of technologies and their threshold points, lot more about cloud and its growing demand.

### Pre-requisites & reading material

Basic knowledge of how things work in the back-end.

### Time required for the talk

20-30 mins

### Link to slides/demos

[canva slides](https://www.canva.com/design/DAF2ClCw4S8/hhhjLydt-ivHDxEYCdfQtw/edit?utm_content=DAF2ClCw4S8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

### About you

I'm a CS undergrad of batch 24, previously interned at a few startups, founder of an open source community in my university with over 1k+ members across platforms, recently got into backend services and devops.

[Twitter](https://twitter.com/_sambhavsaxena)
[LinkedIn](https://www.linkedin.com/in/sambhavsaxena/)

### Availability

24/12/2023

**Comment by Animesh-Ghosh** [comment]
Hi @sambhavsaxena, went through the slides. Just wondering how is this related to Python?

**Comment by sambhavsaxena** [comment]
oh it not, i went through other accepted issues which seem to be not related to python either so, thanks for clarifying.

**Comment by Animesh-Ghosh** [comment]
If you can update your presentation to talk about how Python fits into DevOps and Cloud, you can present it without any issues @sambhavsaxena.

**Comment by sambhavsaxena** [comment]
alright give me some time, will get back in a day or two:)

**Comment by sambhavsaxena** [comment]
@pulsar17 I don't think I'll be able to join in for this session, but I assume that they happen every month or so? I would love to reach out back to you when things are more aligned for me.

**Comment by pulsar17** [comment]
Closing this for now, feel free to reopen based on your availability. We generally have meetups every 3rd Saturday.
