### ISSUE TITLE
An Introduction to Hasura - Build APIs faster

### ISSUE THREAD

**Issue by akhilgarg** [pydelhi/talks#262]
### Title

An Introduction to Hasura - Build APIs faster

### Describe your Talk

In this talk, we will see Hasura, a framework to build APIs automatically to share data in Database.
Hasura in wrapper around GraphQL server. With Hasura no need to write extra code to create GraphQL server and any REST API to share data.
Agenda-
1. An Introduction to Hasura.
2. A little intro to GraphQL.
3. Demo to showcase, hasura installation using Docker.
4. Database connectivity and see hasura queries on console.
5. REST APIs to get hasura query result.
6. Discussion and practical usage of the framework.

### Pre-requisites & reading material

Should at least know about Database, REST APIs, a little info about GraphQL.

### Time required for the talk

40 minutes

### About you

Speaker is Akhil Garg, currently associated with EPAM Systems as Lead Software Engineer and having 10+ years of experience in industry. He holds Btech computer science degree along with Post graduate diploma from CDAC (Centre for development of Advanced Computing). He has delivered various talks in EPAM under TecToniques community( a part of Python Practice in EPAM) as well as in PyDelhi monthly meet ups.
He also leads TecToniques community in EPAM. Apart from this, Akhil is also associated with NITI Ayog in its Atal Innovation Mission (AIM) as a Mentor Of Change where he is assigned to 1-2 schools in Delhi NCR to help/mentor/motivate students.
He also conducted a session in a govt school under EPAM CSR programme to motivate school students and to ignite the lamp of innovation in them.

### Availability

16/12/2023

**Comment by pulsar17** [comment]
Closing this as this talk has been delivered. Thanks @akhilgarg !
