### ISSUE TITLE
From Campus to Company: Building Your Startup While in College

### ISSUE THREAD

**Issue by echiotech** [pydelhi/talks#263]
### Title

From Campus to Company: Building Your Startup While in College

### Describe your Talk

During this discussion, we will explore key aspects of how students can establish their startups while in college. We'll delve into various important points, including the following:

- Key Steps to Building a Successful Student Entrepreneurship Venture
- Leveraging College Resources for Entrepreneurial Initiatives
- How can your technical proficiency empower you to create a successful Minimum Viable Product (MVP)?
- When should you initiate the search for your startup team members and why?
- What steps can you take to address challenges and setbacks if your startup venture encounters failure?

### Pre-requisites & reading material

None

### Time required for the talk

25 min

### About you

I'm Pankaj, Co-founder and CTO of Echio. Originating in college, I founded our tech-driven venture. Excitingly, our company has now achieved a valuation of 10 Crores. Currently, at Echio, I lead our technical pursuits. Drawing on my experience as a machine learning engineer, I dedicated two impactful years to freelancing on diverse projects.

### Availability

16/12/2023

### Any comments

I have some flexibility with my schedule for the upcoming days, except for the period until November 11th when I am not available.

**Comment by Animesh-Ghosh** [comment]
Hey @echiotech, just wanted to confirm your availability for 16th December 2023, for delivering your talk.

**Comment by echiotech** [comment]
yes, I'm available on 16th December

**Comment by Animesh-Ghosh** [comment]
@echiotech could you share a LinkedIn and/or Twitter so that we link to it on the Meetup page?

**Comment by echiotech** [comment]
Sure here is my twitter and linkedin accounts. 
LinkedIn:- https://www.linkedin.com/in/pankajrajput0312
Twitter:-https://x.com/Pankajrajput312

**Comment by pulsar17** [comment]
Closing this as this talk has been delivered. Thanks @echiotech  !
