### ISSUE TITLE
Time Series Classification - How to and how not to do, that is the question.

### ISSUE THREAD

**Issue by malayajac** [pydelhi/talks#265]
### Title

Time Series Classification - How to and how not to do, that is the question.

### Describe your Talk

In this talk, we will learn about Time Series Classification, and how it's different from your usual classification tasks in Machine Learning. What's special about the ordered nature of time series? When do we need to classify time series?
We will carry out a demo on jupyter notebooks. Open source python libraries that we will use (among others) sklearn and sktime.

Agenda:
1. A bit about Classification in Machine Learning
2. A bit about Time Series
3. Time Series Classification
4. How to not do?
5. How to do?

### Pre-requisites & reading material

Python and some machine learning basics. But fret not, most of the basics required will be covered in the talk.

### Time required for the talk

20-30 min

### About you

Malayaja Chutani is currently a Data Science and Scientific Software Consultant for Soft Circuits, where she has been playing around with time series and learning robot operating systems. Before that, she was working on projects based in NLP, knowledge graphs, and causal inference at MathCo. In a past life, she was in academia, working on complex networks, dynamical systems, and science communication at IIT Madras.

### Availability

16/12/2023

**Comment by pulsar17** [comment]
Hi @malayajac, will you be available to give the talk on 21st January, 2024?

**Comment by Animesh-Ghosh** [comment]
@malayajac this'll be an in-person meetup in Delhi. Would you be available to deliver the talk during the date shared by @pulsar17 above?

**Comment by malayajac** [comment]
@pulsar17 @Animesh-Ghosh Unfortunately, I will not be able to give the talk on 20th Jan 2024.

**Comment by pulsar17** [comment]
@malayajac by any chance are you available to give this talk on this 17th?

**Comment by Animesh-Ghosh** [comment]
Closing this for now.
