### ISSUE TITLE
Community partnership with PyDelhi

### ISSUE THREAD

**Issue by crac-learning** [pydelhi/talks#267]
### Title

Community partnership with PyDelhi

### Describe your Talk

I hope this email finds you well. My name is Swati Laxmi, the organizer at CRAC Learning, a dynamic and growing community dedicated to fostering cybersecurity education and awareness. We are thrilled to extend an invitation to your esteemed company to join us as a partner for our upcoming annual cybersecurity conference CRACCON in January 2024.

About CRAC Learning:

At CRAC Learning Foundation (non-profit), New Delhi, our mission is to create a platform that not only educates but also inspires the next generation of cybersecurity enthusiasts. Our annual conference has grown in prominence, and we believe that your company's involvement will play a crucial role in making this event a resounding success.

1. Active engagements with 1000+ students across India
2. Experienced core team with expertise from top companies such as Amazon, Microsoft, AWS, Apple, KPMG, EY, and more
3. Previous partnerships with renowned communities like Seasides, IEEE, OWASP, HackersVilla, SAS, and IIKON.

Event Highlights:

Date: January 27-28, 2024

Venue: India International Centre, New Delhi

Reach: 500+ Attendees Anticipated

Conference Activities:

Cyber Insights Symposium

Executive Conclave

Career fair offering resume reviews and live interview

Innovation Showcase - research and automation

Security Village Experience - lock-picking, ICS, CTF, Hardware

Ask the Experts Session with CXOs, Partners and Directors

Live Cyber Challenge Arena - Offline CTF

Hands-on workshop on popular demand - IoT, Bug Bounty and more

Tech Talks Extravaganza

Industry Integration Forum & Many more.

Why Partner with CRAC Learning:

Networking Opportunities: Gather potential clients from industry, Connect with industry leaders, cybersecurity experts, and like-minded professionals fostering valuable networking opportunities for your company.

Access to Talent Pool: Gain exclusive access to a pool of skilled and motivated students passionate about cybersecurity, providing your company with potential future hires and interns.

Brand Visibility Across Platforms: Benefit from extensive brand visibility not only during the conference but also across our online platforms, social media channels, and promotional materials leading up to the event.

Customizable Sponsorship Packages: Enjoy the flexibility of customizable sponsorship packages tailored to meet your specific marketing objectives and budget constraints.

Recognition as a Thought Leader: Position your company as a thought leader in the cybersecurity domain by participating in expert talks, panel discussions, and workshops, showcasing your expertise and commitment to the industry.

Diversity and Inclusion: CRAC Learning promotes diversity and inclusion in the cybersecurity field. By partnering with us, your company demonstrates a commitment to fostering a diverse and inclusive industry.

Exclusive Content Creation Opportunities: Collaborate with us on creating exclusive content, such as blog posts, articles, or videos, showcasing your company's thought leadership and commitment to cybersecurity education.

Post-Event Coverage and Analytics: Receive comprehensive post-event coverage, including analytics and reports, to assess the impact of your sponsorship and measure your brand's reach and engagement.

Collaboration:

We are seeking support for various aspects of the event, including Venue, Food, Goodie bags, CTF, Badges, Speakers' hospitality, Talks, and Workshop sponsors. A detailed prospectus is attached for your perusal.

Next Steps:

We genuinely appreciate your consideration of our partnership proposal. For any clarifications or to discuss specific details, please feel free to contact us at [admin@crac-learning.com](mailto:admin@crac-learning.com).

Explore more about CRAC Learning on our website:[ CRAC Learning Website](https://www.crac-learning.com/)

We believe that your support will not only contribute to the success of our event but also empower the next generation of cybersecurity professionals. Thank you for your time, and we eagerly await the possibility of collaborating with your esteemed company.

 

Best Regards,

Swati Laxmi

+91 7011197516

+91 74289 73398
CRAC Learning Foundation.

### Time required for the talk

3 hours

### About you

About CRAC Learning:

At CRAC Learning Foundation (non-profit), New Delhi, our mission is to create a platform that not only educates but also inspires the next generation of cybersecurity enthusiasts. Our annual conference has grown in prominence, and we believe that your company's involvement will play a crucial role in making this event a resounding success.

1. Active engagements with 1000+ students across India
2. Experienced core team with expertise from top companies such as Amazon, Microsoft, AWS, Apple, KPMG, EY, and more
3. Previous partnerships with renowned communities like Seasides, IEEE, OWASP, HackersVilla, SAS, and IIKON.

### Availability

27/01/2024

**Comment by crac-learning** [comment]
Dear PyDelhi team,
I trust this email finds you in great spirits. My name is Swati Laxmi, founder at CRAC Learning. We are reaching out with an exciting collaboration opportunity for our upcoming annual event, CRACCON Cybersecurity Summit 2024, scheduled for January 27-28, 2024, in New Delhi.

**Why Collaborate with CRACCON?**
Diverse audience: CISOs, leaders, industry experts, students
CXO Panel: Hear directly from CISOs
Ideathon: Cybersecurity innovations and research
Program: Seminars, career fair, hiring, internship, resume review, workshops, hacking village

**For PyDelhi**
- Twice a week social media posts about CRACCON until the conference.
- Purchase 3 corporate tickets for CRACCon and giveaway to your community.

**For CRAC** 
- 15% coupon code for subsidized CRACCon general tickets exclusively for the PyDelhi community.
- 1 session on security in python during pydelhi meetup.(every alternate meets)
- 1 specially designed Capture the flag competition specially designed for your community.
- Once a week social media posts about CRACCON until the conference.
- collaborate with you in PyCon event.

We believe that this collaboration will not only benefit our respective communities but also contribute to the overall success of CRACCON 2024. Your support will be instrumental in fostering a thriving environment for cybersecurity education and awareness.

If you are interested in exploring this collaboration further or have additional ideas in mind, please feel free to reach out. We are open to discussing how we can tailor this collaboration to best suit your community's objectives. Thank you for considering this collaboration opportunity. We look forward to the possibility of working together to make CRACCON 2024 a memorable and impactful event.

Thank you,
Swati Laxmi
CRAC Learning

**Comment by crac-learning** [comment]
Updated collaboration requests:

**Comment by pulsar17** [comment]
> For PyDelhi
Twice a week social media posts about CRACCON until the conference.

The frequency of social media posts is fine. Let us know who'll provide the creatives (text and posters).

> Purchase 3 student tickets for CRACCon and giveaway to your community. Use community partnership discount 10%. we will share once confirmed.

As @Animesh-Ghosh explained in private chat, we can't "purchase" tickets beforehand. What we can do is share the coupon code you provide on our social media through some contest. This does not guarantee that people will buy those tickets however. We'll try our best to promote, if folks want to purchase it, they will.

> For CRAC
15% coupon code for subsidized CRACCon general tickets exclusively for the PyDelhi community.

This is fine as well. Will this be a fixed number of tickets?

> 1 session on security in python during pydelhi meetup.(every alternate meets)

For how long? 3 months? 6 months? If we do this, it can be only be done on a best-effort basis since we're not sure of anyone's availability.
I think you've already proposed a combined meetup featuring security in Python. Is this in addition to that?

> 1 specially designed Capture the flag competition specially designed for your community.

This is fine as well

> Once a week social media posts about CRACCON until the conference.

Above you mentioned twice a week. This is fine as well.

> collaborate with you in PyCon event.

Did you mean PyDelhi Conference? It's separate from PyCon India which is a much bigger event. As of now, there are no plans to do either of those in 2024 (talking about just PyDelhi, for PyCon other Python chapters may propose to organise) @Animesh-Ghosh please correct me if I am wrong. If we do end up organising an event, we'll surely ask CRAC for collaboration.

**Comment by crac-learning** [comment]
Thank you Ishaan for your response. I am happy to know the mutual points of collaboration you have agreed upon. Below are the points where I have added clarification. Please let us know if you need more information

- There will be 20 tickets available at 15% coupon code for subsidized CRACCon general tickets exclusively for the PyDelhi community. USE code- PYDELHIHEROS for purchasing community and giveaway tickets once confirmed. Please share the PyDelhi logo for the giveaway social media post.
- 
- 1 session on security in python during pydelhi meetup.(every alternate meets) for next 1 year based on your convenience. It's part of the same combined meetup featuring security 
- We will happy to collaborate on any conference organized by PyDelhi group.
- Twice a week social media posts about CRACCON until the conference. Please share the PyDelhi logo for the  social media posts and we will provide it.


Please let me know next steps.
