### ISSUE TITLE
Supaercharge python with Redis

### ISSUE THREAD

**Issue by HarshitMahajan** [pydelhi/talks#269]
### Title

Introduction to Redis 

### Describe your Talk

Redis is an open source (BSD licensed), in-memory data structure store used as a database, cache, message broker, and streaming engine. Redis helps change the way we use databases with python. 

### Time required for the talk

30min

### About you

I am Harshit, I community manager at Bluelearn and an Ai and Datascience pre-final year student. I am learning new and opensource right now and exploring..

### Availability

16/02/24

**Comment by pulsar17** [comment]
Hi @HarshitMahajan, will you be available to give the talk on 21st January, 2024?

**Comment by HarshitMahajan** [comment]
Heyy 
Won't be available this month on those dates

**Comment by pulsar17** [comment]
@HarshitMahajan are you available to give this talk on 20/04/2024 (3rd Saturday)? 

The description might need some tweaking since Redis is no more BSD licensed ^^

**Comment by HarshitMahajan** [comment]
I will confirm you in a day 

Suree I will update the description

**Comment by pulsar17** [comment]
Closing this for now, feel free to reopen based on your availability. We generally have meetups every 3rd Saturday.
