### ISSUE TITLE
Seeking Aid for the workshop in my college 

### ISSUE THREAD

**Issue by Shoto0095** [pydelhi/talks#270]
### Describe your Talk

My name is Pratyush Mathur, and I'm reaching out from ABES Institute of Technology. We're planning a 12-hour Python Workshop at our College and are interested in potential collaboration with PyDelhi.

Could you please provide some insights by answering the following questions?

Event Details:

Proposed Date: 8th Jan 2024 - 23Jan 2023(Tentative)
Expected Number of Participants: Around 50-60 
Collaboration Opportunities:

How could PyDelhi contribute to the workshop's success, for right now we mainly need a speaker who can give a session on python topics mainly the one which are not taught in curriculum and are used on industry based? 
Availability and Preferences:
Is PyDelhi available for collaboration around the proposed date?
Are there specific preferences or requirements we should consider?
Process and Next Steps:

What is the preferred process for initiating collaboration with PyDelhi?
Any specific steps or protocols we should follow?
Your input is crucial for our planning, and we appreciate your time in providing this information. Looking forward to the possibility of collaboration.

### Time required for the talk

1-3 hours each on single topic (1 hour session each day)

### About you

My name is Pratyush Mathur and currently I am pursuing Bachelor of technology in computer science and engg. from ABES Institute of Technology and currently at Public relation position in Rubix Club ABESIT 

### Availability

08/01/2024

**Comment by Shoto0095** [comment]
And my contact details are:
LinkedIn : https://www.linkedin.com/in/pratyush-mathur-35a1a2251/
Twitter : https://twitter.com/PratyushMathur8

**Comment by satyaakam** [comment]
@Animesh-Ghosh can you look into it
