### ISSUE TITLE
Community meetup collaboration with Neo4j and PyDelhi

### ISSUE THREAD

**Issue by sidagarwal04** [pydelhi/talks#271]
### Title

Pythonistas and Graphistas: Navigating the World of Graph Databases with Python

### Describe your Talk

Hi team,

We would like to collaborate with PyDelhi for a community meetup in March as part of Graph Database Delhi/NCR User Group. Here is the proposal for the same:

Event Format : 2 hr hands-on worshop on Python + Neo4j and two 30-min talks
Event Size : 50-60 Python Developers
Location : TBD
Tentative dates : 16th March
Speakers : Both from Neo4j and PyDelhi community
Logistics : 
- Neo4j will take care of F&B
- PyDelhi will take care of Venue arrangements
- Promotions will be owned by both the orgs

Looking forward to hearing from you soon!

Regards,
Sid

### Time required for the talk

2 hours (120 min)

### About you

**Graph Database Delhi/NCR User Group**
Graph Database Delhi/NCR User Group is for anyone interested in exploring the intersection of graphs, artificial intelligence, machine learning, big data, and analytics. Our group is open-source efforts of Neo4j, a leading graph database technology to democratize graphs by discussing and exploring technologies that empower fraud prevention, personalized recommendation, supply-chain optimization, and other analysis capabilities found in today's most critical enterprise applications.

Our events include talks, workshops, and discussions on various topics related to graph data science. We cover a wide range of subjects, such as graph data modeling, graph algorithms, data visualization, machine learning, deep learning, and more. Our events are designed to be beginner-friendly but we cover in-depth topics as well, and we encourage participation and questions from everyone.

**Requester: Siddhant Agarwal**
I am currently leading Developer Communities for APAC at Neo4j. Formerly, I pioneered India's first fintech community as the 'Developer Relations Lead' at Open Financial Technologies. Prior to that, I spearheaded community efforts as a Program Manager with Google's Developer Relations team in India, overseeing programs like Developer Student Clubs, TensorFlow User Groups, Google Developer Groups, and Google Developer Experts. In 2019, I collaborated with the Ministry of Electronics & Information Technology, Government of India, to launch 'Build for Digital India,' engaging 7,000+ students in solving India's challenges.

I'm passionate about design thinking and enjoy mentoring startups to enhance their UX and designs. Recognized as one of ACM's Distinguished Speakers, my career of roughly a decade is dedicated to building, scaling, and growing communities in India, launching ed-tech initiatives, fostering design innovation, and contributing to the startup ecosystem.
In 2021, I was nominated as a finalist for the CMX Community Industry Awards for my role in community building. As an avid public speaker, I've shared insights at over 1,000 national and international forums, reaching 300K+ individuals.

### Availability

16/03/2024

**Comment by pulsar17** [comment]
Hi @sidagarwal04, thanks for the workshop. Can you please share the slides so that I can share them further?

**Comment by sidagarwal04** [comment]
Hi @pulsar17 , Here you go. [Uploading Graph Powered NLP using Google Gemini, Neo4j and Python.pdf…]()

**Comment by pulsar17** [comment]
Thanks! Looking forward to more such collaborations in the future. Closing this issue.
