### ISSUE TITLE
Python and RabbitMQ: A Beginner's Guide to Asynchronous Workflows

### ISSUE THREAD

**Issue by ahtesham007** [pydelhi/talks#272]
### Title

Python and RabbitMQ: A Beginner's Guide to Asynchronous Workflows

### Describe your Talk

I will introduce the messaging queue (RabbitMQ), its application, and its benefits. How this message broker can be integrated with Python and its usage with a demo.

### Pre-requisites & reading material

Python understanding is required.

### Time required for the talk

25 - 30 mins

### About you

I am a Software Engineer at L&T Technology Services with over 2.5 years of work experience. I have been designing, developing, and testing software in Python.

LinkedIn - https://www.linkedin.com/in/ahtesham-zaidi/
Blog - https://ahtesham-zaidi.hashnode.dev/

### Availability

Available on mostly all the weekends

### Any comments

This will be beginner friendly talk.

**Comment by ahtesham007** [comment]
Yes, I am available.

**Comment by pulsar17** [comment]
@ahtesham007 please ping me on Telegram so that I can contact you tomorrow; my username is @pulsar17 there as well. Your talk is scheduled at 2:30 pm, so please reach the venue at least 20 minutes before your slot.

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk @ahtesham007!
