### ISSUE TITLE
Secure Coding in Python

### ISSUE THREAD

**Issue by shrutiiaroraaa** [pydelhi/talks#274]
### Title

Secure Coding in Python

### Describe your Talk

In this talk, we'll delve into the fundamental principles of secure coding, exploring common pitfalls that developers often encounter and learning best practices to fortify Python applications against potential vulnerabilities. From essential security libraries to real-world case studies, we'll cover a spectrum of topics aimed at empowering developers with the knowledge and tools to enhance the security posture of their Python projects. Whether you're a seasoned developer or just starting your coding journey, this talk promises valuable insights to help you build robust and secure Python applications. Let's navigate the nuances of secure coding together and ensure that our Python code stands strong against the ever-evolving cybersecurity landscape.

### Pre-requisites & reading material

Prior Familiarity with Python Basics Recommended

### Time required for the talk

30

### About you

- Always Excited about security - I am a Cyber Security Advocate ;)
- Developer Relations At Commudle
- Founder At DevRelo
- [LinkedIn](https://www.linkedin.com/in/shrutiiaroraaa/)
- [Twitter](https://twitter.com/shrutiiaroraaa)

### Availability

Weekends

**Comment by pulsar17** [comment]
Hi @shrutiiaroraaa, will you be available to give this talk on 24th February?

**Comment by Animesh-Ghosh** [comment]
Hey @shrutiiaroraaa, can you deliver your talk on March 16th?

**Comment by shrutiiaroraaa** [comment]
Hi,
Yes I'm available.

**Comment by pulsar17** [comment]
Looks like it's going to be a security theme all around - https://github.com/pydelhi/talks/issues/282 ^^

@shrutiiaroraaa can you ping me on Telegram so that I can reach out on the day of the meetup? My username there is pulsar17 as well.

**Comment by pulsar17** [comment]
Hi @shrutiiaroraaa just a friendly reminder that your talk is scheduled for today. Please do ping me on Telegram before your allotted time slot - https://www.meetup.com/pydelhi/events/300443396/

**Comment by pulsar17** [comment]
Closing this for now, feel free to reopen based on your availability.
