### ISSUE TITLE
The scientific side of Python and Open-Source: using Python for High Energy Physics at CERN 

### ISSUE THREAD

**Issue by Saransh-cpp** [pydelhi/talks#275]
### Title

The scientific side of Python and Open-Source: using Python for High Energy Physics at CERN 

### Describe your Talk

I'll start broad, covering use cases of Python across the scientific community, including my own experiences. The talk will include discussing the Scientific Python ecosystem, core scientific libraries of Python, and open-source + open-science.

The talk will then funnel down to use cases of Python at CERN. I'll dive into how physicists are using Python, how computer scientists are developing tools for physicists, and a relatively new field - research software engineering (RSE). Finally, I'll discuss the career prospects in RSE and Scientific Computing, and how one can contribute to the exciting research going on at places like CERN.

### Pre-requisites & reading material

Basics of Python and a curious mind. Knowledge of Mathematics and Physics is appreciated but even I don't have a background in Physics.

### Time required for the talk

60 mins

### About you

Previous talk at PyDelhi - https://github.com/pydelhi/talks/issues/215
Better description: https://saransh-cpp.github.io

---

I am currently based at [CERN](https://home.cern/), working as a Research Fellow with the [Princeton Research Computing Group](https://researchcomputing.princeton.edu/) and [IRIS-HEP](https://researchcomputing.princeton.edu/research/iris-hep-software-institute). I am an engineering senior at the [University of Delhi](http://du.ac.in/), pursuing a major in IT and Mathematics. In daylight, I work on my academic skills and professional commitments, and by night, I develop and maintain Open-Source Scientific Software (see [/opensource](https://saransh-cpp.github.io/opensource)), which I believe are the key to collaborative and reproducible research.

I am broadly interested in {Research Software Engineering, Scientific Computing, DevOps}, {Theory of Computation, Programming Languages, Type Theory}, {Scientific Machine Learning, Computer Vision, and Machine Learning for BioMedical Data}. I am extremely passionate about Open-Source and Open-Science. I am also developing some taste for pure Software Engineering research (runtime verification, new testing methods, etc). Finally, I possess a strong background in Android Development and Backend Development, but I don’t find them interesting anymore.

### Availability

After June 18th, before July 30th

### Any comments

I am creating this issue in advance to ensure that I get a spot in the June/July meetup. I will not be available after this, and I really want to talk about scientific computing as it is a relatively less explored field amongst Indian CS undergrads. I will update this issue with more details as the meetup gets near.

**Comment by pulsar17** [comment]
I know you've mentioned exact dates but still... we're having a meetup on 15th June. Let us know if that's ok. Otherwise we can schedule it for July.

**Comment by Saransh-cpp** [comment]
Hi, thanks for the ping! Unfortunately, I won't be able to present on 15th June. I should be able to make it to the July meetup tho.

**Comment by Saransh-cpp** [comment]
Hi @pulsar17 @Animesh-Ghosh,

A few things popped up, and unfortunately, I will not be available in India in July, but I just saw @pulsar17's comment on a proposal saying that the June meetup is being postponed to the 22nd. I can make it to the 22nd June meetup if that is the plan. Please let me know if you do end up postponing the meetup.

Thanks!

**Comment by pulsar17** [comment]
@Saransh-cpp this is a combined meetup (almost a mini-conference) with @rustdelhi and @ILUGD. We have 2 speakers already from PyDelhi. We're keeping 20 mins as the time slot this time since we'll potentially have total 6 speakers (2+2+2).

You've mentioned 1 hour as the required time for your talk. I'd suggest you come to the meetup and give it as a lightning talk instead (5-10 mins) if possible.

**Comment by pulsar17** [comment]
Cool, I'm confirming your talk for 22nd June as a lightning talk. We might or might not announce it "officially" (usually we don't for lightning talks) but you can give it :)

The timings would probably be 10am-1pm but I'll mention here once we decide it.

**Comment by Saransh-cpp** [comment]
Cool, see you then! :)

**Comment by pulsar17** [comment]
Thanks for giving the talk! Feel free to reopen / open a new issue when you get available next time. In the meantime, please don't let a black hole engulf this tiny planet :)

**Comment by Saransh-cpp** [comment]
Haha, thanks again for organising this!
