### ISSUE TITLE
Engineering Excellence and AI with PyDelhi Community Collaboration Proposal

### ISSUE THREAD

**Issue by arglee** [pydelhi/talks#276]
### Title

Engineering Excellence using AI and Python

### Describe your Talk

🚀 **Innovaccer Engineering Meetup in Delhi-NCR Chapter!** 🐍🔧 
Calling all Python and engineering enthusiasts for an epic gathering filled with insights and networking opportunities

🤝 Calling all tech enthusiasts! Innovaccer's Engineering Meetup in Noida is eager to collaborate with PyDelhi. Together, let's forge an unforgettable event brimming with knowledge-sharing, networking opportunities, and tech wizardry! Join forces with us to create an epic gathering that fuels innovation and community spirit. See you there! 🚀

**Event Date:** 16 March 2024
**Event Location:** Innovaccer Noida Office, Sector 62, Noida
**Time:** 11 AM-3 PM
**Topics:** An insightful session on elevating coding efficiency. Explore topics like building enterprise-level products with Python and FastAPI, hands-on AI application development, and mastering bug-free coding with Python AI. 

Plus, we've got a treat for you! Enjoy a **delicious lunch and grab some exciting goodie**s as a token of appreciation for being part of this enriching Engineering Meetup. Let's make learning and networking even more delightful! 🍔🎁

### Pre-requisites & reading material

- Python Basic
- Artificial Intelligence Basics

### Time required for the talk

3-4 Talks each of 30 mins

### About you

I am working as Senior Engineering Manager - Platform team at Innovaccer and have delivered few talks on PyDelhi Chapter in  2022. 

### Availability

16/03/2024

**Comment by satyaakam** [comment]
@Animesh-Ghosh anyone looked into it ? reply to OP if this is feasiable

**Comment by satyaakam** [comment]
@arglee what are you expectations from PyDelhi community can you jot that down as well ?

**Comment by satyaakam** [comment]
@arglee oh i missed it we have a collaborative meetup with Neo4J on the same date https://www.meetup.com/pydelhi/events/298794986/ , is it possible for you to postpone your event ?

**Comment by arglee** [comment]
@satyaakam That's not feasible. But thank you for the support. Hope to do something in future together.
