### ISSUE TITLE
unittest- How to use Assertions

### ISSUE THREAD

**Issue by BhargavaAshish** [pydelhi/talks#28]
Python unittest is an excellent tool to test the python code at unit level and easy to understand every python developer should aware of it

**Comment by akshayaurora** [comment]
@BhargavaAshish scheduling your talk for our next meet up on 6th November.

Let us know if you won't be able to make it.

**Comment by theskumar** [comment]
@BhargavaAshish i'm closing this up due to no response. Please reopen as required.
