### ISSUE TITLE
Embarking on the Gemini Journey: Exploring the Twin Worlds of Technology and Innovation

### ISSUE THREAD

**Issue by 072arushi** [pydelhi/talks#280]
### Title

Embarking on the Gemini Journey: Exploring the Twin Worlds of Technology and Innovation

### Describe your Talk

The talk will cover following aspects-
1. Introduction to Gemini
2. High level architecture of Gemini
3. Talking about transformers
4. Uniqueness of Gemini 
5. Importance of the write prompt

### Pre-requisites & reading material

NA

### Time required for the talk

30 mins

### Link to slides/demos

https://www.canva.com/design/DAF8pafFYrk/yNmdP5R8bPFmG7Qhcqhkrw/edit?utm_content=DAF8pafFYrk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### About you

4th year BTech student at IGDTUW, Winter intern at Adobe
LinkedIn- https://www.linkedin.com/in/arushi-garg105
Twitter- https://twitter.com/ArushiSpeaks105
Instagram- https://instagram.com/arushigarg_105?igshid=NTA5ZTk1NTc=

### Availability

Can discuss over this

**Comment by pulsar17** [comment]
Hi @072arushi , will you be available to present this talk on 16th March? This meetup is a collaborative one with Neo4j (More details [here](https://www.meetup.com/pydelhi/events/298794986))

Also, I'm assuming there'll be some Python examples on working with Gemini. Or is this more of an overview of how Gemini itself works?

**Comment by pulsar17** [comment]
Hey @072arushi are you available to present this talk on April 20?

**Comment by Animesh-Ghosh** [comment]
1. timings would be 1 - 5 PM most probably
2. date would be the 3rd Saturday of the month, ie 20th April
3. location is still TBD
4. assume the target audience to be junior and mid-level software developers; consider most to be either unfamiliar with transformers or have some semblance of the topic

Does this help, @072arushi?

**Comment by pulsar17** [comment]
Except we're full in terms of slots for this month @Animesh-Ghosh. Though the points mentioned would be the same. We can have your talk next month @072arushi. It's generally always the 3rd Saturday, so 18th May.

**Comment by 072arushi** [comment]
Ohhh alright @Animesh-Ghosh

**Comment by pulsar17** [comment]
@072arushi are you available to present this talk on 18th May?

**Comment by pulsar17** [comment]
Feel free to reopen!
