### ISSUE TITLE
Proposal of talk in collaboration with CRAC Learning

### ISSUE THREAD

**Issue by crac-learning** [pydelhi/talks#282]
### Title

Secure development in Python

### Describe your Talk

Using Python for Secure implementation
• Gathering security requirements
• Learn about common insecure code practices.
• Securing the written code.
• Use AI for using secure technologies.
User Authentication and Authorization 
• Implementing strong authentication and authorization mechanisms safeguards AI systems from unauthorized access. 
• Techniques such as multi-factor authentication, 
• Role-based access control, and 
• least privilege principle help enforce access control policies and prevent unauthorized usage.
Secure testing
• Learn about common insecure code practices.
• Securing the written code.
• Use secure technologies.
Dev-Sec-ops 
• Automated code analysis
• Secure pipeline and repositories
• Access management
LAB: Hands on quiz

### Time required for the talk

1 hour

### About you

About CRAC Learning:

At CRAC Learning Foundation (non-profit), New Delhi, our mission is to create a platform that not only educates but also inspires the next generation of cybersecurity enthusiasts. Our annual conference has grown in prominence, and we believe that your company's involvement will play a crucial role in making this event a resounding success.

Active engagements with 5000+ students across India

Experienced core team with expertise from top companies such as Amazon, Microsoft, AWS, Apple, KPMG, EY, and more

Previous partnerships with renowned communities like Seasides, IEEE, OWASP, HackersVilla, SAS, and IICON.

### Availability

15/04/2024

### Any comments

Flexible with availability, we can accordingly discuss.

**Comment by pulsar17** [comment]
Hi @crac-learning, our meetups are on 3rd Saturday of every month, so the next one is on 20/04/2024. 

Please let me know the following details:
- if someone from CRAC is available on 20/04/2024. 
- the name, work information (designation/company if any) of the speaker(s) that will give the talk

**Comment by pulsar17** [comment]
One can refer to https://github.com/pydelhi/talks/issues/266 for previous discussion on the collaboration.

**Comment by crac-learning** [comment]
Sure, we can do it for 20 April

**Comment by crac-learning** [comment]
Speaker name:
Swati Laxmi, Founder of CRAC Learning Foundation
https://www.linkedin.com/in/swatil/

**Comment by crac-learning** [comment]
Please let me know next steps.

**Comment by pulsar17** [comment]
We'll announce the meetup soon. The timings are generally 1-5 pm, and the venue is CIC, Delhi University.

**Comment by pulsar17** [comment]
@crac-learning are you available on this 18th?

**Comment by crac-learning** [comment]
Hello @pulsar17 , I am not available on 18th, can we do it next month please in second half?

**Comment by pulsar17** [comment]
@crac-learning would 15th June work for you?

**Comment by crac-learning** [comment]
Yes that works for me.

**Comment by pulsar17** [comment]
Scheduling the talk then. We're thinking of keeping the timings around 10am-1pm due to the heat wave. Will let you know once everything is finalized.

**Comment by pulsar17** [comment]
@crac-learning we're thinking of postponing the meetup to 22nd June (3rd Saturday). Would you be available on that day?

**Comment by pulsar17** [comment]
@crac-learning forgot to mention this but the time slot would be 20 mins as opposed to 30 mins as this is a combined meetup with @rustdelhi and @ILUGD. Please try to either trim or squeeze the material in 20 mins. I see you've mentioned 1 hour in the description. Would 20 mins be sufficient?

**Comment by crac-learning** [comment]
sure that would be fine.

**Comment by pulsar17** [comment]
Thanks for giving the talk!
