### ISSUE TITLE
Career Options in Python and Roadmap to Succeed 

### ISSUE THREAD

**Issue by bhupi080** [pydelhi/talks#283]
### Title

Career Options in Python and Roadmap to Succeed

### Describe your Talk

1. How can we choose Python as a career option?
2. How much time does it take to learn Python for IT/non-IT aspirants?
3. How can non-IT professionals shift their career to Python development?
4. What is the roadmap to becoming a Python developer?
5. How to handle errors in Python programming?
6. How can I determine if I am suited to coding?
7. How to decide when to transition my career, especially for candidates from BA/BCom backgrounds?
8. How to manage finances, especially considering that beginners are often paid less?
9. What are some free resources, both online and offline, to start learning Python?

### Pre-requisites & reading material

I have a lot of my own customized study materials. I will attach a few of them.

https://www.youtube.com/playlist?list=PLUTX0EJodOBfN6eNjHj3ZNetgyg64bJX2

### Time required for the talk

30 Minutes - 1 Hour

### Link to slides/demos

https://docs.google.com/presentation/d/1eWGkJI393de7QB6SU0rIg2FTNqx2eD9AsgflrhwnCT8/edit?usp=sharing 

### About you

I am Bhupinder, professional serving as a Full-Time Training Incharge in Software Development Faculty at World Class Skill Centre, which is an initiative by Sun Foundation. In this role, I develop and execute comprehensive training plans, providing valuable coding skills to trainees and ensuring their technical proficiency.

With a professional journey spanning 7 years, I initially started my career as a backend developer and DevOps engineer. During this phase, I specialized in building APIs using Spring Boot and deploying them on AWS, gaining hands-on experience in crafting robust and scalable solutions.

For More - https://bhupisingh.in/

### Availability

18/05/2024

### Any comments

I would love to share my knowledge with fellow developers and am excited to meet both fresh and experienced minds to exchange knowledge and explore the upcoming opportunities.

email - official@bhupisingh.in

**Comment by Animesh-Ghosh** [comment]
Hey @bhupi080, can you update the link to slides with links to your slides instead of your homepage? It's fine if it's still in draft etc.

We ask for it so that people, when they scroll through the Issues in the future, can refer to the slides and get an idea about the kind of talks that are usually accepted.

Also, the PDF links can be removed, since the YouTube playlist seems to be more relevant to your proposed talk.

Thanks!

**Comment by bhupi080** [comment]
@Animesh-Ghosh Updated, sir. Also, if I need to speak in 1 hour, then this PowerPoint slide link may not be useful. In that case, I'll have to prepare another one. Please let me know in advance if I need to prepare it.

**Comment by Animesh-Ghosh** [comment]
@bhupi080 some more feedback for your proposal:

1. the talk should take 30 minutes max to deliver
2. your talk seems to touch a lot of things, the focus is not clear. Can we do either a career counseling or a Python talk?

Apologies for the delayed response.

**Comment by bhupi080** [comment]
Yes, Sir, I have attached a lot of content that I won't be able to cover in 30 minutes. Therefore, I will focus on career counseling and the Python talk as you suggested. Please give me today's time i.e, 16th May, and I will send another PPT with the respective points.

**Comment by Animesh-Ghosh** [comment]
@bhupi080 no, the talk should focus on either career counseling or Python development, not both.

**Comment by bhupi080** [comment]
Okay, sir. I have prepared the PPT for Python Counseling. Please review it.

https://docs.google.com/presentation/d/1mNVyu1SOl4dChnuC5zdc-VZ6fo9xwuNYatctQjVyCJw/edit?usp=sharing

**Comment by Animesh-Ghosh** [comment]
@bhupi080 looks good to me.

Please share your Telegram handle so that we may add you to the PyDelhi Telegram group, if you're not already there. It will help coordinate the timings etc.

You may reach out to me on mine: @MaD_Dogx
