### ISSUE TITLE
Python 1 Liners

### ISSUE THREAD

**Issue by Param302** [pydelhi/talks#284]
### Title

Python 1 Liners

### Describe your Talk

Python 1 liners consist of all the short-hands we can do in Python. It is very useful for beginners, as well as other levels of programmers too, as it's time efficient and a good skill to learn on. It contains ternary operator (If else in 1 line), Comprehensions for various data structures like list, tuple, dictionary and generator. Also includes nested comprehensions and conditional comprehensions. By the end of this talk, a programmer will be able to refactor their code using comprehensions and 1 liners, it will help them save the time, cost of computing and also follows Zen of Python :snake: 

### Pre-requisites & reading material

Basic knowledge of Python and it's data structures like:
- Variables & Datatypes
- Conditionals
- List
- Tuple
- Dictionary
- Functions
- Generator (optional, will be covered)

### Time required for the talk

30-45 mins

### Link to slides/demos

https://docs.google.com/presentation/d/1Jop5ZBtO-1EMs-jVnhRbvCpT-NQBeewiGLR_JGkVpJ8/edit?usp=sharing

### About you

I am Parampreet Singh, a Self Taught Developer, having more than 4 years of programming experience. My main tech stack is Python and I am an ML Enthusiast. I am currently pursuing Bachelors of Science in Data Science and Applications from **IIT Madras**. Having mroe than 4 years of experience, I have shared my learning, and taught Python to various students. Took Python sessions in several famous Tech influencer's discord server like Love Babbar, Apna College. Also Taught Python to 100+ of my college students Live!
My Python Playlist link: https://www.youtube.com/playlist?list=PLClULgPbRPsD-t0AYG8hR5iLIt2ZaNTkv
My LinkedIn: https://linkedin.com/in/Param302
All my links: https://param302.bio.link

### Availability

18/05/2024

### Any comments

It will be my first talk in person, need suggestions on how to stay stress free :sweat_smile:

**Comment by pulsar17** [comment]
Hi @Param302 thanks for proposing this!

A couple of pointers for a giving a technical talk:
1. Practice and time your talk.
2. Understand that you might not be the expert in the room on the topic you're presenting, there might be someone who's life's work is that topic (improbable but possible). Try to be factually correct but it's ok to make mistakes, this is a meetup not a conference.
3. The audience is there to listen and won't judge you. You being the speaker have "extra" power over the room.
4. Let people know if it's going to be interactive or you want questions at the end.
5. Try to have fun and don't stress too much :)

[This](https://youtu.be/4KSX9ZEE5-o?si=rlTxepFWDE0imzpV) is a presentation on how to give presentations that I personally like.

You can attend https://www.meetup.com/pydelhi/events/300973362/ and even give a 5-10 min talk (what we call a lightning talk) about this topic to gauge interest and ask for feedback.

I'm marking this as "accepted".

All the best!

**Comment by Param302** [comment]
Hi @pulsar17 , 

Thank you so much for accepting my proposal and providing the points for giving a talk, I will practice the talk and keep all points in mind.

And I will modify the PPT accordingly!

**Comment by pulsar17** [comment]
@Param302 would you be available to present this on 15th June (3rd Saturday)?

**Comment by Param302** [comment]
> @Param302 would you be available to present this on 15th June (3rd Saturday)?

Yes!

**Comment by pulsar17** [comment]
I've scheduled your talk. We're thinking of keeping the timings around 10am-1pm due to the heat wave. Will let you know once everything is finalized.

**Comment by pulsar17** [comment]
@Param302 we're thinking of postponing the meetup to 22nd June (4th Saturday). Would you be available on that day?

**Comment by Param302** [comment]
> @Param302 we're thinking of postponing the meetup to 22nd June (3rd Saturday). Would you be available on that day?

Yes, I am available!

**Comment by pulsar17** [comment]
@Param302 forgot to mention this but the time slot would be 20 mins as opposed to 30 mins as this is a combined meetup with @rustdelhi and @ILUGD. Please try to either trim or squeeze the material in 20 mins.

**Comment by Param302** [comment]
> @Param302 forgot to mention this but the time slot would be 20 mins as opposed to 30 mins as this is a combined meetup with @rustdelhi and @ILUGD. Please try to either trim or squeeze the material in 20 mins.

No worries, I will update the ppt accordingly.

**Comment by pulsar17** [comment]
Thanks for giving the talk!
