### ISSUE TITLE
Worried of slow pandas with large-scale Data Analysis? Embrace FireDucks!

### ISSUE THREAD

**Issue by qsourav** [pydelhi/talks#286]
### Title

Worried of slow pandas with large-scale Data Analysis? Embrace FireDucks!

### Describe your Talk

In this talk, I will introduce [FireDucks](https://fireducks-dev.github.io/), a revolutionary compiler-accelerated DataFrame Library for Python that seamlessly integrates with the pandas API. It offers high performance (even on CPU), high compatibility with pandas, sustainability, cost-effectiveness, and reliability, making it an ideal choice for large-scale data analysis using pandas.

Key features of FireDucks include: 
- Multithreaded processing for increased efficiency 
- JIT (Just-In-Time) compilation for optimized performance 
- Seamless integration with Pandas API 
- Comprehensive benchmarks for performance evaluation 

Agenda:
- Common problems with large-scale pandas workload
- Introduction of FireDucks and its capabilities
- Demonstrations 
- Q&A Session
 

### Pre-requisites & reading material

Basic knowhow of pandas will be fine.

### Time required for the talk

30-40 mins

### Link to slides/demos

https://fireducks-dev.github.io/files/20240716_FireDucksIntro_AustinPython.pdf

### About you

Sourav has 11+ years of professional experience at NEC Corporation (based in Tokyo, Japan) in the diverse fields of High-Performance Computing, Distributed Programming, Compiler Design, and Data Science. Currently, his team at NEC R&D Lab, Japan, is researching various data processing-related algorithms. Blending the mixture of different niche technologies related to compiler framework, high-performance computing, and multi-threaded programming, they have developed a Python library named FireDucks with highly compatible pandas APIs for DataFrame-related operations. In his previous engagements, he has worked in research and development of performance-critical AI and Big Data solutions, optimization of several legacy applications related to weather prediction, earth-quake simulation, etc., written in C++ and Fortran.

### Availability

any day should work for me

### Any comments

I am based in Tokyo, Japan. So, if there is an online or hybrid meetup session sometime, I can present my talk.

**Comment by pulsar17** [comment]
Hi @qsourav, thanks for proposing this!

In the past, it has been difficult to organize hybrid events due to lack of resources. If we do do one in the future, someone will definitely reach out to you.

**Comment by pulsar17** [comment]
Sure! A bunch of us from PyDelhi are attending.

Best
Ishaan Arora

A man’s not dead while his name is still spoken.

-------- Original Message --------

**Comment by Animesh-Ghosh** [comment]
@qsourav would you be available to deliver your talk this Saturday on 21st Dec?

**Comment by qsourav** [comment]
Hi @Animesh-Ghosh,

Sincere apologies for the delay in my response. At what time do you plan to conduct the session?

**Comment by Animesh-Ghosh** [comment]
The tentative meetup timings are 1-5 PM @qsourav.

Could you let us know what time might suit you?

**Comment by qsourav** [comment]
Hi @Animesh-Ghosh, thank you for the flexibility in timing. I would prefer it to be from 1 pm.

**Comment by qsourav** [comment]
Hi @Animesh-Ghosh , can you please inform me the zoom id or something to join the meetup? It is being conducted in virtual mode, right?

**Comment by Animesh-Ghosh** [comment]
Thanks @qsourav for the talk!
