### ISSUE TITLE
Proposal: "Kivy :Python for Android" 

### ISSUE THREAD

**Issue by rajarahulray** [pydelhi/talks#29]
Aim: To develop android applications using Kivy from scratch.

Level: Beginner + Intermediate

Live Tutorial demonstration : Yes

Link to slides: **http://slides.com/rajarahulray/kivy_intro#/**

**Comment by akshayaurora** [comment]
@rajarahulray can you deliver this talk on 24th June?

**Comment by rajarahulray** [comment]
I am really sorry Sir...But I am going to Hyderabad this weekend for
AngelHack. However, I can deliver it on next weekend, if you can allow.

Thanks for considering my proposal.

Raja Rahul Ray

**Comment by rajataaron** [comment]
Hi @rajarahulray ,
Sorry for a delay, can you deliver your talk in our next meetup which is on 17th Feb ?
