### ISSUE TITLE
monitor your linux system using python

### ISSUE THREAD

**Issue by rpsmaini** [pydelhi/talks#290]
### Title

monitor your linux system using python

### Describe your Talk

In this talk I will be discussing about my linux script that monitors almost every metric of the linux server like( cpu, disk, memory etc) and record those metrics in the csv files.
here is link to the project: https://github.com/rpsmaini/linux_sys_monitor

### Time required for the talk

15-20 mins

### About you

My Name is Ravpreet Singh Maini. I aspire to become an IT professional. Currently I am in my senior year in IGNOU pursuing BCA. I am more inclined towards Cloud and Devops domain.
here is my linkedin: https://www.linkedin.com/in/rpsmaini

### Availability

24/08/2024

**Comment by rpsmaini** [comment]
I forgot to mention that the script is written in Python for linux systems

**Comment by Animesh-Ghosh** [comment]
Hi @rpsmaini, 

Are you available to deliver your talk on the 24th of August?

**Comment by rpsmaini** [comment]
yes for sure

**Comment by Animesh-Ghosh** [comment]
@rpsmaini do share the link to the slides in the original comment.

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk @rpsmaini!

Please make sure to update the issue with your talk's slides for future speakers' reference.
