### ISSUE TITLE
From Open Source Basics to Building with InstructLab

### ISSUE THREAD

**Issue by 1610ayushi** [pydelhi/talks#291]
### Title

From Open Source Basics to Building with InstructLab

### Describe your Talk

In this session, we will dive into **InstructLab**, a new community-based approach to building truly open-source large language models (LLMs). We’ll begin by explaining the significance of open-source development in the AI landscape and how it empowers global collaboration. The focus will be on how InstructLab fosters a community-driven effort to develop LLMs that are accessible, transparent, and innovative. By simplifying the complex world of machine learning, InstructLab is enabling contributors to actively participate in the creation of powerful AI tools, pushing the boundaries of open-source AI.

### Pre-requisites & reading material

Basic knowledge of LLM

### Time required for the talk

15-20 mins

### Link to slides/demos
https://docs.google.com/presentation/d/1d08YUbL8JlBPrDAryebkXDqYlBYPmCfuw2JYBxq1jNw/edit?usp=sharing

_No response_

### About you

I’m Ayushi Tiwari, an Associate Software Engineer at Red Hat with over 1 year of experience in AI, machine learning, and open-source technologies. In addition to my engineering work, I am also a public speaker, having delivered talks at various colleges and events. I am passionate about sharing my knowledge in AI and ML, and I actively contribute to the open-source community, aiming to make cutting-edge technologies more accessible and understandable.

LInkedin - https://www.linkedin.com/in/ayushitiwari16/

### Availability

24/08/2024

**Comment by 1610ayushi** [comment]
LInkedin - https://www.linkedin.com/in/ayushitiwari16/

**Comment by Animesh-Ghosh** [comment]
Hi @1610ayushi 

Could you also dive into one aspect of InstructLab's architecture, even if briefly, along with doing the community driven aspect?

I understand InstructLab is written in Python. If you do give an overview of its architecture, that would be more valuable and foster good discussions around your talk.

No need to drop the community aspect, but augmenting the talk with some technical depth will enhance audience takeaways.

**Comment by 1610ayushi** [comment]
Okay sure.

**Comment by Animesh-Ghosh** [comment]
Please do share the slides for future speakers' reference @1610ayushi.

You may edit the initial comment itself and add the link there.

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk @1610ayushi!

Looking forward to more such talks in the future.
