### ISSUE TITLE
Build ML Web Apps with Python

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [pydelhi/talks#292]
### Title

Build ML Web Apps with Python

### Describe your Talk

In this session, I will talk about deploying ML models in production, using open source python library like Gradio. I will start by simply asking the questions of why is there a need of such web apps in the first place, then what are some other famous python frameworks, and why streamlit or gradio are better when it comes to ml model integration. In the end, I'll provide a demo, so that the participants can easily relate to the topic and can also participate.

### Pre-requisites & reading material

Python language, Python Functions

### Time required for the talk

20 mins

### Link to slides/demos

https://docs.google.com/presentation/d/1IkrQ-cXFnigiZtRX7pCiyy-pFw25G9NceAKBAmkRcZY/edit?usp=sharing

### About you

I'm Kritika Parmar, Machine Learning Engineer at Filterpixel, with over 1 year of experience in computer vision, machine learning and deep learning. I have delivered talks at different GDG, GDSC and TensorFlow group events. 

### Availability

24/08/2024

**Comment by Daksh777** [comment]
Hey Kirtika, thank you for your submission 

Can you please tell what would be there in the demo? And please note that a lot of attendees are not able to bring their laptops so they won't be able to do it hands on

Rest the talk seems great!

**Comment by kritikaparmar-programmer** [comment]
Here is a small demo. https://colab.research.google.com/drive/1mbzIu0t-NDm-PVyNLSw3u_hIwtSOLBKp?usp=sharing
No issues if not hands on, they will be able to interact with it.

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk and the referenece Jupyter Notebook @kritikaparmar-programmer!

Hope to see more talk submissions from you in the future.
