### ISSUE TITLE
Use of cvlib face detection tech for some interesting use cases. 

### ISSUE THREAD

**Issue by virajsharma2000** [pydelhi/talks#294]
### Title

Use of cvlib face detection tech for some interesting use cases. 

### Describe your Talk

Human face detection in real time is made very easy using the Cvlib module. We will walk through the code and execution for some interesting use cases like count faces in a stream, intruder detection, gauge aesthetics of a face etc. The talk will be to emphasize the ease of use of the lib and the use cases through code.

### Pre-requisites & reading material

The library readme - https://github.com/arunponnusamy/cvlib
Some information about face detection - https://en.wikipedia.org/wiki/Face_detection
some code - https://github.com/virajsharma2000/python_apps/blob/main/face_looking_competition.py

### Time required for the talk

15-20 minutes

### Link to slides/demos

https://docs.google.com/presentation/d/1grE0gkw-GclDB4adq5EJGwSMQHwpRh9lzK5oeYRMd3A/edit?usp=sharing

### About you

I am viraj- I am a python technology enthusiast. please check my github for some of the work I have done - virajsharma2000

### Availability

19/10/2024

**Comment by pulsar17** [comment]
Hi @virajsharma2000 I went through your demo code, and I think it can be better presented as a lightning talk. If you'd like to give one let me know. We generally don't post lightning talks on socials, but if you want to give it, a 5 min slot will be made available to you.

**Comment by virajsharma2000** [comment]
Hi @pulsar17 ..thanks for suggestion, yes I would be happy for it to be shortened to a lightening talk.

**Comment by pulsar17** [comment]
Alright! The tentative schedule will be posted on the Meetuo page in a few days.
Confirming your lightning talk.

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk @virajsharma2000!

See you in the next meet-up and keep sharing what you learnt 👏
