### ISSUE TITLE
Getting Started with APIs in Python - FastAPI

### ISSUE THREAD

**Issue by bhupi080** [pydelhi/talks#295]
### Title

Introduction to FastAPI Framework

### Describe your Talk

In this talk, we’ll explore how to set up and get started with FastAPI, a modern and high-performance web framework for building APIs with Python. This session will guide you through each step, from creating a Python environment and installing FastAPI, to writing your first API endpoints and running your app locally with Uvicorn. You’ll also learn how to handle API documentation, explore interactive tools like Swagger.

### Time required for the talk

15 - 20 mins

### Link to slides/demos

https://drive.google.com/file/d/1ULKAb_BrNudSwqUL7e6SFNTglF0NKZjz/view?usp=sharing

### About you

I am Bhupinder, professional serving as a Full-Time Training Incharge in Software Development at World Class Skill Centre, which is an initiative by Sun Foundation. In this role, I develop and execute comprehensive training plans, providing valuable coding skills to trainees and ensuring their technical proficiency.

With a professional journey spanning 7 years, I initially started my career as a backend developer and DevOps engineer. During this phase, I specialized in building APIs using Spring Boot and deploying them on AWS, gaining hands-on experience in crafting robust and scalable solutions.

### Availability

19/10/2024

**Comment by Animesh-Ghosh** [comment]
Hi @bhupi080, will you be doing a hands-on demo for the talk?

If you can try and name drop some companies using FastAPI on production that'd be a neat addition to the slides imo.

**Comment by bhupi080** [comment]
@Animesh-Ghosh Yes, I will be giving a practical demo on how to create APIs in Python, and I will include a slide showing the companies that are using FastAPI. Thanks for the great suggestion!

**Comment by bhupi080** [comment]
Companies that are using FastAPI - updated in the slides. Please refer to slide no. 2 @Animesh-Ghosh

**Comment by pulsar17** [comment]
I'm marking this as "Accepted" while acknowledging that explaining this in a 15 mins talk would be challenging :)

**Comment by pulsar17** [comment]
We'll update you @bhupi080 on the timings of your talk.

**Comment by Schefflera-Arboricola** [comment]
Thank you for the great talk @bhupi080  :)
Hope to see you at the coming meet-ups!

Feel free to submit more talk proposals :)
