### ISSUE TITLE
Fetching current weather using an API in python

### ISSUE THREAD

**Issue by muskan168** [pydelhi/talks#297]
### Describe your Talk

In my talk, I will cover the process of fetching current weather data using an API in Python. We'll explore how APIs serve as a bridge between the weather service provider and our Python application, making real-time data easily accessible. The presentation will include an overview of popular weather APIs, such as OpenWeatherMap, and guide you through obtaining an API key. Additionally, I will show you a  code examples and its output.

### Time required for the talk

10-15 min

### Link to slides/demos

https://drive.google.com/file/d/1G-L_LNZpCaCYnU7D2y4m1i5juGDYVx6f/view?usp=sharing

### About you

I am an aspiring software developer currently pursuing a Bachelor of Commerce (BCom) degree. My expertise includes JavaScript, PHP  and Python, where I have developed both frontend and backend applications. I'm constantly expanding my skill set by learning new technologies, such as Postman API, to enhance my proficiency in working with APIs .My passion for coding and continuous learning drives me to stay updated with the latest tools and technologies in the field of software development.
I am excited to share my knowledge in front of you and want to contribute ahead.

### Availability

19/10/24

**Comment by Schefflera-Arboricola** [comment]
Thank you for submitting this proposal, @muskan168. I appreciate the effort you've put into it, and I'd like to offer a few suggestions to enhance your presentation:

1. Code in slides: While showing code can be effective, it’s important to balance the amount of code displayed with the overall flow of the talk. Extensive blocks of code might overwhelm the audience, especially within a short timeframe. Based on my experience, for short format talks, it's generally better to focus more on the core message first and then go onto the code. But, it's your talk so you probably know the best way to present it :)
   
2. Real-Time Demonstration: Rather than relying solely on static screenshots, consider incorporating a live demonstration of the final result. This will make your talk more engaging and give the audience a more dynamic understanding of how the API works in real-time. Seeing a live output can be much more compelling than static slides.

3. Broader API Application: Instead of focusing solely on one specific API, aim to provide a broader understanding of how APIs work in general. I think the goal is to ensure that after your talk, attendees will have the foundational knowledge to work with any API, not just the one you demonstrate. You could emphasize best practices for API integration and how to handle common challenges such as authentication, error handling, and rate limiting.

4. Security Best Practices: Lastly, it's important to highlight security concerns when dealing with APIs. I noticed that you included an API key in your slides. Be sure to advise your audience on keeping their API keys secure, as public exposure of keys can lead to misuse. If the key in your slides is real, I'd recommend removing it and regenerating a new one.

5. Your talk timing (10-15 minutes) is appropriate for the material you're covering, but make sure to leave some room for a quick Q&A session at the end, or add some hooks in your talk that would make people come and talk to you after the talk.

6. Consider adding some pre-requisites or suggested reading materials so that the audience can come prepared and engage more actively.

I hope these suggestions help refine your presentation.

Best of luck!

**Comment by muskan168** [comment]
> Thank you for submitting this proposal, @muskan168. I appreciate the effort you've put into it, and I'd like to offer a few suggestions to enhance your presentation:
> 
> 1. Code in slides: While showing code can be effective, it’s important to balance the amount of code displayed with the overall flow of the talk. Extensive blocks of code might overwhelm the audience, especially within a short timeframe. Based on my experience, for short format talks, it's generally better to focus more on the core message first and then go onto the code. But, it's your talk so you probably know the best way to present it :)
> 2. Real-Time Demonstration: Rather than relying solely on static screenshots, consider incorporating a live demonstration of the final result. This will make your talk more engaging and give the audience a more dynamic understanding of how the API works in real-time. Seeing a live output can be much more compelling than static slides.
> 3. Broader API Application: Instead of focusing solely on one specific API, aim to provide a broader understanding of how APIs work in general. I think the goal is to ensure that after your talk, attendees will have the foundational knowledge to work with any API, not just the one you demonstrate. You could emphasize best practices for API integration and how to handle common challenges such as authentication, error handling, and rate limiting.
> 4. Security Best Practices: Lastly, it's important to highlight security concerns when dealing with APIs. I noticed that you included an API key in your slides. Be sure to advise your audience on keeping their API keys secure, as public exposure of keys can lead to misuse. If the key in your slides is real, I'd recommend removing it and regenerating a new one.
> 5. Your talk timing (10-15 minutes) is appropriate for the material you're covering, but make sure to leave some room for a quick Q&A session at the end, or add some hooks in your talk that would make people come and talk to you after the talk.
> 6. Consider adding some pre-requisites or suggested reading materials so that the audience can come prepared and engage more actively.
> 
> I hope these suggestions help refine your presentation.
> 
> Best of luck!





Thanks for  your valuable suggestions @Schefflera-Arboricola  and the additional points you shared with me. They have been very helpful in identifying areas where I can improve the presentation.

I wanted to check with you—should I revise the proposal based on these changes and resubmit it, or would you prefer that I take a different approach or consider something else?

I look forward for your guidance.

**Comment by Animesh-Ghosh** [comment]
> > Thank you for submitting this proposal, @muskan168. I appreciate the effort you've put into it, and I'd like to offer a few suggestions to enhance your presentation:
> > 
> > 1. Code in slides: While showing code can be effective, it’s important to balance the amount of code displayed with the overall flow of the talk. Extensive blocks of code might overwhelm the audience, especially within a short timeframe. Based on my experience, for short format talks, it's generally better to focus more on the core message first and then go onto the code. But, it's your talk so you probably know the best way to present it :)
> > 2. Real-Time Demonstration: Rather than relying solely on static screenshots, consider incorporating a live demonstration of the final result. This will make your talk more engaging and give the audience a more dynamic understanding of how the API works in real-time. Seeing a live output can be much more compelling than static slides.
> > 3. Broader API Application: Instead of focusing solely on one specific API, aim to provide a broader understanding of how APIs work in general. I think the goal is to ensure that after your talk, attendees will have the foundational knowledge to work with any API, not just the one you demonstrate. You could emphasize best practices for API integration and how to handle common challenges such as authentication, error handling, and rate limiting.
> > 4. Security Best Practices: Lastly, it's important to highlight security concerns when dealing with APIs. I noticed that you included an API key in your slides. Be sure to advise your audience on keeping their API keys secure, as public exposure of keys can lead to misuse. If the key in your slides is real, I'd recommend removing it and regenerating a new one.
> > 5. Your talk timing (10-15 minutes) is appropriate for the material you're covering, but make sure to leave some room for a quick Q&A session at the end, or add some hooks in your talk that would make people come and talk to you after the talk.
> > 6. Consider adding some pre-requisites or suggested reading materials so that the audience can come prepared and engage more actively.
> > 
> > I hope these suggestions help refine your presentation.
> > 
> > Best of luck!
> 
> 
> 
> 
> 
> Thanks for  your valuable suggestions @Schefflera-Arboricola  and the additional points you shared with me. They have been very helpful in identifying areas where I can improve the presentation.
> 
> I wanted to check with you—should I revise the proposal based on these changes and resubmit it, or would you prefer that I take a different approach or consider something else?
> 
> I look forward for your guidance.
> 

Hey @muskan168 just updating the original comment with the updated slides should suffice.

**Comment by Schefflera-Arboricola** [comment]
> Hey @muskan168 just updating the original comment with the updated slides should suffice.

Also, the slides don't have to be finalised right now. You can work on the flow of your talk until the last minute :P

But these were just some points I thought might help you improve your proposal and hence your talk. But don't break your head too much on these points; it's your talk; keep it authentic; and just have fun :)

**Comment by muskan168** [comment]
> > > Thank you for submitting this proposal, @muskan168. I appreciate the effort you've put into it, and I'd like to offer a few suggestions to enhance your presentation:
> > > 
> > > 1. Code in slides: While showing code can be effective, it’s important to balance the amount of code displayed with the overall flow of the talk. Extensive blocks of code might overwhelm the audience, especially within a short timeframe. Based on my experience, for short format talks, it's generally better to focus more on the core message first and then go onto the code. But, it's your talk so you probably know the best way to present it :)
> > > 2. Real-Time Demonstration: Rather than relying solely on static screenshots, consider incorporating a live demonstration of the final result. This will make your talk more engaging and give the audience a more dynamic understanding of how the API works in real-time. Seeing a live output can be much more compelling than static slides.
> > > 3. Broader API Application: Instead of focusing solely on one specific API, aim to provide a broader understanding of how APIs work in general. I think the goal is to ensure that after your talk, attendees will have the foundational knowledge to work with any API, not just the one you demonstrate. You could emphasize best practices for API integration and how to handle common challenges such as authentication, error handling, and rate limiting.
> > > 4. Security Best Practices: Lastly, it's important to highlight security concerns when dealing with APIs. I noticed that you included an API key in your slides. Be sure to advise your audience on keeping their API keys secure, as public exposure of keys can lead to misuse. If the key in your slides is real, I'd recommend removing it and regenerating a new one.
> > > 5. Your talk timing (10-15 minutes) is appropriate for the material you're covering, but make sure to leave some room for a quick Q&A session at the end, or add some hooks in your talk that would make people come and talk to you after the talk.
> > > 6. Consider adding some pre-requisites or suggested reading materials so that the audience can come prepared and engage more actively.
> > > 
> > > I hope these suggestions help refine your presentation.
> > > Best of luck!
> > 
> > 
> > Thanks for  your valuable suggestions @Schefflera-Arboricola  and the additional points you shared with me. They have been very helpful in identifying areas where I can improve the presentation.
> > I wanted to check with you—should I revise the proposal based on these changes and resubmit it, or would you prefer that I take a different approach or consider something else?
> > I look forward for your guidance.
> 
> Hey @muskan168 just updating the original comment with the updated slides should suffice.

sure @Animesh-Ghosh

**Comment by muskan168** [comment]
> > Hey @muskan168 just updating the original comment with the updated slides should suffice.
> 
> Also, the slides don't have to be finalised right now. You can work on the flow of your talk until the last minute :P
> 
> But these were just some points I thought might help you improve your proposal and hence your talk. But don't break your head too much on these points; it's your talk; keep it authentic; and just have fun :)

Okay thanks for your suggestions , this is helpful for me!

**Comment by pulsar17** [comment]
@Schefflera-Arboricola @Animesh-Ghosh can this be added to the roster of accepted talks?
Also, is it a lightning talk or a regular one?

**Comment by Schefflera-Arboricola** [comment]
It's an interesting topic and I think it can be added as an lightening talk. But, if @muskan168 wants to make it a more broader talk on APIs(as suggested in the above feedback) then it would also be a good fit for a 20-min talk. I think @muskan168 can tell it better if they want to give it as a 5min lightening talk or if they have enough material to give it as a 20-min talk.

**Comment by muskan168** [comment]
> It's an interesting topic and I think it can be added as an lightening talk. But, if @muskan168 wants to make it a more broader talk on APIs(as suggested in the above feedback) then it would also be a good fit for a 20-min talk. I think @muskan168 can tell it better if they want to give it as a 5min lightening talk or if they have enough material to give it as a 20-min talk.

Thanks for the feedback @Schefflera-Arboricola ! I'm comfortable with both types of talks, whether it's a 5-minute lightning talk or a 20-minute broader discussion. But my current topic is "Fetching Current Weather Using an API," where I briefly cover how APIs work in the context of retrieving weather data. However, as you suggested, I can broaden the scope to give a more comprehensive talk about APIs, which would shift my topic to covering concepts and examples related to APIs. 
So I think that it would be better that i give a lightning talk this time so I can get a exposure how it will experience. My talk duration will be max 5-10 min .Let me know your preference.

**Comment by Schefflera-Arboricola** [comment]
Thank you for the great talk @muskan168 :) 
Hope to see you at the coming meet-ups!

Feel free to submit more talk proposals :)
