### ISSUE TITLE
Reptilia Amazon: deploy django app on AWS lightsail

### ISSUE THREAD

**Issue by rpsmaini** [pydelhi/talks#298]
### Title

Deploy your django applications on AWS lightsail service

### Describe your Talk

In this session I will be discussing about aws lightsail and how you can deploy your django app on the lightsail server.

### Pre-requisites & reading material

A bit of Django and AWS knowledge is recommended but not compulsory

### Time required for the talk

30mins

### Link to slides/demos

https://docs.google.com/presentation/d/1rfusIYCQ814twSsrAq9mqQc8ktu_j7TQ23kNlg7zpuc/edit?usp=sharing

### About you

https://www.linkedin.com/in/rpsmaini/

### Availability

16/11/2024

**Comment by Schefflera-Arboricola** [comment]
Thank you @rpsmaini for submitting your proposal. Could you please provide some more details like, what exactly would be the flow of your talk, who would benefit from it or how this will be valuable to the PyDelhi community, or how you'll present the topic-- like a tutorial or presentation? Additionally, please clarify any specific pre-requisites for the audience, like familiarity with AWS, Django, or app development, etc. This would really help us better understand and review your proposal.

Thank you :)

**Comment by pulsar17** [comment]
Hi @rpsmaini we'd like to confirm the talks for this month. Could you please address the things mentioned above by @Schefflera-Arboricola ?

Also, the slots this month are 20 mins. Is it possible for you to squeeze your talk to fit that? If not we can consider the talk for next month's meetup.

**Comment by rpsmaini** [comment]
Hi there, thank you for reaching out to me. Unfortunately, I am unable to give my talk this time I have some commitments clashing with each other. You may push my slot to the next meetup. Thank you

**Comment by Animesh-Ghosh** [comment]
Leaving it as Re-Opened for now.

**Comment by rpsmaini** [comment]
hi there
I want to give my talk on upcoming meetup

**Comment by rpsmaini** [comment]
> Thank you @rpsmaini for submitting your proposal. Could you please provide some more details like, what exactly would be the flow of your talk, who would benefit from it or how this will be valuable to the PyDelhi community, or how you'll present the topic-- like a tutorial or presentation? Additionally, please clarify any specific pre-requisites for the audience, like familiarity with AWS, Django, or app development, etc. This would really help us better understand and review your proposal.
> 
> Thank you :)

In this session I will talk about how fast you can deploy your Django applications on AWS light sail server and what are the benefits of using this approach, How my django application works in lightsail.

**Comment by Animesh-Ghosh** [comment]
Hi @rpsmaini, could you update your proposal with the link to your slides?

**Comment by rpsmaini** [comment]
Ok so just to be clear, I only have to upload slides right?

**Comment by rpsmaini** [comment]
https://docs.google.com/presentation/d/1rfusIYCQ814twSsrAq9mqQc8ktu_j7TQ23kNlg7zpuc/edit?usp=sharing
here's the link to my slides

**Comment by agriyakhetarpal** [comment]
Thanks, @rpsmaini! The slides are minimal and look good to me. I'm assuming that your demo/showcase will consume the rest of the time for your presentation. I'll mark this as "accepted" for now.

Could you re-confirm your availability for the 16th? Reiterating that the venue is the Thoughtworks office, Gurugram and the timings are 12pm–5pm.

**Comment by rpsmaini** [comment]
Yes I completely confirm that I am available on 16th of November for the pydelhi meetup held at  Thoughtworks office, Gurugram and the timings are 12pm–5pm.

**Comment by agriyakhetarpal** [comment]
Excellent, thank you again!
