### ISSUE TITLE
Proposal: Moving from Django to Pyramid - Lessons Learned

### ISSUE THREAD

**Issue by psjinx** [pydelhi/talks#3]
**Topic:  Moving from Django to Pyramid - Lessons Learned**
**Date: August 8, 2015**
**Pre-requisite:**  Good familiarity with any web framework written in Python.
**My Background** - I've used [Django](https://docs.djangoproject.com/) for almost 4 years (`v1.2` to `v1.6`). In July, 2014 I switched to [Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/latest/) for all the new web apps.
**Description** - Django makes life of a web-developer very easy because of it's awesome documentation, [3rd party packages](https://www.djangopackages.com/) and community. And, building pluggable apps in Django is very easy because it's opinionated. But there are [ some pros and cons of](http://qr.ae/RYNE2Y)  opinionated web application frameworks:
> **Pro:**
> An opinionated framework can save time and effort for most of its target market of developers/engineers.
>
> **Con:**
> An opinionated framework can waste a lot of time for some people.﻿

I'll share my experience with Pyramid after using it for 1 year.

I'm working on the presentation and an example project in Pyramid which has a polling app (same as Django tutorial), user authentication, admin, REST API and tests. I'll share it by tomorrow night.

**Comment by psjinx** [comment]
Presentation (still work in progress) - https://docs.google.com/presentation/d/1RgJzsiv5PJVmAM_57X6nSCx9Ga1GpP9Y13Rn8GiK_7s/edit?pli=1

**Comment by toanant** [comment]
:+1:

**Comment by bhanuvrat** [comment]
+1

**Comment by akshayaurora** [comment]
:+1:

**Comment by theskumar** [comment]
:+1:

**Comment by CuriousLearner** [comment]
:+1:

**Comment by theskumar** [comment]
Finalised for 8th August. This issue should be closed after talk info get added to `README.md`

@psjinx it would wonderful, if you can send a pull-request this repo, adding the relevant relevant details to `REAMDE.md` for all our future audiences. Thanks.

**Comment by theskumar** [comment]
Video processed and uploaded at https://www.youtube.com/watch?v=a2Llc1EGGA4 

closing this now.
