### ISSUE TITLE
Empowering Machine Learning with Python: From Data to Decisions!

### ISSUE THREAD

**Issue by dashish703** [pydelhi/talks#304]
### Title

Empowering Machine Learning with Python: From Data to Decisions!

### Describe your Talk

In this 10-minute talk, we'll explore how Python has revolutionized machine learning, enabling developers to turn raw data into actionable insights. As an ML Python Developer, I'll walk you through the power of Python’s libraries like Scikit-Learn, TensorFlow, and Pandas, highlighting how these tools streamline the process of data preprocessing, model building, and deployment. Whether you're a beginner or a seasoned tech enthusiast, discover how Python makes machine learning more accessible, flexible, and impactful for real-world applications. Get ready to dive into the world of machine learning with Python!

### Time required for the talk

10 minutes!

### Link to slides/demos

https://www.canva.com/design/DAGZqVqfBVY/hWL74zEDBpS8F6FeyO5kFA/edit

### About you

A ML developer... who recently completed his learning in cybersecurity. And trying to make fusion between ML and security which conclude to ML+Security!

### Availability

16/11/24

**Comment by Animesh-Ghosh** [comment]
Hi @dashish703, could you update the link to the slides in the proposal? Thanks!

**Comment by Animesh-Ghosh** [comment]
Hi @dashish703 would you be able to deliver your talk this Saturday on the 21st of Dec?

**Comment by dashish703** [comment]
Yes sure!

**Comment by Animesh-Ghosh** [comment]
Please update the link to your slides in the original comment. Thanks!

**Comment by dashish703** [comment]
Ok!

**Comment by dashish703** [comment]
Also can u share the event details!

**Comment by Animesh-Ghosh** [comment]
@dashish703 I've mentioned the dates already.

Tentative timings are 1-5 PM.

I'll be sharing the meetup link for RSVPs on the Telegram and WhatsApp groups soon, which will have the location.

**Comment by dashish703** [comment]
Can u share me the WhatsApp group link!

**Comment by agriyakhetarpal** [comment]
This should be it: https://chat.whatsapp.com/DFaT2HSZVfOBocqP4Bob4j

**Comment by dashish703** [comment]
Hi @Animesh-Ghosh here's the link to my ppt!
https://www.canva.com/design/DAGZqVqfBVY/hWL74zEDBpS8F6FeyO5kFA/edit

**Comment by Animesh-Ghosh** [comment]
Thanks @dashish703 for the talk!

**Comment by dashish703** [comment]
Thank you 😊
