### ISSUE TITLE
Migrating from unittest to pytest : Pytest's syntactic sugars, community extensions, and my GSoC project

### ISSUE THREAD

**Issue by prady0t** [pydelhi/talks#307]
### Title

**Migrating from unittest to pytest**: Pytest's syntactic sugars, community extensions, and my GSoC project

### Describe your Talk

- Covered about my GSoC project where I migrated [PyBaMM's](https://github.com/pybamm-team/PyBaMM) unittest testing suit to pytest.
- Talk covers things such as pytest's advantages over unittest, about [pytestify](https://github.com/dannysepler/pytestify), and how we can migrate to pytest.
- Will also talk about my experience working as a GSoC student and being a part of other open-source mentorship programs.

### Pre-requisites & reading material

GSoC completion blog : https://prady0t.github.io/My-Blog/posts/gsoc-final/

### Time required for the talk

20-25 min

### Link to slides/demos

https://docs.google.com/presentation/d/1XFT47iWfJjHi6xHqsUstYCSFYZfs4HLIrnwoYQuh3Ms/edit?usp=sharing

### About you

Hi, My name is Pradyot. I'm a final year student. I'm currently working as a LFX mentee for KubeArmor (CNCF project). I've previously been a GSoC student at NumFOCUS and as a SoK mentee at KDE. I really like working with open-source tech and am enthusiast about scientific python projects.

### Availability

16/11/2024

### Any comments

Demo is just 5 min of me showcasing how pytestify can be used to convert to pytest code, also how to improve it, since it has lot of bugs and is left unmaintained.

**Comment by agriyakhetarpal** [comment]
As Pradyot's mentor for the GSoC programme this year, I encouraged him to submit a proposal here – my short answer for this is that I'd gladly accept this as a thirty-minute talk and I can affirm that the contents will be useful for the audience :) I've shared some feedback in direct messages with Pradyot already, and I'll ask others to pitch in in case they have more to say.

**Comment by Animesh-Ghosh** [comment]
Nice Monty Python reference in the first slide @prady0t :love_you_gesture: 

My suggestions are quite generic:
1. Break down the slides. A few of them have too much content, and might distract the audience from your delivery of the talk. Consider moving some pointers to speaker notes if they don't need to be read by the audience and are only needed by you to give context to the content.
2. Code samples in the slides need to have better legibility.  Unittest v/s Pytest slide :white_check_mark:  but Fixtures slide :x:

We can confirm the talk based on your availability @prady0t.

**Comment by prady0t** [comment]
@Animesh-Ghosh Thanks for noticing 😄 

Thanks for the suggestions. I'll make the necessary changes. I'll be available on the 16th of this month at any time slot.

**Comment by Daksh777** [comment]
Hey @prady0t, are you okay with your photo being posted on our socials?
If yes, please share your photo

**Comment by prady0t** [comment]
Yes sure. You can use this photo: https://drive.google.com/file/d/1xArnDxhmNgjqyySBtnyNl_yQkb1ORrJq/view?usp=sharing

**Comment by Daksh777** [comment]
Awesome, thank you!
