### ISSUE TITLE
From Good to Great: Transforming Django Admin for Maximum Productivity

### ISSUE THREAD

**Issue by notnotrachit** [pydelhi/talks#310]
### Title

From Good to Great: Transforming Django Admin for Maximum Productivity

### Describe your Talk

Discover how to turn Django Admin into a powerful productivity tool. This talk will cover key customization techniques, advanced filters, and time-saving actions to optimize Django Admin for any project. Learn practical tips to streamline data management, improve usability, and make the most of Django’s built-in features—whether you're building a quick prototype or managing a complex application. Perfect for Django developers of all levels looking to boost their workflow efficiency.

### Time required for the talk

15-20 mins

### About you

I am a full stack developer who loves to build projects using django. I am also the FOSS Club lead for Bennett University Chapter. 

My Links:
[Portfolio](https://www.rachitkhurana.tech/)
[LinkedIn](https://www.linkedin.com/in/rachitkhurana1)
[X](https://x.com/notnotrachit)
[GitHub](https://github.com/notnotrachit)

### Availability

16/11/2024

**Comment by Daksh777** [comment]
Hey @notnotrachit 
Do you have any slides to your talk?

**Comment by notnotrachit** [comment]
No, not right now.

**Comment by Daksh777** [comment]
No worries
Could you give a little more detailed overview of the talk please?

**Comment by notnotrachit** [comment]
My talk will include :
- A brief overview of django admin
- How you can customize the fields and page of a django admin
- Different ways to customise:
    - Custom list display
    - search_fields, list filters, ordering
    - TabularInline & StackedInline
    - readonly_fields
    - Custom Actions
    etc...

**Comment by Daksh777** [comment]
Could you please share your slides by today EOD?
The overview looks good, but we'd love to go through the final content once

Also do note that there will be students who aren't that familiar with Django, so you should start with a little basics of Django Admin as well :)

**Comment by notnotrachit** [comment]
This is the link for the slides. ( These are still work in progress)

https://www.canva.com/design/DAGWVuxDNI8/-ktsxm5VZfzg00yOsGezsw/view?utm_content=DAGWVuxDNI8&utm_campaign=designshare&utm_medium=link&utm_source=editor

**Comment by agriyakhetarpal** [comment]
Thanks for sharing the slides, @notnotrachit, they are looking great so far! :) Could you please re-confirm your availability for Saturday, 12:50pm–1:10pm? We've been allocated space at the Thoughtworks office in Gurugram ([link to the agenda on Meetup](https://www.meetup.com/pydelhi/events/304341342/)). We might be able to switch the times around a bit in case this time doesn't work for you, please let us know if needed.

**Comment by notnotrachit** [comment]
Yes, I will be available
