### ISSUE TITLE
Application Architecture and Database Scaling

### ISSUE THREAD

**Issue by vermastuti** [pydelhi/talks#312]
### Title

Application Architecture and Database Scaling

### Describe your Talk

Application architecture and database scaling are critical aspects of software development that require meticulous strategy. The most effective approach depends on application's specific requirements and constraints. In this talk, we will discuss about methods and when to use them for scaling the application.

### Pre-requisites & reading material

N/A

### Time required for the talk

45 minutes 

### Link to slides/demos

https://docs.google.com/presentation/d/1djLxVLrFmmasOjB70GHSKHjrwVmk_piQfsvKz-9_9CI/edit

### About you

8+ years of work experience in software engineering building apis and architecture

Building products from scratch to scale for B2B businesses

Worked at a unicorn startup for acquisition integrations in technology

6 years with Women Who Code Delhi (co-director)

### Availability

16/11/2024

**Comment by vermastuti** [comment]
Hey Daksh, Thanks! 

I'll try to remove some slides to keep it for 20 minutes and 5 minutes for Q&A. This should work for the event👍🏼

**Comment by Daksh777** [comment]
Sounds great!
Are you okay with your photo being posted on our socials?
If yes, please share your photo

**Comment by Daksh777** [comment]
Also, could you share your photo? We'll post it on our socials

**Comment by vermastuti** [comment]
Sure, could you share email id?

**Comment by Daksh777** [comment]
Texting you on WhatsApp instead!
