### ISSUE TITLE
Talk Proposal - Assistant - Thread Architecture GenAI

### ISSUE THREAD

**Issue by aditijain-11** [pydelhi/talks#313]
### Title

Assistant - Thread Architecture GenAI

### Describe your Talk

1. The talk titled "Assistant - Thread Architecture for Chatbot OpenAI" would delve into how OpenAI's thread-based architecture is leveraged to build advanced, context-aware chatbots.
2.  It would focus on how threads allow for managing multi-turn conversations, maintaining context across interactions etc. Key areas would include how threads enable scalability, managing cost, and modular design for chatbot systems. 
3. The session would also cover practical examples, challenges faced in implementation, and how this architecture optimizes performance for complex conversational workflows.

This architecture have been implemented in Health Assistant of Tata 1mg Health Records app and will also share challenges building this functionality

### Pre-requisites & reading material

Source of truth - https://platform.openai.com/docs/assistants/overview

### Time required for the talk

10-12mins

### Link to slides/demos

https://docs.google.com/presentation/d/1fjpNOcLcaJuEOeZfEheG0BLbqlpgRhEGRP40ALwJkDQ/edit?usp=sharing

### About you

Hi I am Aditi Jain, Backend Engineer-1 at Tata 1mg, I am really passionate about Applications of ML/AI and am a Backend Nerd
can connect with me @ https://www.linkedin.com/in/aditijan1100/

### Availability

21/12/24

**Comment by Animesh-Ghosh** [comment]
Hi @aditijain-11, please update the original comment with the link to your talk's slides.

We'd be able to review it then.

Thanks!

**Comment by Schefflera-Arboricola** [comment]
Hi @aditijain-11 , thank you for submitting this talk proposal!

The slides LGTM. But, I think this topic can take more time than what you have mentioned. Would you be open to making it a 25-30 min talk instead? Also please make sure to mention the pre-requisites above.

Thank you :)

**Comment by agriyakhetarpal** [comment]
Thanks, @aditijain-11! The slides and content look good to me. I'll accept this talk for the meetup on 21/12/2024 (subject to others' comments); do you have a preference for the time?

One request: could you convert the slides (and the code snippets) to light mode if that's possible for you? Dark mode presentations usually pose negative accessibility implications, and we've found that those in light mode tend to fare better.

**Comment by aditijain-11** [comment]
@agriyakhetarpal  I have converted slides into light mode, thanks for the heads up, also i'll be comfortable with any slot in second half if that's possible
@Schefflera-Arboricola I think this talk will take 15-20 mins, rest I am expecting QnA will also take up some time?

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk @aditijain-11!
