### ISSUE TITLE
Working with ChatGPT, Mistral, Claude, Llama all with one API.

### ISSUE THREAD

**Issue by ilavanyajain** [pydelhi/talks#314]
### Title

Tracing Multi Agent Capabilities with LangDB using One API.

### Describe your Talk

Ever had the trouble of managing different LLMs subscriptions, and maintaining API key for each of them. Well, LangDB has come with the solution of solving this problem. One API Key that runs for all the LLMs out there. 

In this talk/workshop, I will explore the core advantages of building, and deploying your RAG/LLM applications using LangDB and Python. I'll also cover the aspects of integrating LangChain into your local machine using Runpod/vLLM with LangDB.

The talk is favorable for everyone who's :

-- Pythonista
-- Worked with LLM (be it basic prompt writing, doesn't matter)
-- Favourable with basic API fundamentals 
-- Girth to withstand 30 minutes of fun and interactive workshop
-- Looking to get free credits.

### Time required for the talk

30 mins

### About you

Hi. This is Lavanya Jain, a junior undergrad @JIIT. I am a python developer and have worked with the DRDO on a project. Recently, I have joined langdb.ai as a DevRel engg. I am a people's person who loves to connect and talk with different groups of people. I have worked in several communities, and have volunteered at PyCon India 2024. Open Source Contributor for TensorFlow.

### Availability

21/12/2024

**Comment by Animesh-Ghosh** [comment]
Hey @ilavanyajain, thanks for the talk proposal.

Please put up a link to your slides in the original comment for @agriyakhetarpal, @Schefflera-Arboricola and others to review.

Thanks!

**Comment by Animesh-Ghosh** [comment]
Thanks for the talk @ilavanyajain!
