### ISSUE TITLE
Proposal: Contributing to Mozilla Marionette & Firefox UI Tests using Python

### ISSUE THREAD

**Issue by CuriousLearner** [pydelhi/talks#33]
Marionette is an automation driver for the gecko engine to write UI tests. 
With Marionette, one can replicate user actions and control either UI/JS of Gecko platform. This includes both the visible content of the page (content context) or the elements of the menu/ functions (chrome context).

In this talk, I'll be explaining it's usage in Firefox/Firefox OS explaining about Marionette & a little about Firefox Puppeteer. I hope with the basic knowledge of these, people would be able to contribute to Mozilla Firefox.

__Pre-requisites:__
Basic knowledge of writing and executing test cases using pytest/unittest or any other framework.

Note: Slides would be updated soon.

**Comment by theskumar** [comment]
@CuriousLearner details please.

**Comment by CuriousLearner** [comment]
Marionette is an automation driver for the gecko engine to write UI tests. 
With Marionette, one can replicate user actions and control either UI/JS of Gecko platform. This includes both the visible content of the page (content context) or the elements of the menu/ functions (chrome context).

In this talk, I'll be explaining it's usage in Firefox/Firefox OS explaining about Marionette & a little about Firefox Puppeteer. I hope with the basic knowledge of these, people would be able to contribute to Mozilla Firefox.

Pre-requisites: 
Basic knowledge of writing and executing test cases using pytest/unittest or any other framework.

Note: Slides would be updated soon.
Let me know if you want more details. @theskumar

**Comment by theskumar** [comment]
@CuriousLearner this proposal is good to go. can you get is updated on meetup page? maybe be add link back to this issue for detail about the talk, followup by participants, etc. 

Send a PR with slides/recorded talks, etc when after talk is delivered. 

Cheers, best of luck! 👍

**Comment by theskumar** [comment]
Talk added to https://www.meetup.com/pydelhi/events/232105313/

**Comment by CuriousLearner** [comment]
Thanks @theskumar! I'll update with the slides soon :)

**Comment by sourabhtk37** [comment]
Mark this as delivered. Please.
