### ISSUE TITLE
Anthropology of FOSS in India

### ISSUE THREAD

**Issue by jasminefolz** [pydelhi/talks#36]
I would like to give a short talk about my phd research and solicit volunteers for my project. About me:
Jasmine Folz is an American/Canadian citizen doing her Ph. D. in Anthropology in the University of Manchester (UK) on the subject of FOSS in India. She is hosted as a Visiting Researcher at the AU-KBC Research Centre in Chennai for her field work for one year, March 2016 to Feb 2017. Some more info on her is available at: jfolz.org
As a part of her fieldwork , Jasmine has been traveling to different parts of India to meet persons who have been leading/promoting FOSS in India in various ways. She plans to be in Delhi December 12-19 and would like to meet up with FOSS folks for interviews.

**Comment by akshayaurora** [comment]
@jasminefolz thanks for the talk. 

@theskumar Talk has been delivered on our December Meetup. This issue can be closed.
