### ISSUE TITLE
Proposal: Lets talk about "GIL"

### ISSUE THREAD

**Issue by aktech** [pydelhi/talks#37]
I will be talking about Global-Interpreter-Lock (GIL) in Python. It's a mutex that prevents multiple native threads from running in parallel. In essence, this says that a python program cannot do more than one thing at once via threading.

**Comment by akshayaurora** [comment]
@aktech can you talk about it this meetup on 21Jan IIM Campus ?

**Comment by aktech** [comment]
Yes, works for me.

**Comment by akshayaurora** [comment]
Delivered.
