### ISSUE TITLE
Proposal: Is Random.py  "Random"??? 

### ISSUE THREAD

**Issue by aniketmaithani** [pydelhi/talks#38]
- What is Random?
- Defining Random?
- Diving into the source code lib/random.py 
- Talk Time 20 Mins [For beginners ] 
- Here is the link to the slide : https://drive.google.com/file/d/0B3LQS5ZvGd69RjFDNUtWUkMwVVU/view?usp=sharing :)

**Comment by akshayaurora** [comment]
@aniketmaithani would you be available to deliver this talk for the meetup on 21 Jan @ IIM Lucknow Noida Campus?

**Comment by aniketmaithani** [comment]
@akshayaurora I am not sure. I am in Bengaluru right now. Will update by 18th EOD :)

**Comment by akshayaurora** [comment]
@aniketmaithani slating this for 18th Feb Meetup in amity.

**Comment by aniketmaithani** [comment]
@akshayaurora sure. :)

**Comment by aniketmaithani** [comment]
@akshayaurora @theskumar you can mark this as delivered and close the issue. The link to the slide has been added on my topmost comment. :)

**Comment by theskumar** [comment]
@aniketmaithani if possible create a PR adding data to README.md with details. I'm marking this as delivered.

**Comment by aniketmaithani** [comment]
@theskumar already did that #43 :)
