### ISSUE TITLE
Proposal:  Async programming and real time features in python

### ISSUE THREAD

**Issue by shubh3794** [pydelhi/talks#39]
There are always some questions were related to realtime functionality - how it works, how to integrate realtime portion with conventional WSGI applications, how to structure application code and so on. Also with this talk I'd like to put some light on Greenlets and Gevents

**Comment by akshayaurora** [comment]
Seems like a interesting talk. Slating this for 18th Feb Amity Meetup.

**Comment by akshayaurora** [comment]
@shubh3794 can you confirm your availability for this meetup.

**Comment by shubh3794** [comment]
Sure. I am available.

**Comment by akshayaurora** [comment]
Perfect, meetup page updated with your talk.

**Comment by akshayaurora** [comment]
@shubh3794 can you upload some slides, details, requirements etc that people need to be ready with before hand.

**Comment by shubh3794** [comment]
@akshay Yes will do by tonight.

Warm regards
Shubham Aggarwal
+91-8447223459

**Comment by akshayaurora** [comment]
@shubh3794 could you please refresh my Memory ? Was this talk delivered ?
