### ISSUE TITLE
Proposal: Getting started with Kivy

### ISSUE THREAD

**Issue by amitt001** [pydelhi/talks#4]
**Topic: Getting started with Kivy**
**Date:**
**Description:** Kivy - Open source Python library for rapid development of applications
that make use of innovative user interfaces, such as multi-touch apps. Its Cross platform, Business Friendly and GPU Accelerated. [Kivy](http://kivy.org/)

---

- [ ] Date Confirmation.
- [ ] Presentation Review.

**Comment by theskumar** [comment]
@amitt001 Please add a link to slides asap, it is one of the pre-criteria for a talk to get selects. Also it will increase the likelihood to getting more upvotes. ;-) 

Add link to presentation/article in the description and also let everyone know, when you have done so by writing a comment.

**Comment by akshayaurora** [comment]
https://docs.google.com/presentation/d/1zoyqnnDqpXRPmZ1pLYu05cWMg-l9qt2657uGFozZWig

I will be holding the workshop, it is the same presentation I held on pylon last year https://in.pycon.org/funnel/2014/220-mobile-application-development-with-python-kivy/

**Comment by theskumar** [comment]
As discussed with @akshayaurora this proposal is for workshop and not for a 30mins talk. Let's move this to: https://github.com/pydelhi/workshops/issues

I'm closing this issue here.
