### ISSUE TITLE
Assertion in python

### ISSUE THREAD

**Issue by BhargavaAshish** [pydelhi/talks#40]
How to user assertion
Use Different type of assertion
using assertion in same class
use assertion in outside the class

**Comment by akshayaurora** [comment]
Can you give this talk on this upcoming meetup? @ Ramanujan College 25th February?

**Comment by BhargavaAshish** [comment]
I will confirm by tomorrow evening 4.00 PM 

    On Thursday, February 23, 2017 12:17 PM, Akshay Arora <notifications@github.com> wrote:
 

 Can you give this talk on this upcoming meetup? @ Ramanujan College 25th February?—

**Comment by BhargavaAshish** [comment]
Hi,
Due to  death in my family I will not be able to to make it.
Regards,Ashish Bhargava  

    On Thursday, February 23, 2017 2:14 PM, ashish bhargava <ashish_bhargava@yahoo.com> wrote:
 

 I will confirm by tomorrow evening 4.00 PM 

    On Thursday, February 23, 2017 12:17 PM, Akshay Arora <notifications@github.com> wrote:
 

 Can you give this talk on this upcoming meetup? @ Ramanujan College 25th February?—

**Comment by aktech** [comment]
@BhargavaAshish Would be able to confirm this for the next meetup on this Saturday, 29th April?

**Comment by BhargavaAshish** [comment]
Already have commitments for 29th april , but take up in next meet upRegards,Ashish Bhargava. 

    On Thursday, April 27, 2017 1:19 PM, Amit Kumar <notifications@github.com> wrote:
 

 @BhargavaAshish Would be able to confirm this for the next meetup on this Saturday, 29th April?—

**Comment by akshayaurora** [comment]
@BhargavaAshish can you deliver this talk on our upcoming meetup? 24th June?

**Comment by akshayaurora** [comment]
@BhargavaAshish still available? we have another opportunity on 22July meetup, let us know if you can take your talk up in that session.

**Comment by rajataaron** [comment]
@BhargavaAshish are you able to give your talk on our upcoming meetup on 16 Sept?

**Comment by CuriousLearner** [comment]
I'm closing this one. When you're ready for the talk, please feel free to re-open this.
