### ISSUE TITLE
"Propose a talk" on PyDelhi Page.

### ISSUE THREAD

**Issue by akshayaurora** [pydelhi/talks#41]
The PyDelhi.org page should have a link to. "Propose a talk" that takes them to https://github.com/pydelhi/talks/issues/new

**Comment by shakti4ranjan** [comment]
Working on Python with Visual Studio

**Comment by realslimshanky** [comment]
Fixing this issue and adding progress in this [PR](https://github.com/pydelhi/pydelhi.github.io/pull/33)

**Comment by rajataaron** [comment]
@realslimshanky status on this

**Comment by realslimshanky** [comment]
@rajat404 please checkout https://github.com/pydelhi/pydelhi.github.io/pull/33
