### ISSUE TITLE
Proposal: Celery with Python: The way to distribute and schedule millions of processes

### ISSUE THREAD

**Issue by KushagraB** [pydelhi/talks#45]
## Have a large codebase and lots of processes to run?
> Celery is a very powerful distributed tasks queue which helps your system schedule and executes multiple processes asynchronously.
-------------------------------------------------------------------------------------------------------------------------------------------
I plan to introduce the power and scope of Celery to novice/intermediate level Pythonistas.
Since this will be an introduction to celery, I will go with the beginner-level discussion and hands-on:
- List of message transport that we can use for celery.
- Creating tasks and scheduling them.
- Going through the transition through all the tasks happening in the celery.

**Comment by aktech** [comment]
Hey @KushagraB  thanks for the proposal. Would be able to confirm this for the next meetup on [Saturday, 1st April](https://www.meetup.com/pydelhi/events/235843440/) ?

**Comment by aktech** [comment]
Would be able to confirm this for the next meetup on this Saturday, 29th April?

**Comment by akshayaurora** [comment]
@KushagraB Hey, you available to give this on 15th May?

**Comment by akshayaurora** [comment]
Closing this cause of lack of response.
