### ISSUE TITLE
Proposal : Introduction to text classification

### ISSUE THREAD

**Issue by ishaan007** [pydelhi/talks#46]
Every text classification problem in NLP is broadly categorized as a document or a token level classification .This talk will be  devoted to document classification 

I will walk through a classification experiment I coded and will talk about the process and ins and outs of it.

This is a blog I wrote on all this
https://medium.com/towards-data-science/document-feature-extraction-and-classification-53f0e813d2d3#.lzi3u4t29

Code for the talk
https://github.com/ishaan007/vector_space_modelling

**Comment by ishaan007** [comment]
@theskumar @aniketmaithani  can anyone of you look into this talk proposal ?

**Comment by aktech** [comment]
Hey @ishaan007 thanks for the proposal. Would be able to confirm this for the next meetup on [Saturday, 1st April](https://www.meetup.com/pydelhi/events/235843440/) ?

**Comment by ishaan007** [comment]
Sure,dropped an email on dtu.amit@gmail.com ,kindly check !

**Comment by akshayaurora** [comment]
@aktech was this delivered?

**Comment by aktech** [comment]
> was this delivered?

Yes
