### ISSUE TITLE
Proposal: X things you can do to improve your python code right now.

### ISSUE THREAD

**Issue by dusual** [pydelhi/talks#48]
These days I am refactoring a python codebase that has lead to a lot of ideas on simple things that can improve a codebase in short amount of time. There is no tentative date or number I can give right now but I think I should have some 20-30 in next 2 months.

**Comment by akshayaurora** [comment]
@dusual Hey welcome back to NCR, would you be available to give this talk on our next meet-up?

13th May 2017, venue would probably be Ramanujan or Sarai.

**Comment by dusual** [comment]
@akshayaurora I am still compiling things for this talk. I think i should be ready in couple of weeks. But 13th may be too soon.

**Comment by Warlord77** [comment]
@dusual  can you deliver your talk on 27th May 2017
