### ISSUE TITLE
Proposal: Make Telegram Bot Using Python And Run On Your Phone

### ISSUE THREAD

**Issue by realslimshanky** [pydelhi/talks#49]
I'll be covering the use of telegram bot API from scratch.
* Telegram Bot API
* Making request and sending response to Bot
* Using Telegram-Python-Bot package
* Deploying bot on your smart phone
* Other options to deploy

Speaker's Profile
* Bio - http://shanky.xyz
* Slides - http://slides.com/realslimshanky/tbotpython 
* Previous Talk - https://www.youtube.com/watch?v=J6aZlUzxL5w

**Comment by akshayaurora** [comment]
@realslimshanky can you deliver this talk on 24th June?

**Comment by realslimshanky** [comment]
@akshayaurora yes. I'm all prepared.

**Comment by theskumar** [comment]
@realslimshanky Is this talk delivered, if so would you mine sending a pull-request updating README.md with details. Thanks.

**Comment by theskumar** [comment]
Delivered @ https://www.meetup.com/pydelhi/events/238176680/

**Comment by realslimshanky** [comment]
@theskumar done. I've added the updated the README.md in PR #54
