### ISSUE TITLE
Awesome features in Mercurial, a version control system in Python

### ISSUE THREAD

**Issue by Pulkit07** [pydelhi/talks#50]
This will be a talk on features like revsets, filesets, phases, history editing eatures like evolve, absorb, etc. which are extremely useful for programmers. This will also cover why organisations like Facebook, Mozilla and others uses Mercurial.

**Comment by akshayaurora** [comment]
@Pulkit07 can you deliver this talk in our upcoming meetup this Saturday 24th ?

**Comment by Pulkit07** [comment]
@akshayaurora sorry I have some other commitments this weekend.

**Comment by aktech** [comment]
@Pulkit07 would you like to deliver this talk on the next meetup on [Saturday, July 8, 2017](https://www.meetup.com/pydelhi/events/238176683/) ?

**Comment by Pulkit07** [comment]
@aktech Yeah sure.

**Comment by aktech** [comment]
Cool! I have added your talk [here](https://www.meetup.com/pydelhi/events/238176683/). See you at the meetup.

**Comment by sourabhtk37** [comment]
@Pulkit07 please add your slides and(or) code of the talk here.
