### ISSUE TITLE
Talk : Ethereum Blockchain

### ISSUE THREAD

**Issue by amitkumarj441** [pydelhi/talks#51]
This talk comprises of basic introduction to Blockchain and Ethereum dealing with development framework and quick testing environment for Blockchain.

:e-mail: Agenda :

  - Blockchain Philosophy
  - Bitcoin
  - Ethereum 
  - Difference b/w Bitcoin & Ethereum
  - Basic concepts in Ethereum
  - Supporting tools for Ethereum
  - Developing Framework
  - Quick Testing environment for Blockchain

Speaker's Profile :

  - Bio : https://amitkumarj441.github.io
  - Slide : https://amitkumarj441.github.io/Presentation/Meetup/PyDelhi_17
  - Interview at [Blockchain Hackathon](https://twitter.com/campether): https://youtu.be/eXk29vQ0mHQ

**Comment by aktech** [comment]
Delivered.

**Comment by theskumar** [comment]
@aktech 🤘 

@amitkumarj441 thanks for the talk, we love to add the talk detail in our README.md for future records and reference. Possible you can create a pull-request with the details. I'm closing this issue for now. 

Cheers!!

**Comment by theskumar** [comment]
Tagging delivered @ https://www.meetup.com/pydelhi/events/238176680/
