### ISSUE TITLE
How to build a Web Crawler using Python

### ISSUE THREAD

**Issue by sahil811** [pydelhi/talks#56]
A lightening talk on Web Crawler using Python and Beautiful Soup.
This talk will involve building a web crawler using python and beautiful soup library. Talk will involve live demonstration for the same. Estimate time for this talk would be 30 minutes.

**Comment by aktech** [comment]
@sahil811 would you like to deliver this talk on the next meetup on [Saturday, July 8, 2017](https://www.meetup.com/pydelhi/events/238176683/)?

**Comment by sahil811** [comment]
Yes Sure !

**Comment by aktech** [comment]
Cool! I have added your talk [here](https://www.meetup.com/pydelhi/events/238176683/). See you at the meetup.

**Comment by sourabhtk37** [comment]
@sahil811 please provide the slides for this talk.

**Comment by sahil811** [comment]
@sourabhtk37 Sorry for the delay. Here is the slides for this talk 
[web crawlers ppt.pptx](https://github.com/pydelhi/talks/files/1134533/web.crawlers.ppt.pptx)

Also you can find the complete repository here : 
https://github.com/sahil811/Web-Crawler-using-Python
