### ISSUE TITLE
Getting Started with PySpark 

### ISSUE THREAD

**Issue by menikhilpandey** [pydelhi/talks#57]
I will be briefing about Hadoop, Spark and Big Data mechanism, RDDs, SQLContext, Dataframes. Hands-on with configuration, installation and basic usage of pyspark sql and mllib functions. These topics are extremely useful for programmers who are getting started with Machine Learning and Big Data architecture.

**Comment by shagunsodhani** [comment]
Hey @menikhilpandey how time do you think you would need for this. Also, this is kind of an advanced topic. It would be great if you could add some slides for it :). I did a talk on this topic in PyCon 2016. You might want to take a look at my [content](https://github.com/shagunsodhani/talks/tree/master/spark/PyCon2016).

**Comment by menikhilpandey** [comment]
hey @shagunsodhani I will need a 40 minutes long slot for this talk. I will share the slides with you tonight. Also, your content looks great.

**Comment by menikhilpandey** [comment]
Hi @shagunsodhani  I am preparing this talk for the next meetup. I would require a 40 minutes slot for the same. I will share the link of my content soon. Also, your content is awesome :)

**Comment by shagunsodhani** [comment]
Just to confirm, you are referring to the one on 8th July right?

**Comment by menikhilpandey** [comment]
No I am referring to the one on 22nd July.

**Comment by shagunsodhani** [comment]
Sure. Looking forward to your talk :smile:

**Comment by akshayaurora** [comment]
@menikhilpandey so you are up for the meetup on 22nd July? Just confirming before we put it on the meetup schedule.

**Comment by menikhilpandey** [comment]
Yes. I'll share the slides today.
