### ISSUE TITLE
Exploring Numpy

### ISSUE THREAD

**Issue by Tanya-Jain** [pydelhi/talks#58]
A lightning talk on Numpy, a Python library widely used for ML.
This talk will proceed from a brief introduction to get started with Numpy, to its application in solving matrices and pictorial representation of Mandelbrot and histograms. This talk would be ~30 minutes long.

**Comment by shagunsodhani** [comment]
Hey @Tanya-Jain. Can you do this in the [8th July Meetup](https://www.meetup.com/pydelhi/events/238176683/)?

**Comment by Tanya-Jain** [comment]
Yes, it would be possible for me.

**Comment by shagunsodhani** [comment]
I do see two slots on the [meetup page](https://www.meetup.com/pydelhi/events/238176683/). What do you think @aktech ?

**Comment by aktech** [comment]
> I do see two slots on the meetup page.

+1 I think we can have it on this meetup.

**Comment by shagunsodhani** [comment]
Could you please add it to the meetup page @aktech . And @Tanya-Jain could you please add a link to the slides (even if it is a WIP)

**Comment by aktech** [comment]
@shagunsodhani I have added this talk on the [meetup page](https://www.meetup.com/pydelhi/events/238176683/). @Tanya-Jain See you at the meetup.

**Comment by shagunsodhani** [comment]
:+1:

**Comment by sourabhtk37** [comment]
@Tanya-Jain please provide the slides for this talk
