### ISSUE TITLE
Open Daylight

### ISSUE THREAD

**Issue by akshayaurora** [pydelhi/talks#6]
Invite Sridhar from [OpenDaylight][1] to talk about the python app he did for managing . Details will be added soon.

Update:  
The people from open daylight would be coming for the  19th meet. Not for the 5th.
Mail sent for getting details, will updated when we get a response.

[1]:https://www.opendaylight.org

**Comment by theskumar** [comment]
@akshayaurora What's the status of this. I'm moving this to 17th Oct milestone for voting. If it's not possible on 17th, do inform.
