### ISSUE TITLE
Real time push notifications with Python , Gevent , Redis and Nginx .

### ISSUE THREAD

**Issue by aregee** [pydelhi/talks#60]
The idea is to implement a Pipeline based architecture where a message would come off of Redis queue and run through a pipeline of transformations and published to frontend or mobile clients using Nginx-push-stream module.

**Comment by aregee** [comment]
I intend to cover similar aspects mentioned in #39  along with hands on implementation of push notification service, please let me know if this talk is feasible.

**Comment by shagunsodhani** [comment]
@aregee This sounds very interesting. How much time do you think you would need. Also, it would be very helpful if you could please add your slide deck (even if it is a work in progress)

**Comment by aregee** [comment]
@shagunsodhani 
Link to [repo](https://github.com/aregee/teteris.py/) and [deck](https://github.com/aregee/teteris.py/blob/master/pitch.pdf) wip

**Comment by shagunsodhani** [comment]
@aregee This looks great :+1:

**Comment by akshayaurora** [comment]
@aregee can you give this talk in our next meetup on 22 July ?

**Comment by shagunsodhani** [comment]
@akshayaurora lets close this issue then. I can not close issues so you would have to do it.
