### ISSUE TITLE
Tail call optimization and Memoization in Python

### ISSUE THREAD

**Issue by cosmologist10** [pydelhi/talks#61]
- This talk will cover:
  1. Why Python doesn't optimize tail recursion.
   2. Tail Call Optimization using some libraries.
   3. Memoization in Python. 
   4. Visualization

 Will explain the above topics using Fibonacci sequence.

-This talk would be ~30 minutes long.
-The link to the slides will be updated on Thursday.

**Comment by akshayaurora** [comment]
@cosmologist10 would you be up to give your talk in this upcoming meetup?

**Comment by cosmologist10** [comment]
Yeah, I'll be delivering my talk this Saturday(22nd July).

**Comment by cosmologist10** [comment]
The slides of my talk: http://slides.com/shwetasuman/tail-call-optimisation#/
Codes: https://github.com/cosmologist10/Tail-call-optimization-and-memoization-in-Python
