### ISSUE TITLE
Getting started with Flask and SQLAlchemy 

### ISSUE THREAD

**Issue by bhaveshAn** [pydelhi/talks#62]
- Title

Getting started with Flask and SQLAlchemy 
- Brief description about the content to be covered

This will cover Introduction to Flask and SQLAlchemy and to develop a simple data driven web application using these libraries.

- Time required for the talk

About 30-40 minutes.
- About yourself

Hi, I am Bhavesh Anand, B.Tech IT final year student from G.B. Pant University of Agriculture and Technology, Pantnagar.

**Comment by akshayaurora** [comment]
@bhaveshAn up to give the talk on this meet? 22nd July?

**Comment by bhaveshAn** [comment]
Yes @akshayaurora on 22nd July!

**Comment by aktech** [comment]
@bhaveshAn available for this talk on next meetup, [19th August](https://www.meetup.com/pydelhi/events/241079149/)?

**Comment by bhaveshAn** [comment]
@aktech Can confirm the talk and its title only after knowing the venue.

**Comment by rajataaron** [comment]
@bhaveshAn are you available to give your talk on  17th feb.

**Comment by rajataaron** [comment]
Hi @bhaveshAn are you available to deliver your talk on [17th March](https://www.meetup.com/pydelhi/events/247118303/) meetup?

**Comment by rajataaron** [comment]
Due to no communication with the speaker we are closing this issue. In case @bhaveshAn you want to deliver your talk at the meetup you can create your issue again. :)

Thanks,
