### ISSUE TITLE
Talk Proposal: Dabbling with Decorators

### ISSUE THREAD

**Issue by suheb** [pydelhi/talks#63]
- Title
 Dabbling with Decorators

- Brief description about the content to be covered
I'll be talking about Decorators, a very powerful design pattern to extend the functionality of function, method or class in Python.

- Time required for the talk
30 mins

- About yourself
I'm currently a Software Developer at Zomato. I've also been a GSoC student and mentor in the past couple of years. I briefly worked at Aspiring Minds as a Research Engineer.

**Comment by aktech** [comment]
Hey @suheb are you available for this talk in the next meetup on [Saturday, September 16, 2017](https://www.meetup.com/pydelhi/events/240633979/)

**Comment by suheb** [comment]
@aktech Yes, I'm available. Looking forward to it.

**Comment by aktech** [comment]
Cool! Adding you for the next Meetup.

**Comment by akshayaurora** [comment]
@aktech @suheb was this talk delivered?

**Comment by suheb** [comment]
@akshayaurora No, it wasn't. But I'm available to deliver the talk on next meetup i.e. 28th Oct.

**Comment by realslimshanky** [comment]
@suheb are you available on 25th November to deliver this talk?

**Comment by suheb** [comment]
@realslimshanky I wasn't available this weekend. Would love to deliver this talk at the next meetup.

**Comment by realslimshanky** [comment]
@suheb great. Would you like to join [Telegram group for volunteer](https://t.me/joinchat/AAAAAEK2nzPg0IlwbbAing) so we can keep in touch?

**Comment by rajataaron** [comment]
@suheb are you available to give your talk on 17th feb meetup?

**Comment by suheb** [comment]
@rajataaron Sorry for the late reply. Unfortunately, I won't be available tomorrow i.e. 17th Feb.

**Comment by rajataaron** [comment]
Hi @suheb are available to deliver your talk on our next meetup which is on [17th March](https://www.meetup.com/pydelhi/events/lvkpknyxfbwb/).

**Comment by suheb** [comment]
@rajataaron I'm available this Saturday. Hope to see you at the meetup.

**Comment by rajataaron** [comment]
Cool I am putting you on the schedule.

**Comment by rajataaron** [comment]
Hi @suheb , can you deliver your talk at PyDelhi next meetup which is on 12th May?

**Comment by suheb** [comment]
Yes, I'm available. You can put me on the schedule.

**Comment by rajataaron** [comment]
@suheb . Thanks for confirming your talk I am putting you on schedule.
