### ISSUE TITLE
Talk Proposal : Writing Web Apps in Python using Django

### ISSUE THREAD

**Issue by pythongiant** [pydelhi/talks#68]
- Title :  Writing Web Apps in Python using Django

- Brief description about the content to be covered:
Motive of the talk is to get the audience write their first web app in python using django.

- Time : 30-45 minutes

- Link to slides / demos / any other content (if any):
https://drive.google.com/open?id=1gGFqVwPkg-besPNui1bwETq68lLNDyIT

- About yourself:
Hi,I am Srihari Unnikrishnan, a passionate and enthusiastic programmer. I am 14 years old and I have been coding since 7. I like Python ,C++,Web Development,IOT and Machine Learning. You can check out my github profile [here]( https://github.com/pythongiant)

**Comment by realslimshanky** [comment]
LGTM. @pythongiant, we're scheduling your talk on 25th November from 12 PM to 1PM. Will this be okay with you?

**Comment by realslimshanky** [comment]
@aktech this issue can be closed with the 'Delivered' tag as it has been delivered and added to README.md
