### ISSUE TITLE
Proposal : Implementing efficient Data Structures in Python

### ISSUE THREAD

**Issue by sriramr98** [pydelhi/talks#69]
- Title : Implementing efficient Data Structures in Python

- In this talk, we will be looking over common data structures required by any software developer to be efficient with data. Structuring data properly is key in optimizing algorithms. We will try to implement common data structures and try to optimize it considering memory and time efficiency.

- This talk requires about 1 hour to 1:30 hours.

- This is hands on codelab. There are no slides. I have started implementing some data structures. You can check that out in my GitHub repo : https://github.com/sriramr98/Data-Structures-and-Algorithms

- I am a 3rd year Nanotechnology student from Amity University with experience in Android and Python Development.

**Comment by realslimshanky** [comment]
@sriramr98 would you be available for this talk on the upcoming 9th December meetup?
PS: what's the update on your talk repository?

**Comment by sriramr98** [comment]
Yeah I will be able to give a talk on 9th. I have implemented the
algorithms. I will commit the changes by tomorrow positively.

**Comment by realslimshanky** [comment]
@sriramr98 Great. Waiting to hear from your about the updates.

**Comment by realslimshanky** [comment]
@aktech this issue can be closed with the 'Delivered' tag as it has been delivered. #73 will add this talk to README.md

**Comment by sriramr98** [comment]
Actually it hasn't been given as I couldn't come. I would love to give the
talk on the first meetup in Jan'19

**Comment by realslimshanky** [comment]
Okay, let me verify and fix README.md. sorry @aktech for the confusion we can leave the issue open for now.

**Comment by realslimshanky** [comment]
@sriramr98 are you available for the meetup on [13th January](https://www.meetup.com/pydelhi/events/lvkpknyxcbjb/).

**Comment by sriramr98** [comment]
Yeah. I will be able to give the talk then.

On 03-Jan-2018 7:24 PM, "Shashank Kumar" <notifications@github.com> wrote:

@sriramr98 <https://github.com/sriramr98> are you available for the meetup
on 13th January <https://www.meetup.com/pydelhi/events/lvkpknyxcbjb/>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pydelhi/talks/issues/69#issuecomment-355016935>, or mute
the thread

**Comment by Gouravchawla** [comment]
@shashank we can mark this delivered now.

**Comment by realslimshanky** [comment]
> @shashank we can mark this delivered now.

Sure. @aktech please help up with this.

**Comment by aktech** [comment]
Done.
