### ISSUE TITLE
Intro to Ansible

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/talks#7]

**Comment by akshayaurora** [comment]
:+1:

**Comment by CuriousLearner** [comment]
:+1:

**Comment by amitt001** [comment]
:+1:

**Comment by ajoyoommen** [comment]
+1

**Comment by theskumar** [comment]
@bhanuvrat i'm moving this to 17th Oct, milestone for voting. Please let us know if you can't be available on that day. 

It would be great if you can add a url a presentation for this talks. Thanks.

**Comment by dusual** [comment]
@bhanuvrat @theskumar I think this talk has been delivered hasn't it.

**Comment by CuriousLearner** [comment]
Yes, it was delivered in last meet-up.

**Comment by bhanuvrat** [comment]
it wasn't recorded properly, plus the audience less too.
we can do it again - if and when we are in need of a talk.

On Mon, Oct 12, 2015 at 10:16 AM, Sanyam Khurana <notifications@github.com>
wrote:

> Yes, it was delivered in last meet-up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydelhi/talks/issues/7#issuecomment-147291224>.
>



-- 
Anuvrat Parashar
http://anuvrat.in

**Comment by akshayaurora** [comment]
@bhanuvrat if we want to do it again then this needs to be opened up as a new issue so people can vote from fresh.
