### ISSUE TITLE
Proposal: Python for IoT

### ISSUE THREAD

**Issue by abhi2898** [pydelhi/talks#70]
I can talk on using Python for the Raspberry Pi and can talk about various libraries for developing something integrating various sensors.

**Comment by realslimshanky** [comment]
Could you please elaborate on what are all the topics you are covering, what part of those will you be live coding and what else will you be explaining via presentation?

**Comment by CuriousLearner** [comment]
Do you have any updates here @abhi2898 ?

**Comment by rajataaron** [comment]
@CuriousLearner I think we should close this issue now.
