### ISSUE TITLE
Talk Proposal: Nonstationary Signal Analysis with PyTFTB

### ISSUE THREAD

**Issue by jaidevd** [pydelhi/talks#72]
**Nonstationary Signal Analysis with PyTFTB**

Most real-life time series signals are _nonstationary_, i.e they have rapidly varying frequency content. Conventional signal processing tools like Fourier analysis are limited only to stationary signals. This talk introduces the PyTFTB project which is a set of tools that adapt Fourier analysis for nonstationary signals

**Time Required**: 30 mins

**Comment by realslimshanky** [comment]
Do you have slides for the talk or you'll be directly showcasing code?

**Comment by realslimshanky** [comment]
@aktech this issue can be closed with the 'Delivered' tag as it has been delivered and added to README.md. @jaidevd you can update the README.md with presentation link or repository. #73 is updating your talk.
