### ISSUE TITLE
Proposal: A hacker's primer to Free and Open Source License

### ISSUE THREAD

**Issue by hargup** [pydelhi/talks#74]
## A hacker's primer to Open Source License

Time: 30 min
Date: 13th January 2017

Choosing an FOSS license is one of the most important decision a project maintainer makes. The license determines which projects/libraries can be used as sub components of the project, it determines who can use the project and it what ways and the license also has a huge influence on who will contribute to the project. Unfortunately, licenses are complicated and often a develop isn't sufficiently aware of the various factors which should be taken care of while choosing a license. In this talk, building on the principles from copyright law, I'll demystify licenses so that people can make an informed choice.

## About me

I have been a core contributor to [SymPy](http://sympy.org) and have participated in various open source communities. The content of the talk will be derived form this experience and learning from a semester long course on Copyright at IIT Kharagpur.

**Comment by realslimshanky** [comment]
Hi @hargup, we have a spot available for 13th January meetup. Should we confirm your talk? Also, please share your contact details on abc [at] shanky [dot] xyz. You can also join the [telegram](https://t.me/joinchat/AAAAAEK2nzPg0IlwbbAing) volunteer group.

**Comment by hargup** [comment]
Thanks! please confirm the talk. My email is mail@hargup.in

**Comment by Gouravchawla** [comment]
@hargup Can you add your presentation link here? We'll mark it delivered with a link to your presentation.

**Comment by hargup** [comment]
Here is the link https://www.dropbox.com/s/l4b6e3ds6tpghgf/foss_licenses_talk_py_delhi.pdf?dl=0
:)

**Comment by Gouravchawla** [comment]
Thanks @hargup. @shashank Can we mark this delivered?
