### ISSUE TITLE
APIs using Google Cloud Endpoints

### ISSUE THREAD

**Issue by m-murad** [pydelhi/talks#75]
- Title 
Developing APIs using Google Cloud Endpoints Framework

- Brief description about the content to be covered
Developing, designing and deploying APIs using Google Cloud Endpoint Framework for App Engine.

- Time required for the talk
30 mins

- About yourself
I'm an opensource enthusiast working on android and python. I work with organisations like JBoss mentoring students who code.

**Comment by rajataaron** [comment]
Hi @m-murad,
Are you available to deliver your talk in upcoming next meetup which is on [17th Feb](https://www.meetup.com/pydelhi/events/lvkpknyxdbwb/)?

**Comment by m-murad** [comment]
yes, I will be available.

**Comment by rajataaron** [comment]
Ok, then I am putting you on schedule. 
:)

**Comment by m-murad** [comment]
What is the venue of the Meetup?

**Comment by rajataaron** [comment]
Venue is [Fueled, Noida](https://www.google.co.in/maps/place/Fueled+Noida/@28.5800065,77.3177433,15z/data=!4m5!3m4!1s0x0:0xba21b54ac5e81201!8m2!3d28.5800065!4d77.3177433)

**Comment by rajataaron** [comment]
Hi @m-murad, are you available to deliver your talk on 14th April? The venue is Investopad, Gurugram.

**Comment by rajataaron** [comment]
Hi @m-murad, are you available to deliver your talk on 12th May?

**Comment by rajataaron** [comment]
Hi @m-murad are you available to deliver your talk on 23rd March meetup?

**Comment by m-murad** [comment]
I have moved out of the city, Closing this.
