### ISSUE TITLE
Proposal: Simple Voter System : Django 101

### ISSUE THREAD

**Issue by sriramr98** [pydelhi/talks#76]
- Simple Voter System : Django 101

- This is an introductory hands on coding lab where we create a simple Voter System Website using Django Framework

- Time required for the talk : 1 hr - 1:30 hrs

- Github Link to the code : https://github.com/sriramr98/Voter-System/ 

- I am an Android Developer and a beginner Django Developer.

- The github code will be updated with the finished code within a week. 

*  Its recommended that people install the following before attending the talk
    * Python 3.5 +
    * Atom/ Sublime Text 3 (preffered. Any good text editor will do)
    * Windows user need a unix terminal (HINT : GitBash)
    * Python Virtual Env Recommended. Not necessary

**Comment by Gouravchawla** [comment]
Can we mark this as done? @shashank @amit
