### ISSUE TITLE
Proposal: Understanding strings in Python

### ISSUE THREAD

**Issue by satwikkansal** [pydelhi/talks#77]
The talk is designed to give the audience a better insight of Python strings by first demonstrating them snippets with unexpected outcomes and then later diving into the concepts behind the outcomes.

 Consider these snippets

        >>> a = "some_string" # first snippet
        >>> id(a)
        140420665652016
        >>> id("some" + "_" + "string")
        140420665652016

        >>> a = "foo" # second snippet
        >>> b = "foo"
        >>> a is b
        True
        
        >>> a = "foo!"
        >>> b = "foo!"
        >>> a is b
        False
        
        >>> 'a' * 20 is 'aaaaaaaaaaaaaaaaaaaa' # third snippet
        True
        >>> 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
        False

These outcomes may seem baffling to some programmers at first, but all of them are consequences of how (native) string interning works in Python.

So there are 3 key things I’d be explaining in the talk one by one with the help of “examples and then explanation” approach:
    1. Strings are immutable sequences.
    2. String interning (which is possible because strings are immutable)
    3. Best ways for string concatenation (based on the knowledge of above two and some CPython optimizations)

And there are few more tricky snippets (related with concepts like “implicit string literal concatenation”, “backslashes in raw string literals”, etc) which I’ll be explaining at the end (if time allows).

- Time required for the talk
30-45 mins

- Link to slides / demos / any other content (if any)
I wrote a blog post recently on similar lines. Here's the link: [Do you really think you know strings in Python](https://www.codementor.io/satwikkansal/do-you-really-think-you-know-strings-in-python-fnxh8mtha)

- About yourself
I'm a freelance developer, programming in Python for 3 years now.
https://satwikkansal.xyz

**Comment by aktech** [comment]
@satwikkansal Thanks for the proposal. Will you be available for the talk on the meetup after the next on [17th Feb, 2017](https://www.meetup.com/pydelhi/events/lvkpknyxdbwb/)?

**Comment by satwikkansal** [comment]
Hey @aktech, 17th Feb is my college fest day (and it's kind of my last fest), can it be considered for the next available slot?

**Comment by aktech** [comment]
@satwikkansal Yes, sure it's up to you.

**Comment by satwikkansal** [comment]
Alright, I guess I'd prefer to wait for the next meetup then 😅

**Comment by rajataaron** [comment]
@satwikkansal are you available to deliver your talk on 14th April meetup?

**Comment by satwikkansal** [comment]
@rajataaron I'm afraid it won't be possible on 14th April.

**Comment by satwikkansal** [comment]
Can you please let me know the dates of next meetups? I guess it happens every alternate week, right?

**Comment by satwikkansal** [comment]
Thanks, I can't make it to this one, but I'll definitely inform you at least a week before next meetup?

**Comment by Pradhvan** [comment]
This would be an interesting talk.

**Comment by satwikkansal** [comment]
Hey all, I'd love to have this session considered for upcoming meetups. Please let me know if there are slots available :)

**Comment by rajataaron** [comment]
Hi @satwikkansal you can choose a slot from 9th June and 7th July which feels right for you.

**Comment by satwikkansal** [comment]
9th June works

**Comment by aktech** [comment]
@satwikkansal Confirming this talk for 9th June 2018. Looking forward to it.

**Comment by rajataaron** [comment]
@satwikkansal as per the availability for 9th June I am putting you on schedule.
You can check schedule [here](https://www.meetup.com/pydelhi/events/248955397/)

**Comment by satwikkansal** [comment]
Location is Gurgaon, right?

**Comment by satwikkansal** [comment]
Never mind, just checked the event description, it's yet to be decided :+1:

**Comment by rajataaron** [comment]
Location is not confirmed yet @satwikkansal

**Comment by rajataaron** [comment]
@CuriousLearner now you can close this issue. The talk has been delivered successfully.
