### ISSUE TITLE
Suggestion : Advanced git Class

### ISSUE THREAD

**Issue by vipulgupta2048** [pydelhi/talks#78]
- Advanced concepts used in git such rebasing (and its types), cherry picking, troubleshooting, Merging and rebasing, resets and reverts, checkouts, tips and tricks for experienced users. Could include a little about how git works behind the scenes and other fine details about git. 

- Time required for the talk

- Link to slides / demos / any other content (if any)

- About Yourself

- Any comments

**Comment by vipulgupta2048** [comment]
Anybody would like to take this up ?

**Comment by rajataaron** [comment]
Is this proposal or Suggestion @vipulgupta2048 ?

**Comment by rajataaron** [comment]
@vipulgupta2048 can you change the title from Proposal to "Suggestion" so it will help us also to differentiate.
