### ISSUE TITLE
Custom Amazon Alexa skill using Python Flask

### ISSUE THREAD

**Issue by iayanpahwa** [pydelhi/talks#79]
- Title: Alexa Skill development using Python Flask Ask 

- Description:- Build your own custom Alexa skill using Amazon Alexa voice kit, Python and Flask-Ask framework

- Time required:- 1 hour 

- Link to slides / demos / any other content (if any) :- [WIP]

- About yourself :- [Just a techy](https://iayanpahwa.github.io/about/)

- Any comments:- I Shall not be available to deliver this talk in the month of February

**Comment by rajataaron** [comment]
Hi @iayanpahwa ,
Are you available to deliver your talk at our next meetup which is on [17th Feb](https://www.meetup.com/pydelhi/events/lvkpknyxdbwb/)?

**Comment by iayanpahwa** [comment]
@rajataaron I shall be available during March. Please let me know 2 weeks prior at best possible, thanks! :)

**Comment by Aviral190694** [comment]
No offence but Flash Ask is not worth putting a lot of resource in. Amazon Lambda with python are very powerful :)

**Comment by iayanpahwa** [comment]
@Aviral190694 you use what works for you :)

**Comment by aktech** [comment]
Hey @iayanpahwa Thanks for the proposal, we are looking forward to your talk. I will let you know about the possible dates soon.

**Comment by rajataaron** [comment]
Hi @iayanpahwa are you available to deliver your talk on our next meetup which is on [17th March](https://www.meetup.com/pydelhi/events/lvkpknyxfbwb/).

**Comment by iayanpahwa** [comment]
@rajataaron , sorry I'm not available for this one, Maybe next month would be able to deliver this talk, thanks! :)

**Comment by rajataaron** [comment]
@iayanpahwa are you available to deliver your talk on 14th April?
