### ISSUE TITLE
Automatic Data Validation and Cleaning

### ISSUE THREAD

**Issue by jaidevd** [pydelhi/talks#8]
Hey guys,

I had a proposal at PyCon 2015 (https://in.pycon.org/cfp/pycon-india-2015/proposals/automatic-data-validation-and-cleaning-with-pysemantic/), which didn't get selected. If you don't mind, I'd like to deliver the talk at our meetup on 17th Oct 2015

**Comment by akshayaurora** [comment]
+1 as a workshop,  had a talk with jade and he would be able to deliver this as a workshop.

**Comment by theskumar** [comment]
@jaidevd We are confirming this as workshop for 17th Oct. Wish you best of luck! :blush:

**Comment by jaidevd** [comment]
Thanks! Will put up the requirements shortly.
