### ISSUE TITLE
Handson on Debian packaging of nodejs modules

### ISSUE THREAD

**Issue by Manas-kashyap** [pydelhi/talks#80]
It will be a Hands-on to pack some small modules of nodejs for Debian, I will also cover some tools like npm2deb and other tools like lintian , and fixing some patches using Quilt .

Expected Duration
1hr to 1:30 hr

Track
ILUG-D talks are divided intro three tracks:
- Beginner

Pre-requisite
Laptop with Debian sid in the docker.
good internet connection.

[Debian_packaging.pdf](https://github.com/pydelhi/talks/files/1703941/Debian_packaging.pdf)

**Comment by rajataaron** [comment]
@Manas-kashyap as you have opened new issue can I close this one?
