### ISSUE TITLE
Gotchas In Python

### ISSUE THREAD

**Issue by igauravsehrawat** [pydelhi/talks#81]
- Title
Gotchas In Python

- Brief description about the content to be covered
I will be talking about potentially tricky behavior in Python code. I will be using short codes for these peculiar behavior and way to get around it. No more surprises from Python. :)

- Time required for the talk
30-40 minutes

- Link to slides / demos / any other content (if any)
http://igauravsehrawat.com/MyTalks/PyDelhi/Gotchas%20In%20Python.slides.html#/

- About yourself
https://twitter.com/Root3d

- Any comments
I will be available for the [17th Feb](https://www.meetup.com/pydelhi/events/246930622/) slot

**Comment by aktech** [comment]
@igauravsehrawat Thanks for the proposal, I have scheduled your talk for the next meetup on [17th February, 2018](https://www.meetup.com/pydelhi/events/246930622/)

**Comment by igauravsehrawat** [comment]
That's great.

Thanks
