### ISSUE TITLE
Firebase for Android

### ISSUE THREAD

**Issue by jatinkatyal13** [pydelhi/talks#82]
# Firebase for Android

**Abstract**

With smartphone becoming dominant mobile applications has become a popular way to find new ways to interact with users. Many small scale developers face scalability and performance bottleneck of their application due to lack of resources. Here Firebase comes into picture to handle all that for the developers

**About**

* Why Firebase?
    - Real-time database
    - Authentication
    - Cross Platform

* Real life use of Firebase with android

**Format**

* Hands on session

**Pre-requisites**

* Android Studio Installed

* Basic programming concepts

* Basic Java knowledge

**Expected duration**

* 90 mins

**Level**

* Intermediate

**Previous Experience/Sample ppt**

* [Introduction to Machine Learning](https://github.com/proximus-coding-society/Intro-to-ML)

**Speaker Bio**

* [Jatin Katyal](https://github.com/jatinkatyal13)

**How will it help developers/students**

Developers/Student after this session will be able to code their own real time application using Firebase. They can use Firebase SDK to easily integrate Google and Facebook Login in their application.

**Comment by rajataaron** [comment]
Hi @jatinkatyal13, are you using Python in it?

**Comment by jatinkatyal13** [comment]
@rajataaron No purely on Android with Firebase sdk.

**Comment by rajataaron** [comment]
Hi @jatinkatyal13 , Sorry for late reply, 17th March slots are full right now can I put you on 31st March meetup?

**Comment by jatinkatyal13** [comment]
@rajataaron No problem !

**Comment by rajataaron** [comment]
Hi @jatinkatyal13 are you free today?
Is it possible for you to deliver your talk today? I know its urgent call but we got some issues today so thats why.

**Comment by jatinkatyal13** [comment]
@rajataaron I am really sorry sir but as of now I am out of town. I will be back by 22 March.

**Comment by rajataaron** [comment]
Hi @jatinkatyal13 ,
Sorry for last time, last minute call is done by me. Is it possible for you to deliver a talk on 14th April meetup?

**Comment by jatinkatyal13** [comment]
@rajataaron sure! Let me know the details of the meetup .

**Comment by rajataaron** [comment]
@jatinkatyal13 Hi, so we have a meetup next week on 14th April at Investopad, Gurgaon it is a collaboration with ILUG-D. Are you available to deliver your talk on that day?

**Comment by rajataaron** [comment]
Hi @jatinkatyal13  , are you available to deliver your talk on 12th May meetup?

**Comment by jatinkatyal13** [comment]
Sure ! Please contact me with all the details of the meetup over the night email.

**Comment by rajataaron** [comment]
@jatinkatyal13 sent you the mail please check.

**Comment by rajataaron** [comment]
@CuriousLearner you can close this issue now. The talk has been delivered successfully.
