### ISSUE TITLE
AWS Dynamo Nosql managed service

### ISSUE THREAD

**Issue by tannubansal** [pydelhi/talks#83]
- Title
 AWS Dynamo DB

- Brief description about the content to be covered
I would like to speak about Aws dynamodb, basics and why to use it.

- Time required for the talk 
30-45 mins

- Link to slides / demos / any other content (if any)
Not yet

- About yourself
I am expert in AWS and running my own start up for aws consulting

- Any comments

**Comment by aktech** [comment]
Hey @tannubansal Thanks for the proposal, we are looking forward to your talk. I will let you know about the possible dates soon.

**Comment by rajataaron** [comment]
Hi Tanu,
As per our conversation, I am scheduling your talk for our 10th March meetup which is on International Women's Week at [Adobe](https://www.google.co.in/maps/place/Adobe+Systems+India+Pvt.+Ltd/@28.587765,77.3429021,16.75z/data=!4m13!1m7!3m6!1s0x390ce5a43173357b:0x37ffce30c87cc03f!2sNoida,+Uttar+Pradesh!3b1!8m2!3d28.5355161!4d77.3910265!3m4!1s0x0:0x8858fb4aca48b216!8m2!3d28.5890449!4d77.3447196). 
See you at the meetup. :)

**Comment by CuriousLearner** [comment]
Talk has been delivered.
Closing down this issue.
