### ISSUE TITLE
Understanding GIL Python

### ISSUE THREAD

**Issue by karanjot-bhasin** [pydelhi/talks#84]
- Title
Python GIL impact 
- Brief description about the content to be covered
Impact of GIL ON Python concurrency and parallelism
- Time required for the talk
1 hr
- Link to slides / demos / any other content (if any)

- About yourself
4+ years in Python Developement
- Any comments

**Comment by aktech** [comment]
Hey @karanjot-bhasin Thanks for the proposal, we are looking forward to your talk. I will let you know about the possible dates soon.

**Comment by rajataaron** [comment]
Hi @karanjot-bhasin are you available to deliver your talk for our next meetup which is on [17th March](https://www.meetup.com/pydelhi/events/lvkpknyxfbwb/).

**Comment by rajataaron** [comment]
Hi @karanjot-bhasin are you available to deliver your talk for our next meetup which is on [12th May](https://www.meetup.com/pydelhi/events/mglhqpyxhbqb/)?

**Comment by aaqaishtyaq** [comment]
Hi @karanjot-bhasin are you available to deliver your talk for our next meetup which is on 27th Oct

**Comment by rajataaron** [comment]
Due to no communication with the speaker we are closing this issue. In case of @karanjot-bhasin you want to deliver your talk at the meetup please create issue again.

Thanks,
