### ISSUE TITLE
Proposal: Connecting AI & IoT

### ISSUE THREAD

**Issue by sidagarwal04** [pydelhi/talks#86]
- Title: Connecting AI & IoT

- Brief description about the content to be covered: The talk will be an introduction to AI,ML,DL and how to connect AI & IoT together. The talk will cover Intel IoT architecture, AWS IoT stack, GCP IoT Core along with understanding on image recognition, image analysis and speech recognition.

- Time required for the talk: 45 minutes to 1 hour

- Link to slides / demos / any other content (if any)

- About yourself: I currently work as an Ecosystem Engagement Manager at Beahead Private Limited. I am also an Intel Software Innovator, Oracle Certified Java Professional, Google AdWords Certified Professional and recipient of Google India Challenge Scholarship 2018. I have been involved in delivering trainings on topics like: Internet of Things, Artificial Intelligence, Machine Learning, Deep Learning, Neural Networks, Scratch and App Inventor at various national and international platforms. I also execute Google Design Sprints – a Design Thinking and Agile Development Methodology focused workshop series to improve the UX of applications by focusing on Unified User Experience and helps support various early stage start-ups and aspiring entrepreneurs on UX designing.

- Any comments

**Comment by sidagarwal04** [comment]
Hey Amit,

Thanks for the response. I missed out on mentioning this in the proposal, I
am looking forward to have a session on 10th March at your event happening
@ Adobe, Noida. Will it be possible to accommodate this session during that
day?

Looking forward to hear from you. Please feel free to reach out to me on
+91-9675196465/+918178430309.

Thanks!

Regards,
Siddhant Agarwal
- Sent from my android phone

**Comment by rajataaron** [comment]
Hey @sidagarwal04 ,
Sorry to tell you that we are full of slots if you want we can accommodate you at our next meetup which is on 17th March.

**Comment by sidagarwal04** [comment]
Hey @rajataaron,
Thanks for the response. 'Will let you know my availability by end of this week for 17th March. Will that work?

**Comment by rajataaron** [comment]
Hi @sidagarwal04 
Any updates on your availability for 17th March meetup?

**Comment by sidagarwal04** [comment]
Hey Rajat,

Somehow missed responding to this. I should be available on 17th March. Can
you share with me details regarding the meetup - venue, timings, target
audience?

Siddhant Agarwal
- Sent from my android phone

**Comment by rajataaron** [comment]
Sorry, to tell you that our all slots are full for 17th March meetup. Let me know your availability for 31st March meetup?
We always get an 80% of students and 20% of professional as an audience.

**Comment by realslimshanky** [comment]
Hi @sidagarwal04 , would you be available to give a talk on this topic for a 30/45 minutes session on [31st March](https://www.meetup.com/pydelhi/events/lvkpknyxfbpc/) meetup?

**Comment by sidagarwal04** [comment]
Hey @realslimshanky, Sure. Can we have a quick call to discuss further on this? I am available on +919675196465

**Comment by realslimshanky** [comment]
@sidagarwal04 you can edit out your number. We'll reach out to you in the morning.

**Comment by realslimshanky** [comment]
@sidagarwal04 please add your presentation url.

**Comment by sidagarwal04** [comment]
@realslimshanky The talk will cover AI powered Speech Recognition: Speech to text conversion on edge and cloud along with Text Analysis and AI powered Image Recognition and Image Analysis along with demos. I won't be able to share slide deck as it is proprietary content from Intel. However, you can check out github repo. The source code is available [here](https://github.com/sidagarwal04/ComputerVision-OpenCV-AWSRekognition) and [here](https://github.com/sidagarwal04/SpeechRecognition-Sphinx-GCP).

**Comment by realslimshanky** [comment]
HI @sidagarwal04 , [Here](https://www.meetup.com/pydelhi/events/lvkpknyxfbpc/)'s the schedule for 31st and you can contact Rajat or Gourav taking their numbers from the meetup page if you are facing any trouble regarding the location or any other problem. Please acknowledge. Thanks :)

**Comment by sidagarwal04** [comment]
Hi @realslimshanky, thanks for the update. Do we have HDMI cable connection at the venue?

**Comment by realslimshanky** [comment]
@rajataaron will help you out with cables.

**Comment by rajataaron** [comment]
Hi @sidagarwal04 yes, we have HDMI cable at the venue.

**Comment by sidagarwal04** [comment]
Hi @rajataaron, awesome. See you tomorrow @ 10.30. :)

**Comment by rajataaron** [comment]
@CuriousLearner you can close this issue as talk is delivered on 31st March event.
