### ISSUE TITLE
Basics: Logging in python

### ISSUE THREAD

**Issue by sourabhtk37** [pydelhi/talks#87]
- **Basics: Logging in Python**

- Will be covering logging in a python application. Discuss various techniques and methods that are available in the python logging module in the std lib. Including implementation/demo of sample application with logging.

- 45min - 1hour

- Slides : http://slides.com/tksourabh/basics-logging-in-python
- Resources: [Python logging module](https://docs.python.org/3.6/library/logging.html), [Intro tutorial](https://www.blog.pythonlibrary.org/2012/08/02/python-101-an-intro-to-logging/), [best practices](https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/) 

- Code: https://github.com/sourabhtk37/Presentations/tree/master/python_logging/

- I am an undergraduate computer science engineer residing in Delhi. Quite interested in Operating systems, Compilers and programming languages in general. 

- HDMI-to-VGA converter will be required if venue don't have HDMI connectors.

**Comment by realslimshanky** [comment]
Hi @sourabhtk37, would you be able to deliver this in form of a full session (30/45 minutes) on [17th March Meetup](https://www.meetup.com/pydelhi/events/lvkpknyxfbwb/)?

**Comment by sourabhtk37** [comment]
Sure.

**Comment by realslimshanky** [comment]
Nice. Please upload your slides.

**Comment by rajataaron** [comment]
@CuriousLearner can you close this issue

**Comment by CuriousLearner** [comment]
@sourabhtk37 Please upload your slides so we can close this one.

**Comment by sourabhtk37** [comment]
Already uploaded the slides. See description. Closing this.
