### ISSUE TITLE
-Google AMP for Django

### ISSUE THREAD

**Issue by shekankode** [pydelhi/talks#88]
-Google AMP for Django

- The talk will basically cover topics like What is AMP ?, How AMP works, Who is AMP for and how I implemented it with Django . The challenges developers face while making AMP pages and how to get over these and the alternate solutions for it . Django AMP tools and Problems Yet To Be Solved will be the concluding topic for the talk.

- 10-15 mins

- I am a full stack developer working with the development team of MyAdvo (www.myadvo.in) on Django and React and want to contribute to increase the representation of women in the STEM fields so that more women can learn how to code and become leaders in tech. I know how to code in Python, JS , HTML ,CSS , C, C++. and constantly working on myself to improve and increase my learning curve.    

-Thank you for organizing this meet up . This is definitely going to inspire more women to learn how to code and make them more aware about the tech field. Thanks a ton!

**Comment by rajataaron** [comment]
Hi @shekankode ,
This is a very interesting talk, we will definitely looking forward to it. And please do attend our [10th March meetup on International Women's Week](https://www.facebook.com/events/295003874359186/) at [Adobe](https://www.google.co.in/maps/place/Adobe+Systems+India+Pvt.+Ltd/@28.591319,77.3393546,16z/data=!4m5!3m4!1s0x0:0x8858fb4aca48b216!8m2!3d28.5890449!4d77.3447196?hl=en).

**Comment by realslimshanky** [comment]
Hi @shekankode, would you be able to deliver this talk on [17th March Meetup](https://www.meetup.com/pydelhi/events/lvkpknyxfbwb/)?

**Comment by shekankode** [comment]
Hi,
Thanks for the opportunity but  I won't be able to attend the coming meet
up in Noida on 17th March. Looking forward to deliver the talk in some
other meet up maybe , Thanks a lot again

**Comment by rajataaron** [comment]
Hi @shekankode ,

You can choose whichever date suits you from our schedule [here](https://www.meetup.com/pydelhi/events/). And Let us know.

Thanks.

**Comment by shekankode** [comment]
Will let you know soon . Thanks :)

**Comment by realslimshanky** [comment]
Hi @shekankode , would you be available to give a talk on this topic for a 30/45 minutes session on [31st March](https://www.meetup.com/pydelhi/events/lvkpknyxfbpc/) meetup?

**Comment by shekankode** [comment]
What would be the location of the meetup?

**Comment by realslimshanky** [comment]
@shekankode location is not yet confirmed. We'll update it on the [meetup page](https://www.meetup.com/pydelhi/events/247833216/) once we have a place

**Comment by shekankode** [comment]
Yes sure , thanks

**Comment by rajataaron** [comment]
Venue is updated on [meetup ](https://www.meetup.com/pydelhi/events/247833216/)page you can check it now: [Srijan Technologies](https://www.google.co.in/maps/place/Srijan+Technologies/@28.6268965,77.2214494,15z/data=!4m2!3m1!1s0x0:0xd3d1b298923c285?sa=X&ved=0ahUKEwiU0cnDt_3ZAhUIMo8KHdwjAPUQ_BIIsAEwCg)

**Comment by aaqaishtyaq** [comment]
Hi @shekankode are you available to deliver your talk for our next meetup which is on 27th Oct?
