### ISSUE TITLE
Telling stories with code

### ISSUE THREAD

**Issue by gurmanbh** [pydelhi/talks#89]
**The premise**
The talk will cover how code can work as a tool for storytelling - whether that is collection of information, or the actual communication of it. We'll walk through examples and techniques of using a scientific and logical process such as programming, and applying to something creative like storytelling.

**Duration:** 20 mins

**Slides:** http://bit.ly/pydelhi-stories

**Who am I?**
I am a data/interactive reporter at the Hindustan Times where I tell stories through code. I use d3.js, node.js and Python to collect, clean, analyse and visualise information. You can see more of my work here: www.gurmanbhatia.com

**Comment by realslimshanky** [comment]
Hi @gurmanbh, would you be available to give a talk on this topic for a full 45 minutes session on [31st March](https://www.meetup.com/pydelhi/events/lvkpknyxfbpc/) meetup?

**Comment by gurmanbh** [comment]
Hey Shashank. I can. However, I am only available till about 3 p.m. Also,
my work is very less python and a lot more js. Would that work?

**Comment by thisisayush** [comment]
Hi @gurmanbh,
> I am only available till about 3 p.m.

No Issues, we'll try to get your talk in the first available slot :) (11:30 - 12:15)

> my work is very less python and a lot more js. Would that work?

All talks are welcome, so yeah it'll be fine :)

**Comment by gurmanbh** [comment]
Can share the presentation url only by Saturday. Also, I need just 30 mins instead of 40. Happy to present! I'll drop you an email.

**Comment by realslimshanky** [comment]
Sure. :+1:

**Comment by realslimshanky** [comment]
@gurmanbh updates on the presentation?

**Comment by gurmanbh** [comment]
Hey Shashank

Sorry I haven't had the time and probably won't find time to finish before
Thursday.

In case it helps, here is an example to give you an idea. Earlier, I have
spoken about tasks in storytelling for code and humans:
http://bit.ly/codexnews

This talk is obviously different, but will draw 2-3 of the same examples.

**Comment by realslimshanky** [comment]
@gurmanbh sure. Please ping when you are done with the presentation. [Here](https://www.meetup.com/pydelhi/events/lvkpknyxfbpc/)'s the schedule for 31st and you can contact Rajat or Gourav taking their numbers from the meetup page if you are facing any trouble regarding the location or any other problem. Thank :)

**Comment by gurmanbh** [comment]
@realslimshanky - Here are the slides: http://bit.ly/pydelhi-stories

**Comment by rajataaron** [comment]
@CuriousLearner you can close this issue now. Talk is delivered on 31st March meetup.
