### ISSUE TITLE
Data Processing as a pipeline: Functional programming in python

### ISSUE THREAD

**Issue by ikilledthecat** [pydelhi/talks#9]
Setup a simple data processing pipeline using generators and coroutines with a sprinkling of some pandas goodness.

**Comment by akshayaurora** [comment]
Could we have some data  about the author plus some slides ?

**Comment by akshayaurora** [comment]
@ikilledthecat would be great if you could add some info about yourself and about the talk so it's easy for people to vote based on content.

**Comment by ikilledthecat** [comment]
Hey @akshayaurora . I'm new to pydelhi and i mostly work with bitbucket so apologies for taking time with this. 

My name's Prasanjit Prakash. I'm co founder and Tech lead at Xlott. We are a small startup in the tech recruitment space. We hope to provide analytical sourcing solutions to tech firms. We have tested our alpha and are in the final stages of beta.

I started programming in python about two years ago when our journey began. About half a year ago we pivoted into tech sourcing. So for the past six months i have been working to build a analytical engine to crawl, parse and analyze massive datasets.

In this talk I plan to walk through generators, co-routines in details and, depending to how much time I have, hopefully also walk through setting up a small data-pipeline to do some basic etl and some basic ranking using pandas. I'm still working on the slides, give me a day to have them up for everyone.

**Comment by akshayaurora** [comment]
@ikilledthecat don't worry about it and take your time, We can look at having this talk on 31st Oct.

I hope you don't mind. You can still showcase your work as a flash talk "15 minutes" on 17th. If you plan to do so please let us know and we can add you to the list of flash talks.

**Comment by ikilledthecat** [comment]
@akshayaurora Sure that works for me. I'd rather take up some more time and do it on a later date than do a flash talk. Since a flash talk is unlikely to do any justice to the topic.

**Comment by akshayaurora** [comment]
:+1: for 31st october.

**Comment by ikilledthecat** [comment]
@akshayaurora I apologize but I won't be in delhi this weekend. I had conveyed this to @bhanuvrat . Please see if you can shift it to a later date.

**Comment by ikilledthecat** [comment]
[Here's a draft presentation](https://drive.google.com/file/d/0B3hnCqTKLDVNTkVaY1RveXFJUTA/view?usp=sharing). The material is final i may remove code blocks from it though. Laso if anyone has any feedback I'll gladly incorporate things into the presentation.

**Comment by akshayaurora** [comment]
:+1:  for December 12th Meet

**Comment by akshayaurora** [comment]
This was delivered on December 12th
