### ISSUE TITLE
CodeWear (Lightning talk - IWW)

### ISSUE THREAD

**Issue by iayanpahwa** [pydelhi/talks#90]
- Title - Wearable Electronics and Fashion Technology

- Brief description about the content to be covered
When you talk about Wearable Electronics, first thing comes to mind might be a smart watch, google glass or similar gadgets, but a small subset of this growing tech field is also Fashion Technology, using LEDs on costumes and controlling them from sensors and microcontrollers for Cosplay and various other functions and utilities. In this lightning talk I'd be talking about how we can use FashionTechnology to educate and bring women in technology and programming, I'll also be bringing lots of similar demos and share how one can learn coding by making these cool projects.

- Time required for the talk
15 minutes

- Link to slides / demos / any other content (if any)

- About yourself
[Just a tech](https://iayanpahwa.github.io/about)

- Any comments: Technology can be fun, as we showcased in Rpi Jam last week: [Banana Piano](https://www.youtube.com/watch?v=sLuQt_Wn6ho)

**Comment by philo-math** [comment]
Looks like an awesome talk to me. Would like to present it on our next meetup on 17th march?

**Comment by rajataaron** [comment]
This talk is delivered on 10th March can you please close this issue @CuriousLearner
