### ISSUE TITLE
Proposal: Generators in Python

### ISSUE THREAD

**Issue by ArfatSalman** [pydelhi/talks#91]
Title
Generators in Python

Brief description about the content to be covered
I'll talk about how to use generators, and how they are a useful pattern in some cases. 

Time required for the talk
30 mins

About yourself
I'm currently a Senior Web Developer at Pesto Tech. I've programmed in python and flask since the last 3 years. Open source enthusiast, and frequent blogger.

**Comment by rajataaron** [comment]
Hi @ArfatSalman, are you available to deliver your talk on 14th April? The venue is Investopad, Gurgaon.

**Comment by ArfatSalman** [comment]
Yes. I am available to give the talk. The time will be 11:00 AM on the Saturday, 14th?

**Comment by rajataaron** [comment]
Yes you are right. If you agree then should I put you on schedule?

**Comment by ArfatSalman** [comment]
Yes. I agree. I will be available on Saturday, 14th. Thanks!

**Comment by rajataaron** [comment]
Can, I get your email ID so that we can send you an official mail?

**Comment by ArfatSalman** [comment]
Yes. It is giney.paradise@gmail.com 

I've connected with you on LinkedIn as well. 👍
