### ISSUE TITLE
Hands on Regex and it's optimization in Python

### ISSUE THREAD

**Issue by cosmologist10** [pydelhi/talks#92]
- Hands on Regex and it's optimization in Python

- The following sections, i will be covering in my talk : 
      1. Introduction of Regex and it's engine on algorithmic level
      2. Hands on regex problems using re module
      3. Cons of RE implemented in Python
      4. Overview of libraries that can solve those issues and will discuss the methods like Subroutine calls 
         and recursion, inline modifiers etc and algorithm behind it like Aho-Corasick , trie and Rope etc.

- 45 to 60 mins

- Will be updated soon.

- I am a Software intern at Gemini Solutions, working in Python from last 1.5 years. 

- The audience should have basic overview of Regex.

**Comment by cosmologist10** [comment]
Sure, I will deliver this talk in coming meetup.

**Comment by rajataaron** [comment]
@cosmologist10 are you available to deliver your talk on 7th July?
