### ISSUE TITLE
Proposal: I want to give a live presentation about the basics of ML in Python and my experience with it

### ISSUE THREAD

**Issue by yugkhanna** [pydelhi/talks#93]
- Learning about ML in Python

- I will cover the basics of data science and machine learning and would give a live demo of my kaggle competition where I am ranked in the top 1.2K people out of 11K

- Approximately 20 mins

- Slides not made yet. You can check my GitHub for the code.

- I'm an Indian student studying Computer Engineering at University of Waterloo Canada and am here in India for the summer working for a company and serving as a software developer intern.

- I think my experience with Python and Data Science and my skills will be helpful to people who want to go ahead in data science and people will be able to learn new skills and understand concepts better

**Comment by vipulgupta2048** [comment]
Hi, @yugkhanna can you please add a link to your slides for reference.
