### ISSUE TITLE
Deep learning/Machine Learning

### ISSUE THREAD

**Issue by jibinmathew69** [pydelhi/talks#95]
- Could speak on any of the topics stated in the title.

- I would leave it to the community to decide from any of the topics above.

- 1 hour or so

- Slides not yet done, but can do once confirmed.

- I am an AI consultant, working on AI and highly scalable Python projects, In the past, I worked as CTO and co-founder for various startups. Machine learning and Deep Learning are the areas of my inclination. I have worked in the domains of Predictive analytics, Computer vision, and NLU.

- I am on travel until May 15, any dates after that seem fine.

**Comment by rajataaron** [comment]
@jibinmathew691993 you can choose topic according to your comfort. After that we will schedule your talk accordingly.

**Comment by jibinmathew691993** [comment]
Ok, I'll take up some problem in Machine learning, in case if it's not already taken.

**Comment by rajataaron** [comment]
Hi @jibinmathew691993 are you available to deliver your talk on 16th Feb at Grofers, Gurgaon on ML or Data Science or Deep Learning?

**Comment by jibinmathew691993** [comment]
@rajataaron I am not available on 16th Feb.

**Comment by shreybatra** [comment]
Hii @rajataaron, i could deliver the lecture on ML / Flask + mongo on 16th. If you want.

**Comment by rajataaron** [comment]
Hi @jibinmathew691993,

Are you available to deliver your talk at our upcoming meetup which is on 23rd March?

**Comment by rajataaron** [comment]
@jibinmathew691993 can you update this issue with proper talk details or else you can create a new issue for the same with proper talk details it will help us to know on what you are going to talk.

Thanks,

**Comment by jibinmathew691993** [comment]
Sure, I have updated the issue, I'd be happy to speak on Deep Learning, Are all the talks situated in Gurgaon, It's way too far for me to reach, Do you have a location close to Delhi Noida?

**Comment by rajataaron** [comment]
We usually do a meetup in Delhi-NCR. And this time we are trying to get a venue in Delhi only. I will update you about the venue before the end of this week.
